// this file is automatically generated with SourceGear Bridge

#include <stdint.h>

#include "Microsoft_AspNetCore_Mvc_Cors.h"

extern void (*_sg_resolve_jumptable)(const char*, int, void*);

struct {
    TYP (* _Nonnull  _fp_Microsoft_AspNetCore_Mvc_Cors_CorsAuthorizationFilter_get_type_handle)(void);
    SG_HNDL_NONNULL (* _Nonnull  _fp_Microsoft_AspNetCore_Mvc_Cors_CorsAuthorizationFilter_ctor_0__2__ICorsService_ICorsPolicyProvider)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL corsService, SG_HNDL_NONNULL policyProvider);
    SG_HNDL_NONNULL (* _Nonnull  _fp_Microsoft_AspNetCore_Mvc_Cors_CorsAuthorizationFilter_ctor_0__3__ICorsService_ICorsPolicyProvider_ILoggerFactory)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL corsService, SG_HNDL_NONNULL policyProvider, SG_HNDL_NONNULL loggerFactory);
    SG_HNDL_NONNULL (* _Nonnull  _fp_Microsoft_AspNetCore_Mvc_Cors_CorsAuthorizationFilter_Task__OnAuthorizationAsync_0__1__AuthorizationFilterContext)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h, SG_HNDL_NONNULL context);
    SG_HNDL_NULLABLE (* _Nonnull  _fp_Microsoft_AspNetCore_Mvc_Cors_CorsAuthorizationFilter_String__get_PolicyName_0__0)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h);
    void (* _Nonnull  _fp_Microsoft_AspNetCore_Mvc_Cors_CorsAuthorizationFilter_void__set_PolicyName_0__1__String)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h, SG_HNDL_NULLABLE value);
    int32_t (* _Nonnull  _fp_Microsoft_AspNetCore_Mvc_Cors_CorsAuthorizationFilter_i32__get_Order_0__0)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h);
    SG_HNDL_NONNULL (* _Nonnull  _fp_Microsoft_AspNetCore_Mvc_Cors_CorsAuthorizationFilter_cast)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __h);
    SG_HNDL_NONNULL (* _Nonnull  _fp_Microsoft_Extensions_DependencyInjection_MvcCorsMvcCoreBuilderExtensions_IMvcCoreBuilder__AddCors_0__1__IMvcCoreBuilder)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL builder);
    SG_HNDL_NONNULL (* _Nonnull  _fp_Microsoft_Extensions_DependencyInjection_MvcCorsMvcCoreBuilderExtensions_IMvcCoreBuilder__AddCors_0__2__IMvcCoreBuilder_System_Action_Microsoft_AspNetCore_Cors_Infrastructure_CorsOptions_)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL builder, SG_HNDL_NONNULL setupAction);
    SG_HNDL_NONNULL (* _Nonnull  _fp_Microsoft_Extensions_DependencyInjection_MvcCorsMvcCoreBuilderExtensions_IMvcCoreBuilder__ConfigureCors_0__2__IMvcCoreBuilder_System_Action_Microsoft_AspNetCore_Cors_Infrastructure_CorsOptions_)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL builder, SG_HNDL_NONNULL setupAction);
} _g_Microsoft_AspNetCore_Mvc_Cors;

static void my_init() {
    _sg_resolve_jumptable("Microsoft_AspNetCore_Mvc_Cors", 29, &_g_Microsoft_AspNetCore_Mvc_Cors);
}

TYP Microsoft_AspNetCore_Mvc_Cors_CorsAuthorizationFilter_get_type_handle(void) {
    if (!_g_Microsoft_AspNetCore_Mvc_Cors._fp_Microsoft_AspNetCore_Mvc_Cors_CorsAuthorizationFilter_get_type_handle) {
        my_init();
    }
    TYP ret = _g_Microsoft_AspNetCore_Mvc_Cors._fp_Microsoft_AspNetCore_Mvc_Cors_CorsAuthorizationFilter_get_type_handle();
    return ret;
}

SG_HNDL_NONNULL Microsoft_AspNetCore_Mvc_Cors_CorsAuthorizationFilter_ctor_0__2__ICorsService_ICorsPolicyProvider(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL corsService, SG_HNDL_NONNULL policyProvider) {
    if (!_g_Microsoft_AspNetCore_Mvc_Cors._fp_Microsoft_AspNetCore_Mvc_Cors_CorsAuthorizationFilter_ctor_0__2__ICorsService_ICorsPolicyProvider) {
        my_init();
    }
    SG_HNDL_NONNULL ret = _g_Microsoft_AspNetCore_Mvc_Cors._fp_Microsoft_AspNetCore_Mvc_Cors_CorsAuthorizationFilter_ctor_0__2__ICorsService_ICorsPolicyProvider(__thrown, corsService, policyProvider);
    return ret;
}

SG_HNDL_NONNULL Microsoft_AspNetCore_Mvc_Cors_CorsAuthorizationFilter_ctor_0__3__ICorsService_ICorsPolicyProvider_ILoggerFactory(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL corsService, SG_HNDL_NONNULL policyProvider, SG_HNDL_NONNULL loggerFactory) {
    if (!_g_Microsoft_AspNetCore_Mvc_Cors._fp_Microsoft_AspNetCore_Mvc_Cors_CorsAuthorizationFilter_ctor_0__3__ICorsService_ICorsPolicyProvider_ILoggerFactory) {
        my_init();
    }
    SG_HNDL_NONNULL ret = _g_Microsoft_AspNetCore_Mvc_Cors._fp_Microsoft_AspNetCore_Mvc_Cors_CorsAuthorizationFilter_ctor_0__3__ICorsService_ICorsPolicyProvider_ILoggerFactory(__thrown, corsService, policyProvider, loggerFactory);
    return ret;
}

SG_HNDL_NONNULL Microsoft_AspNetCore_Mvc_Cors_CorsAuthorizationFilter_Task__OnAuthorizationAsync_0__1__AuthorizationFilterContext(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h, SG_HNDL_NONNULL context) {
    if (!_g_Microsoft_AspNetCore_Mvc_Cors._fp_Microsoft_AspNetCore_Mvc_Cors_CorsAuthorizationFilter_Task__OnAuthorizationAsync_0__1__AuthorizationFilterContext) {
        my_init();
    }
    SG_HNDL_NONNULL ret = _g_Microsoft_AspNetCore_Mvc_Cors._fp_Microsoft_AspNetCore_Mvc_Cors_CorsAuthorizationFilter_Task__OnAuthorizationAsync_0__1__AuthorizationFilterContext(__thrown, __self_h, context);
    return ret;
}

SG_HNDL_NULLABLE Microsoft_AspNetCore_Mvc_Cors_CorsAuthorizationFilter_String__get_PolicyName_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h) {
    if (!_g_Microsoft_AspNetCore_Mvc_Cors._fp_Microsoft_AspNetCore_Mvc_Cors_CorsAuthorizationFilter_String__get_PolicyName_0__0) {
        my_init();
    }
    SG_HNDL_NULLABLE ret = _g_Microsoft_AspNetCore_Mvc_Cors._fp_Microsoft_AspNetCore_Mvc_Cors_CorsAuthorizationFilter_String__get_PolicyName_0__0(__thrown, __self_h);
    return ret;
}

void Microsoft_AspNetCore_Mvc_Cors_CorsAuthorizationFilter_void__set_PolicyName_0__1__String(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h, SG_HNDL_NULLABLE value) {
    if (!_g_Microsoft_AspNetCore_Mvc_Cors._fp_Microsoft_AspNetCore_Mvc_Cors_CorsAuthorizationFilter_void__set_PolicyName_0__1__String) {
        my_init();
    }
    _g_Microsoft_AspNetCore_Mvc_Cors._fp_Microsoft_AspNetCore_Mvc_Cors_CorsAuthorizationFilter_void__set_PolicyName_0__1__String(__thrown, __self_h, value);
}

int32_t Microsoft_AspNetCore_Mvc_Cors_CorsAuthorizationFilter_i32__get_Order_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h) {
    if (!_g_Microsoft_AspNetCore_Mvc_Cors._fp_Microsoft_AspNetCore_Mvc_Cors_CorsAuthorizationFilter_i32__get_Order_0__0) {
        my_init();
    }
    int32_t ret = _g_Microsoft_AspNetCore_Mvc_Cors._fp_Microsoft_AspNetCore_Mvc_Cors_CorsAuthorizationFilter_i32__get_Order_0__0(__thrown, __self_h);
    return ret;
}

SG_HNDL_NONNULL Microsoft_AspNetCore_Mvc_Cors_CorsAuthorizationFilter_cast(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __h) {
    if (!_g_Microsoft_AspNetCore_Mvc_Cors._fp_Microsoft_AspNetCore_Mvc_Cors_CorsAuthorizationFilter_cast) {
        my_init();
    }
    SG_HNDL_NONNULL ret = _g_Microsoft_AspNetCore_Mvc_Cors._fp_Microsoft_AspNetCore_Mvc_Cors_CorsAuthorizationFilter_cast(__thrown, __h);
    return ret;
}

SG_HNDL_NONNULL Microsoft_Extensions_DependencyInjection_MvcCorsMvcCoreBuilderExtensions_IMvcCoreBuilder__AddCors_0__1__IMvcCoreBuilder(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL builder) {
    if (!_g_Microsoft_AspNetCore_Mvc_Cors._fp_Microsoft_Extensions_DependencyInjection_MvcCorsMvcCoreBuilderExtensions_IMvcCoreBuilder__AddCors_0__1__IMvcCoreBuilder) {
        my_init();
    }
    SG_HNDL_NONNULL ret = _g_Microsoft_AspNetCore_Mvc_Cors._fp_Microsoft_Extensions_DependencyInjection_MvcCorsMvcCoreBuilderExtensions_IMvcCoreBuilder__AddCors_0__1__IMvcCoreBuilder(__thrown, builder);
    return ret;
}

SG_HNDL_NONNULL Microsoft_Extensions_DependencyInjection_MvcCorsMvcCoreBuilderExtensions_IMvcCoreBuilder__AddCors_0__2__IMvcCoreBuilder_System_Action_Microsoft_AspNetCore_Cors_Infrastructure_CorsOptions_(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL builder, SG_HNDL_NONNULL setupAction) {
    if (!_g_Microsoft_AspNetCore_Mvc_Cors._fp_Microsoft_Extensions_DependencyInjection_MvcCorsMvcCoreBuilderExtensions_IMvcCoreBuilder__AddCors_0__2__IMvcCoreBuilder_System_Action_Microsoft_AspNetCore_Cors_Infrastructure_CorsOptions_) {
        my_init();
    }
    SG_HNDL_NONNULL ret = _g_Microsoft_AspNetCore_Mvc_Cors._fp_Microsoft_Extensions_DependencyInjection_MvcCorsMvcCoreBuilderExtensions_IMvcCoreBuilder__AddCors_0__2__IMvcCoreBuilder_System_Action_Microsoft_AspNetCore_Cors_Infrastructure_CorsOptions_(__thrown, builder, setupAction);
    return ret;
}

SG_HNDL_NONNULL Microsoft_Extensions_DependencyInjection_MvcCorsMvcCoreBuilderExtensions_IMvcCoreBuilder__ConfigureCors_0__2__IMvcCoreBuilder_System_Action_Microsoft_AspNetCore_Cors_Infrastructure_CorsOptions_(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL builder, SG_HNDL_NONNULL setupAction) {
    if (!_g_Microsoft_AspNetCore_Mvc_Cors._fp_Microsoft_Extensions_DependencyInjection_MvcCorsMvcCoreBuilderExtensions_IMvcCoreBuilder__ConfigureCors_0__2__IMvcCoreBuilder_System_Action_Microsoft_AspNetCore_Cors_Infrastructure_CorsOptions_) {
        my_init();
    }
    SG_HNDL_NONNULL ret = _g_Microsoft_AspNetCore_Mvc_Cors._fp_Microsoft_Extensions_DependencyInjection_MvcCorsMvcCoreBuilderExtensions_IMvcCoreBuilder__ConfigureCors_0__2__IMvcCoreBuilder_System_Action_Microsoft_AspNetCore_Cors_Infrastructure_CorsOptions_(__thrown, builder, setupAction);
    return ret;
}

