// this file is automatically generated with SourceGear Bridge

#include <stdint.h>

#include "Microsoft_Extensions_Configuration_Binder.h"

extern void (*_sg_resolve_jumptable)(const char*, int, void*);

struct {
    TYP (* _Nonnull  _fp_Microsoft_Extensions_Configuration_BinderOptions_get_type_handle)(void);
    SG_HNDL_NONNULL (* _Nonnull  _fp_Microsoft_Extensions_Configuration_BinderOptions_ctor_0__0)(SG_HNDL_NULLABLE * _Nonnull __thrown);
    int32_t (* _Nonnull  _fp_Microsoft_Extensions_Configuration_BinderOptions_bool__get_BindNonPublicProperties_0__0)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h);
    void (* _Nonnull  _fp_Microsoft_Extensions_Configuration_BinderOptions_void__set_BindNonPublicProperties_0__1__bool)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h, int32_t value);
    int32_t (* _Nonnull  _fp_Microsoft_Extensions_Configuration_BinderOptions_bool__get_ErrorOnUnknownConfiguration_0__0)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h);
    void (* _Nonnull  _fp_Microsoft_Extensions_Configuration_BinderOptions_void__set_ErrorOnUnknownConfiguration_0__1__bool)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h, int32_t value);
    SG_HNDL_NONNULL (* _Nonnull  _fp_Microsoft_Extensions_Configuration_BinderOptions_cast)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __h);
    void (* _Nonnull  _fp_Microsoft_Extensions_Configuration_ConfigurationBinder_void__Bind_0__2__IConfiguration_Object)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NULLABLE configuration, SG_HNDL_NULLABLE instance);
    void (* _Nonnull  _fp_Microsoft_Extensions_Configuration_ConfigurationBinder_void__Bind_0__3__IConfiguration_Object_System_Action_Microsoft_Extensions_Configuration_BinderOptions_)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NULLABLE configuration, SG_HNDL_NULLABLE instance, SG_HNDL_NULLABLE configureOptions);
    void (* _Nonnull  _fp_Microsoft_Extensions_Configuration_ConfigurationBinder_void__Bind_0__3__IConfiguration_String_Object)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NULLABLE configuration, SG_HNDL_NULLABLE key, SG_HNDL_NULLABLE instance);
    SG_HNDL_NULLABLE (* _Nonnull  _fp_Microsoft_Extensions_Configuration_ConfigurationBinder_Object__Get_0__2__IConfiguration_Type)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NULLABLE configuration, SG_HNDL_NULLABLE type);
    SG_HNDL_NULLABLE (* _Nonnull  _fp_Microsoft_Extensions_Configuration_ConfigurationBinder_Object__Get_0__3__IConfiguration_Type_System_Action_Microsoft_Extensions_Configuration_BinderOptions_)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NULLABLE configuration, SG_HNDL_NULLABLE type, SG_HNDL_NULLABLE configureOptions);
    SG_HNDL_NULLABLE (* _Nonnull  _fp_Microsoft_Extensions_Configuration_ConfigurationBinder_Object__GetValue_0__3__IConfiguration_Type_String)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NULLABLE configuration, SG_HNDL_NULLABLE type, SG_HNDL_NULLABLE key);
    SG_HNDL_NULLABLE (* _Nonnull  _fp_Microsoft_Extensions_Configuration_ConfigurationBinder_Object__GetValue_0__4__IConfiguration_Type_String_Object)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NULLABLE configuration, SG_HNDL_NULLABLE type, SG_HNDL_NULLABLE key, SG_HNDL_NULLABLE defaultValue);
    GVAL (* _Nonnull  _fp_Microsoft_Extensions_Configuration_ConfigurationBinder_UT__GetValue_1__2__IConfiguration_String)(TYP T, SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NULLABLE configuration, SG_HNDL_NULLABLE key);
    SG_HNDL_NONNULL (* _Nonnull  _fp_specialize_Microsoft_Extensions_Configuration_ConfigurationBinder_UT__GetValue_1__2__IConfiguration_String)(TYP T, SG_HNDL_NULLABLE * _Nonnull __thrown);
    GVAL (* _Nonnull  _fp_invoke_Microsoft_Extensions_Configuration_ConfigurationBinder_UT__GetValue_1__2__IConfiguration_String)(SG_HNDL_NONNULL ____hdel, SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NULLABLE configuration, SG_HNDL_NULLABLE key);
    GVAL (* _Nonnull  _fp_Microsoft_Extensions_Configuration_ConfigurationBinder_UT__GetValue_1__3__IConfiguration_String_UT)(TYP T, SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NULLABLE configuration, SG_HNDL_NULLABLE key, GVAL defaultValue);
    SG_HNDL_NONNULL (* _Nonnull  _fp_specialize_Microsoft_Extensions_Configuration_ConfigurationBinder_UT__GetValue_1__3__IConfiguration_String_UT)(TYP T, SG_HNDL_NULLABLE * _Nonnull __thrown);
    GVAL (* _Nonnull  _fp_invoke_Microsoft_Extensions_Configuration_ConfigurationBinder_UT__GetValue_1__3__IConfiguration_String_UT)(SG_HNDL_NONNULL ____hdel, SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NULLABLE configuration, SG_HNDL_NULLABLE key, GVAL defaultValue);
    GVAL (* _Nonnull  _fp_Microsoft_Extensions_Configuration_ConfigurationBinder_UT__Get_1__1__IConfiguration)(TYP T, SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NULLABLE configuration);
    SG_HNDL_NONNULL (* _Nonnull  _fp_specialize_Microsoft_Extensions_Configuration_ConfigurationBinder_UT__Get_1__1__IConfiguration)(TYP T, SG_HNDL_NULLABLE * _Nonnull __thrown);
    GVAL (* _Nonnull  _fp_invoke_Microsoft_Extensions_Configuration_ConfigurationBinder_UT__Get_1__1__IConfiguration)(SG_HNDL_NONNULL ____hdel, SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NULLABLE configuration);
    GVAL (* _Nonnull  _fp_Microsoft_Extensions_Configuration_ConfigurationBinder_UT__Get_1__2__IConfiguration_System_Action_Microsoft_Extensions_Configuration_BinderOptions_)(TYP T, SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NULLABLE configuration, SG_HNDL_NULLABLE configureOptions);
    SG_HNDL_NONNULL (* _Nonnull  _fp_specialize_Microsoft_Extensions_Configuration_ConfigurationBinder_UT__Get_1__2__IConfiguration_System_Action_Microsoft_Extensions_Configuration_BinderOptions_)(TYP T, SG_HNDL_NULLABLE * _Nonnull __thrown);
    GVAL (* _Nonnull  _fp_invoke_Microsoft_Extensions_Configuration_ConfigurationBinder_UT__Get_1__2__IConfiguration_System_Action_Microsoft_Extensions_Configuration_BinderOptions_)(SG_HNDL_NONNULL ____hdel, SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NULLABLE configuration, SG_HNDL_NULLABLE configureOptions);
} _g_Microsoft_Extensions_Configuration_Binder;

static void my_init() {
    _sg_resolve_jumptable("Microsoft_Extensions_Configuration_Binder", 41, &_g_Microsoft_Extensions_Configuration_Binder);
}

TYP Microsoft_Extensions_Configuration_BinderOptions_get_type_handle(void) {
    if (!_g_Microsoft_Extensions_Configuration_Binder._fp_Microsoft_Extensions_Configuration_BinderOptions_get_type_handle) {
        my_init();
    }
    TYP ret = _g_Microsoft_Extensions_Configuration_Binder._fp_Microsoft_Extensions_Configuration_BinderOptions_get_type_handle();
    return ret;
}

SG_HNDL_NONNULL Microsoft_Extensions_Configuration_BinderOptions_ctor_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown) {
    if (!_g_Microsoft_Extensions_Configuration_Binder._fp_Microsoft_Extensions_Configuration_BinderOptions_ctor_0__0) {
        my_init();
    }
    SG_HNDL_NONNULL ret = _g_Microsoft_Extensions_Configuration_Binder._fp_Microsoft_Extensions_Configuration_BinderOptions_ctor_0__0(__thrown);
    return ret;
}

int32_t Microsoft_Extensions_Configuration_BinderOptions_bool__get_BindNonPublicProperties_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h) {
    if (!_g_Microsoft_Extensions_Configuration_Binder._fp_Microsoft_Extensions_Configuration_BinderOptions_bool__get_BindNonPublicProperties_0__0) {
        my_init();
    }
    int32_t ret = _g_Microsoft_Extensions_Configuration_Binder._fp_Microsoft_Extensions_Configuration_BinderOptions_bool__get_BindNonPublicProperties_0__0(__thrown, __self_h);
    return ret;
}

void Microsoft_Extensions_Configuration_BinderOptions_void__set_BindNonPublicProperties_0__1__bool(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h, int32_t value) {
    if (!_g_Microsoft_Extensions_Configuration_Binder._fp_Microsoft_Extensions_Configuration_BinderOptions_void__set_BindNonPublicProperties_0__1__bool) {
        my_init();
    }
    _g_Microsoft_Extensions_Configuration_Binder._fp_Microsoft_Extensions_Configuration_BinderOptions_void__set_BindNonPublicProperties_0__1__bool(__thrown, __self_h, value);
}

int32_t Microsoft_Extensions_Configuration_BinderOptions_bool__get_ErrorOnUnknownConfiguration_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h) {
    if (!_g_Microsoft_Extensions_Configuration_Binder._fp_Microsoft_Extensions_Configuration_BinderOptions_bool__get_ErrorOnUnknownConfiguration_0__0) {
        my_init();
    }
    int32_t ret = _g_Microsoft_Extensions_Configuration_Binder._fp_Microsoft_Extensions_Configuration_BinderOptions_bool__get_ErrorOnUnknownConfiguration_0__0(__thrown, __self_h);
    return ret;
}

void Microsoft_Extensions_Configuration_BinderOptions_void__set_ErrorOnUnknownConfiguration_0__1__bool(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h, int32_t value) {
    if (!_g_Microsoft_Extensions_Configuration_Binder._fp_Microsoft_Extensions_Configuration_BinderOptions_void__set_ErrorOnUnknownConfiguration_0__1__bool) {
        my_init();
    }
    _g_Microsoft_Extensions_Configuration_Binder._fp_Microsoft_Extensions_Configuration_BinderOptions_void__set_ErrorOnUnknownConfiguration_0__1__bool(__thrown, __self_h, value);
}

SG_HNDL_NONNULL Microsoft_Extensions_Configuration_BinderOptions_cast(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __h) {
    if (!_g_Microsoft_Extensions_Configuration_Binder._fp_Microsoft_Extensions_Configuration_BinderOptions_cast) {
        my_init();
    }
    SG_HNDL_NONNULL ret = _g_Microsoft_Extensions_Configuration_Binder._fp_Microsoft_Extensions_Configuration_BinderOptions_cast(__thrown, __h);
    return ret;
}

void Microsoft_Extensions_Configuration_ConfigurationBinder_void__Bind_0__2__IConfiguration_Object(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NULLABLE configuration, SG_HNDL_NULLABLE instance) {
    if (!_g_Microsoft_Extensions_Configuration_Binder._fp_Microsoft_Extensions_Configuration_ConfigurationBinder_void__Bind_0__2__IConfiguration_Object) {
        my_init();
    }
    _g_Microsoft_Extensions_Configuration_Binder._fp_Microsoft_Extensions_Configuration_ConfigurationBinder_void__Bind_0__2__IConfiguration_Object(__thrown, configuration, instance);
}

void Microsoft_Extensions_Configuration_ConfigurationBinder_void__Bind_0__3__IConfiguration_Object_System_Action_Microsoft_Extensions_Configuration_BinderOptions_(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NULLABLE configuration, SG_HNDL_NULLABLE instance, SG_HNDL_NULLABLE configureOptions) {
    if (!_g_Microsoft_Extensions_Configuration_Binder._fp_Microsoft_Extensions_Configuration_ConfigurationBinder_void__Bind_0__3__IConfiguration_Object_System_Action_Microsoft_Extensions_Configuration_BinderOptions_) {
        my_init();
    }
    _g_Microsoft_Extensions_Configuration_Binder._fp_Microsoft_Extensions_Configuration_ConfigurationBinder_void__Bind_0__3__IConfiguration_Object_System_Action_Microsoft_Extensions_Configuration_BinderOptions_(__thrown, configuration, instance, configureOptions);
}

void Microsoft_Extensions_Configuration_ConfigurationBinder_void__Bind_0__3__IConfiguration_String_Object(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NULLABLE configuration, SG_HNDL_NULLABLE key, SG_HNDL_NULLABLE instance) {
    if (!_g_Microsoft_Extensions_Configuration_Binder._fp_Microsoft_Extensions_Configuration_ConfigurationBinder_void__Bind_0__3__IConfiguration_String_Object) {
        my_init();
    }
    _g_Microsoft_Extensions_Configuration_Binder._fp_Microsoft_Extensions_Configuration_ConfigurationBinder_void__Bind_0__3__IConfiguration_String_Object(__thrown, configuration, key, instance);
}

SG_HNDL_NULLABLE Microsoft_Extensions_Configuration_ConfigurationBinder_Object__Get_0__2__IConfiguration_Type(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NULLABLE configuration, SG_HNDL_NULLABLE type) {
    if (!_g_Microsoft_Extensions_Configuration_Binder._fp_Microsoft_Extensions_Configuration_ConfigurationBinder_Object__Get_0__2__IConfiguration_Type) {
        my_init();
    }
    SG_HNDL_NULLABLE ret = _g_Microsoft_Extensions_Configuration_Binder._fp_Microsoft_Extensions_Configuration_ConfigurationBinder_Object__Get_0__2__IConfiguration_Type(__thrown, configuration, type);
    return ret;
}

SG_HNDL_NULLABLE Microsoft_Extensions_Configuration_ConfigurationBinder_Object__Get_0__3__IConfiguration_Type_System_Action_Microsoft_Extensions_Configuration_BinderOptions_(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NULLABLE configuration, SG_HNDL_NULLABLE type, SG_HNDL_NULLABLE configureOptions) {
    if (!_g_Microsoft_Extensions_Configuration_Binder._fp_Microsoft_Extensions_Configuration_ConfigurationBinder_Object__Get_0__3__IConfiguration_Type_System_Action_Microsoft_Extensions_Configuration_BinderOptions_) {
        my_init();
    }
    SG_HNDL_NULLABLE ret = _g_Microsoft_Extensions_Configuration_Binder._fp_Microsoft_Extensions_Configuration_ConfigurationBinder_Object__Get_0__3__IConfiguration_Type_System_Action_Microsoft_Extensions_Configuration_BinderOptions_(__thrown, configuration, type, configureOptions);
    return ret;
}

SG_HNDL_NULLABLE Microsoft_Extensions_Configuration_ConfigurationBinder_Object__GetValue_0__3__IConfiguration_Type_String(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NULLABLE configuration, SG_HNDL_NULLABLE type, SG_HNDL_NULLABLE key) {
    if (!_g_Microsoft_Extensions_Configuration_Binder._fp_Microsoft_Extensions_Configuration_ConfigurationBinder_Object__GetValue_0__3__IConfiguration_Type_String) {
        my_init();
    }
    SG_HNDL_NULLABLE ret = _g_Microsoft_Extensions_Configuration_Binder._fp_Microsoft_Extensions_Configuration_ConfigurationBinder_Object__GetValue_0__3__IConfiguration_Type_String(__thrown, configuration, type, key);
    return ret;
}

SG_HNDL_NULLABLE Microsoft_Extensions_Configuration_ConfigurationBinder_Object__GetValue_0__4__IConfiguration_Type_String_Object(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NULLABLE configuration, SG_HNDL_NULLABLE type, SG_HNDL_NULLABLE key, SG_HNDL_NULLABLE defaultValue) {
    if (!_g_Microsoft_Extensions_Configuration_Binder._fp_Microsoft_Extensions_Configuration_ConfigurationBinder_Object__GetValue_0__4__IConfiguration_Type_String_Object) {
        my_init();
    }
    SG_HNDL_NULLABLE ret = _g_Microsoft_Extensions_Configuration_Binder._fp_Microsoft_Extensions_Configuration_ConfigurationBinder_Object__GetValue_0__4__IConfiguration_Type_String_Object(__thrown, configuration, type, key, defaultValue);
    return ret;
}

GVAL Microsoft_Extensions_Configuration_ConfigurationBinder_UT__GetValue_1__2__IConfiguration_String(TYP T, SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NULLABLE configuration, SG_HNDL_NULLABLE key) {
    if (!_g_Microsoft_Extensions_Configuration_Binder._fp_Microsoft_Extensions_Configuration_ConfigurationBinder_UT__GetValue_1__2__IConfiguration_String) {
        my_init();
    }
    GVAL ret = _g_Microsoft_Extensions_Configuration_Binder._fp_Microsoft_Extensions_Configuration_ConfigurationBinder_UT__GetValue_1__2__IConfiguration_String(T, __thrown, configuration, key);
    return ret;
}

SG_HNDL_NONNULL specialize_Microsoft_Extensions_Configuration_ConfigurationBinder_UT__GetValue_1__2__IConfiguration_String(TYP T, SG_HNDL_NULLABLE * _Nonnull __thrown) {
    if (!_g_Microsoft_Extensions_Configuration_Binder._fp_specialize_Microsoft_Extensions_Configuration_ConfigurationBinder_UT__GetValue_1__2__IConfiguration_String) {
        my_init();
    }
    SG_HNDL_NONNULL ret = _g_Microsoft_Extensions_Configuration_Binder._fp_specialize_Microsoft_Extensions_Configuration_ConfigurationBinder_UT__GetValue_1__2__IConfiguration_String(T, __thrown);
    return ret;
}

GVAL invoke_Microsoft_Extensions_Configuration_ConfigurationBinder_UT__GetValue_1__2__IConfiguration_String(SG_HNDL_NONNULL ____hdel, SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NULLABLE configuration, SG_HNDL_NULLABLE key) {
    if (!_g_Microsoft_Extensions_Configuration_Binder._fp_invoke_Microsoft_Extensions_Configuration_ConfigurationBinder_UT__GetValue_1__2__IConfiguration_String) {
        my_init();
    }
    GVAL ret = _g_Microsoft_Extensions_Configuration_Binder._fp_invoke_Microsoft_Extensions_Configuration_ConfigurationBinder_UT__GetValue_1__2__IConfiguration_String(____hdel, __thrown, configuration, key);
    return ret;
}

GVAL Microsoft_Extensions_Configuration_ConfigurationBinder_UT__GetValue_1__3__IConfiguration_String_UT(TYP T, SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NULLABLE configuration, SG_HNDL_NULLABLE key, GVAL defaultValue) {
    if (!_g_Microsoft_Extensions_Configuration_Binder._fp_Microsoft_Extensions_Configuration_ConfigurationBinder_UT__GetValue_1__3__IConfiguration_String_UT) {
        my_init();
    }
    GVAL ret = _g_Microsoft_Extensions_Configuration_Binder._fp_Microsoft_Extensions_Configuration_ConfigurationBinder_UT__GetValue_1__3__IConfiguration_String_UT(T, __thrown, configuration, key, defaultValue);
    return ret;
}

SG_HNDL_NONNULL specialize_Microsoft_Extensions_Configuration_ConfigurationBinder_UT__GetValue_1__3__IConfiguration_String_UT(TYP T, SG_HNDL_NULLABLE * _Nonnull __thrown) {
    if (!_g_Microsoft_Extensions_Configuration_Binder._fp_specialize_Microsoft_Extensions_Configuration_ConfigurationBinder_UT__GetValue_1__3__IConfiguration_String_UT) {
        my_init();
    }
    SG_HNDL_NONNULL ret = _g_Microsoft_Extensions_Configuration_Binder._fp_specialize_Microsoft_Extensions_Configuration_ConfigurationBinder_UT__GetValue_1__3__IConfiguration_String_UT(T, __thrown);
    return ret;
}

GVAL invoke_Microsoft_Extensions_Configuration_ConfigurationBinder_UT__GetValue_1__3__IConfiguration_String_UT(SG_HNDL_NONNULL ____hdel, SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NULLABLE configuration, SG_HNDL_NULLABLE key, GVAL defaultValue) {
    if (!_g_Microsoft_Extensions_Configuration_Binder._fp_invoke_Microsoft_Extensions_Configuration_ConfigurationBinder_UT__GetValue_1__3__IConfiguration_String_UT) {
        my_init();
    }
    GVAL ret = _g_Microsoft_Extensions_Configuration_Binder._fp_invoke_Microsoft_Extensions_Configuration_ConfigurationBinder_UT__GetValue_1__3__IConfiguration_String_UT(____hdel, __thrown, configuration, key, defaultValue);
    return ret;
}

GVAL Microsoft_Extensions_Configuration_ConfigurationBinder_UT__Get_1__1__IConfiguration(TYP T, SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NULLABLE configuration) {
    if (!_g_Microsoft_Extensions_Configuration_Binder._fp_Microsoft_Extensions_Configuration_ConfigurationBinder_UT__Get_1__1__IConfiguration) {
        my_init();
    }
    GVAL ret = _g_Microsoft_Extensions_Configuration_Binder._fp_Microsoft_Extensions_Configuration_ConfigurationBinder_UT__Get_1__1__IConfiguration(T, __thrown, configuration);
    return ret;
}

SG_HNDL_NONNULL specialize_Microsoft_Extensions_Configuration_ConfigurationBinder_UT__Get_1__1__IConfiguration(TYP T, SG_HNDL_NULLABLE * _Nonnull __thrown) {
    if (!_g_Microsoft_Extensions_Configuration_Binder._fp_specialize_Microsoft_Extensions_Configuration_ConfigurationBinder_UT__Get_1__1__IConfiguration) {
        my_init();
    }
    SG_HNDL_NONNULL ret = _g_Microsoft_Extensions_Configuration_Binder._fp_specialize_Microsoft_Extensions_Configuration_ConfigurationBinder_UT__Get_1__1__IConfiguration(T, __thrown);
    return ret;
}

GVAL invoke_Microsoft_Extensions_Configuration_ConfigurationBinder_UT__Get_1__1__IConfiguration(SG_HNDL_NONNULL ____hdel, SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NULLABLE configuration) {
    if (!_g_Microsoft_Extensions_Configuration_Binder._fp_invoke_Microsoft_Extensions_Configuration_ConfigurationBinder_UT__Get_1__1__IConfiguration) {
        my_init();
    }
    GVAL ret = _g_Microsoft_Extensions_Configuration_Binder._fp_invoke_Microsoft_Extensions_Configuration_ConfigurationBinder_UT__Get_1__1__IConfiguration(____hdel, __thrown, configuration);
    return ret;
}

GVAL Microsoft_Extensions_Configuration_ConfigurationBinder_UT__Get_1__2__IConfiguration_System_Action_Microsoft_Extensions_Configuration_BinderOptions_(TYP T, SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NULLABLE configuration, SG_HNDL_NULLABLE configureOptions) {
    if (!_g_Microsoft_Extensions_Configuration_Binder._fp_Microsoft_Extensions_Configuration_ConfigurationBinder_UT__Get_1__2__IConfiguration_System_Action_Microsoft_Extensions_Configuration_BinderOptions_) {
        my_init();
    }
    GVAL ret = _g_Microsoft_Extensions_Configuration_Binder._fp_Microsoft_Extensions_Configuration_ConfigurationBinder_UT__Get_1__2__IConfiguration_System_Action_Microsoft_Extensions_Configuration_BinderOptions_(T, __thrown, configuration, configureOptions);
    return ret;
}

SG_HNDL_NONNULL specialize_Microsoft_Extensions_Configuration_ConfigurationBinder_UT__Get_1__2__IConfiguration_System_Action_Microsoft_Extensions_Configuration_BinderOptions_(TYP T, SG_HNDL_NULLABLE * _Nonnull __thrown) {
    if (!_g_Microsoft_Extensions_Configuration_Binder._fp_specialize_Microsoft_Extensions_Configuration_ConfigurationBinder_UT__Get_1__2__IConfiguration_System_Action_Microsoft_Extensions_Configuration_BinderOptions_) {
        my_init();
    }
    SG_HNDL_NONNULL ret = _g_Microsoft_Extensions_Configuration_Binder._fp_specialize_Microsoft_Extensions_Configuration_ConfigurationBinder_UT__Get_1__2__IConfiguration_System_Action_Microsoft_Extensions_Configuration_BinderOptions_(T, __thrown);
    return ret;
}

GVAL invoke_Microsoft_Extensions_Configuration_ConfigurationBinder_UT__Get_1__2__IConfiguration_System_Action_Microsoft_Extensions_Configuration_BinderOptions_(SG_HNDL_NONNULL ____hdel, SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NULLABLE configuration, SG_HNDL_NULLABLE configureOptions) {
    if (!_g_Microsoft_Extensions_Configuration_Binder._fp_invoke_Microsoft_Extensions_Configuration_ConfigurationBinder_UT__Get_1__2__IConfiguration_System_Action_Microsoft_Extensions_Configuration_BinderOptions_) {
        my_init();
    }
    GVAL ret = _g_Microsoft_Extensions_Configuration_Binder._fp_invoke_Microsoft_Extensions_Configuration_ConfigurationBinder_UT__Get_1__2__IConfiguration_System_Action_Microsoft_Extensions_Configuration_BinderOptions_(____hdel, __thrown, configuration, configureOptions);
    return ret;
}

