// this file is automatically generated with SourceGear Bridge

#include <stdint.h>

#include "Microsoft_Extensions_FileProviders_Physical.h"

extern void (*_sg_resolve_jumptable)(const char*, int, void*);

struct {
    TYP (* _Nonnull  _fp_Microsoft_Extensions_FileProviders_PhysicalFileProvider_get_type_handle)(void);
    SG_HNDL_NONNULL (* _Nonnull  _fp_Microsoft_Extensions_FileProviders_PhysicalFileProvider_ctor_0__1__String)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NULLABLE root);
    SG_HNDL_NONNULL (* _Nonnull  _fp_Microsoft_Extensions_FileProviders_PhysicalFileProvider_ctor_0__2__String_ExclusionFilters)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NULLABLE root, int32_t filters);
    void (* _Nonnull  _fp_Microsoft_Extensions_FileProviders_PhysicalFileProvider_void__Dispose_0__0)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h);
    SG_HNDL_NULLABLE (* _Nonnull  _fp_Microsoft_Extensions_FileProviders_PhysicalFileProvider_IDirectoryContents__GetDirectoryContents_0__1__String)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h, SG_HNDL_NULLABLE subpath);
    SG_HNDL_NULLABLE (* _Nonnull  _fp_Microsoft_Extensions_FileProviders_PhysicalFileProvider_IFileInfo__GetFileInfo_0__1__String)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h, SG_HNDL_NULLABLE subpath);
    SG_HNDL_NULLABLE (* _Nonnull  _fp_Microsoft_Extensions_FileProviders_PhysicalFileProvider_IChangeToken__Watch_0__1__String)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h, SG_HNDL_NULLABLE filter);
    SG_HNDL_NULLABLE (* _Nonnull  _fp_Microsoft_Extensions_FileProviders_PhysicalFileProvider_String__get_Root_0__0)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h);
    int32_t (* _Nonnull  _fp_Microsoft_Extensions_FileProviders_PhysicalFileProvider_bool__get_UseActivePolling_0__0)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h);
    void (* _Nonnull  _fp_Microsoft_Extensions_FileProviders_PhysicalFileProvider_void__set_UseActivePolling_0__1__bool)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h, int32_t value);
    int32_t (* _Nonnull  _fp_Microsoft_Extensions_FileProviders_PhysicalFileProvider_bool__get_UsePollingFileWatcher_0__0)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h);
    void (* _Nonnull  _fp_Microsoft_Extensions_FileProviders_PhysicalFileProvider_void__set_UsePollingFileWatcher_0__1__bool)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h, int32_t value);
    SG_HNDL_NONNULL (* _Nonnull  _fp_Microsoft_Extensions_FileProviders_PhysicalFileProvider_cast)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __h);
    TYP (* _Nonnull  _fp_Microsoft_Extensions_FileProviders_Internal_PhysicalDirectoryContents_get_type_handle)(void);
    SG_HNDL_NONNULL (* _Nonnull  _fp_Microsoft_Extensions_FileProviders_Internal_PhysicalDirectoryContents_ctor_0__1__String)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NULLABLE directory);
    SG_HNDL_NONNULL (* _Nonnull  _fp_Microsoft_Extensions_FileProviders_Internal_PhysicalDirectoryContents_ctor_0__2__String_ExclusionFilters)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NULLABLE directory, int32_t filters);
    SG_HNDL_NULLABLE (* _Nonnull  _fp_Microsoft_Extensions_FileProviders_Internal_PhysicalDirectoryContents_System_Collections_Generic_IEnumerator_Microsoft_Extensions_FileProviders_IFileInfo___GetEnumerator_0__0)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h);
    int32_t (* _Nonnull  _fp_Microsoft_Extensions_FileProviders_Internal_PhysicalDirectoryContents_bool__get_Exists_0__0)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h);
    SG_HNDL_NONNULL (* _Nonnull  _fp_Microsoft_Extensions_FileProviders_Internal_PhysicalDirectoryContents_cast)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __h);
    TYP (* _Nonnull  _fp_Microsoft_Extensions_FileProviders_Physical_ExclusionFilters_get_type_handle)(void);
    int32_t (* _Nonnull  _fp_Microsoft_Extensions_FileProviders_Physical_ExclusionFilters_get_None)(void);
    int32_t (* _Nonnull  _fp_Microsoft_Extensions_FileProviders_Physical_ExclusionFilters_get_DotPrefixed)(void);
    int32_t (* _Nonnull  _fp_Microsoft_Extensions_FileProviders_Physical_ExclusionFilters_get_Hidden)(void);
    int32_t (* _Nonnull  _fp_Microsoft_Extensions_FileProviders_Physical_ExclusionFilters_get_System)(void);
    int32_t (* _Nonnull  _fp_Microsoft_Extensions_FileProviders_Physical_ExclusionFilters_get_Sensitive)(void);
    TYP (* _Nonnull  _fp_Microsoft_Extensions_FileProviders_Physical_PhysicalDirectoryInfo_get_type_handle)(void);
    SG_HNDL_NONNULL (* _Nonnull  _fp_Microsoft_Extensions_FileProviders_Physical_PhysicalDirectoryInfo_ctor_0__1__DirectoryInfo)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NULLABLE info);
    SG_HNDL_NULLABLE (* _Nonnull  _fp_Microsoft_Extensions_FileProviders_Physical_PhysicalDirectoryInfo_Stream__CreateReadStream_0__0)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h);
    int32_t (* _Nonnull  _fp_Microsoft_Extensions_FileProviders_Physical_PhysicalDirectoryInfo_bool__get_Exists_0__0)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h);
    int32_t (* _Nonnull  _fp_Microsoft_Extensions_FileProviders_Physical_PhysicalDirectoryInfo_bool__get_IsDirectory_0__0)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h);
    SG_HNDL_NONNULL (* _Nonnull  _fp_Microsoft_Extensions_FileProviders_Physical_PhysicalDirectoryInfo_DateTimeOffset__get_LastModified_0__0)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h);
    int64_t (* _Nonnull  _fp_Microsoft_Extensions_FileProviders_Physical_PhysicalDirectoryInfo_i64__get_Length_0__0)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h);
    SG_HNDL_NULLABLE (* _Nonnull  _fp_Microsoft_Extensions_FileProviders_Physical_PhysicalDirectoryInfo_String__get_Name_0__0)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h);
    SG_HNDL_NULLABLE (* _Nonnull  _fp_Microsoft_Extensions_FileProviders_Physical_PhysicalDirectoryInfo_String__get_PhysicalPath_0__0)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h);
    SG_HNDL_NONNULL (* _Nonnull  _fp_Microsoft_Extensions_FileProviders_Physical_PhysicalDirectoryInfo_cast)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __h);
    TYP (* _Nonnull  _fp_Microsoft_Extensions_FileProviders_Physical_PhysicalFileInfo_get_type_handle)(void);
    SG_HNDL_NONNULL (* _Nonnull  _fp_Microsoft_Extensions_FileProviders_Physical_PhysicalFileInfo_ctor_0__1__FileInfo)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NULLABLE info);
    SG_HNDL_NULLABLE (* _Nonnull  _fp_Microsoft_Extensions_FileProviders_Physical_PhysicalFileInfo_Stream__CreateReadStream_0__0)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h);
    int32_t (* _Nonnull  _fp_Microsoft_Extensions_FileProviders_Physical_PhysicalFileInfo_bool__get_Exists_0__0)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h);
    int32_t (* _Nonnull  _fp_Microsoft_Extensions_FileProviders_Physical_PhysicalFileInfo_bool__get_IsDirectory_0__0)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h);
    SG_HNDL_NONNULL (* _Nonnull  _fp_Microsoft_Extensions_FileProviders_Physical_PhysicalFileInfo_DateTimeOffset__get_LastModified_0__0)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h);
    int64_t (* _Nonnull  _fp_Microsoft_Extensions_FileProviders_Physical_PhysicalFileInfo_i64__get_Length_0__0)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h);
    SG_HNDL_NULLABLE (* _Nonnull  _fp_Microsoft_Extensions_FileProviders_Physical_PhysicalFileInfo_String__get_Name_0__0)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h);
    SG_HNDL_NULLABLE (* _Nonnull  _fp_Microsoft_Extensions_FileProviders_Physical_PhysicalFileInfo_String__get_PhysicalPath_0__0)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h);
    SG_HNDL_NONNULL (* _Nonnull  _fp_Microsoft_Extensions_FileProviders_Physical_PhysicalFileInfo_cast)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __h);
    TYP (* _Nonnull  _fp_Microsoft_Extensions_FileProviders_Physical_PhysicalFilesWatcher_get_type_handle)(void);
    SG_HNDL_NONNULL (* _Nonnull  _fp_Microsoft_Extensions_FileProviders_Physical_PhysicalFilesWatcher_ctor_0__3__String_FileSystemWatcher_bool)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NULLABLE root, SG_HNDL_NULLABLE fileSystemWatcher, int32_t pollForChanges);
    SG_HNDL_NONNULL (* _Nonnull  _fp_Microsoft_Extensions_FileProviders_Physical_PhysicalFilesWatcher_ctor_0__4__String_FileSystemWatcher_bool_ExclusionFilters)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NULLABLE root, SG_HNDL_NULLABLE fileSystemWatcher, int32_t pollForChanges, int32_t filters);
    SG_HNDL_NULLABLE (* _Nonnull  _fp_Microsoft_Extensions_FileProviders_Physical_PhysicalFilesWatcher_IChangeToken__CreateFileChangeToken_0__1__String)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h, SG_HNDL_NULLABLE filter);
    void (* _Nonnull  _fp_Microsoft_Extensions_FileProviders_Physical_PhysicalFilesWatcher_void__Dispose_0__0)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h);
    SG_HNDL_NONNULL (* _Nonnull  _fp_Microsoft_Extensions_FileProviders_Physical_PhysicalFilesWatcher_cast)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __h);
    TYP (* _Nonnull  _fp_Microsoft_Extensions_FileProviders_Physical_PollingFileChangeToken_get_type_handle)(void);
    SG_HNDL_NONNULL (* _Nonnull  _fp_Microsoft_Extensions_FileProviders_Physical_PollingFileChangeToken_ctor_0__1__FileInfo)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NULLABLE fileInfo);
    SG_HNDL_NULLABLE (* _Nonnull  _fp_Microsoft_Extensions_FileProviders_Physical_PollingFileChangeToken_IDisposable__RegisterChangeCallback_0__2__System_Action_object__Object)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h, SG_HNDL_NULLABLE callback, SG_HNDL_NULLABLE state);
    int32_t (* _Nonnull  _fp_Microsoft_Extensions_FileProviders_Physical_PollingFileChangeToken_bool__get_ActiveChangeCallbacks_0__0)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h);
    int32_t (* _Nonnull  _fp_Microsoft_Extensions_FileProviders_Physical_PollingFileChangeToken_bool__get_HasChanged_0__0)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h);
    SG_HNDL_NONNULL (* _Nonnull  _fp_Microsoft_Extensions_FileProviders_Physical_PollingFileChangeToken_cast)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __h);
    TYP (* _Nonnull  _fp_Microsoft_Extensions_FileProviders_Physical_PollingWildCardChangeToken_get_type_handle)(void);
    SG_HNDL_NONNULL (* _Nonnull  _fp_Microsoft_Extensions_FileProviders_Physical_PollingWildCardChangeToken_ctor_0__2__String_String)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NULLABLE root, SG_HNDL_NULLABLE pattern);
    int32_t (* _Nonnull  _fp_Microsoft_Extensions_FileProviders_Physical_PollingWildCardChangeToken_bool__get_ActiveChangeCallbacks_0__0)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h);
    int32_t (* _Nonnull  _fp_Microsoft_Extensions_FileProviders_Physical_PollingWildCardChangeToken_bool__get_HasChanged_0__0)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h);
    SG_HNDL_NONNULL (* _Nonnull  _fp_Microsoft_Extensions_FileProviders_Physical_PollingWildCardChangeToken_cast)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __h);
} _g_Microsoft_Extensions_FileProviders_Physical;

static void my_init() {
    _sg_resolve_jumptable("Microsoft_Extensions_FileProviders_Physical", 43, &_g_Microsoft_Extensions_FileProviders_Physical);
}

TYP Microsoft_Extensions_FileProviders_PhysicalFileProvider_get_type_handle(void) {
    if (!_g_Microsoft_Extensions_FileProviders_Physical._fp_Microsoft_Extensions_FileProviders_PhysicalFileProvider_get_type_handle) {
        my_init();
    }
    TYP ret = _g_Microsoft_Extensions_FileProviders_Physical._fp_Microsoft_Extensions_FileProviders_PhysicalFileProvider_get_type_handle();
    return ret;
}

SG_HNDL_NONNULL Microsoft_Extensions_FileProviders_PhysicalFileProvider_ctor_0__1__String(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NULLABLE root) {
    if (!_g_Microsoft_Extensions_FileProviders_Physical._fp_Microsoft_Extensions_FileProviders_PhysicalFileProvider_ctor_0__1__String) {
        my_init();
    }
    SG_HNDL_NONNULL ret = _g_Microsoft_Extensions_FileProviders_Physical._fp_Microsoft_Extensions_FileProviders_PhysicalFileProvider_ctor_0__1__String(__thrown, root);
    return ret;
}

SG_HNDL_NONNULL Microsoft_Extensions_FileProviders_PhysicalFileProvider_ctor_0__2__String_ExclusionFilters(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NULLABLE root, int32_t filters) {
    if (!_g_Microsoft_Extensions_FileProviders_Physical._fp_Microsoft_Extensions_FileProviders_PhysicalFileProvider_ctor_0__2__String_ExclusionFilters) {
        my_init();
    }
    SG_HNDL_NONNULL ret = _g_Microsoft_Extensions_FileProviders_Physical._fp_Microsoft_Extensions_FileProviders_PhysicalFileProvider_ctor_0__2__String_ExclusionFilters(__thrown, root, filters);
    return ret;
}

void Microsoft_Extensions_FileProviders_PhysicalFileProvider_void__Dispose_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h) {
    if (!_g_Microsoft_Extensions_FileProviders_Physical._fp_Microsoft_Extensions_FileProviders_PhysicalFileProvider_void__Dispose_0__0) {
        my_init();
    }
    _g_Microsoft_Extensions_FileProviders_Physical._fp_Microsoft_Extensions_FileProviders_PhysicalFileProvider_void__Dispose_0__0(__thrown, __self_h);
}

SG_HNDL_NULLABLE Microsoft_Extensions_FileProviders_PhysicalFileProvider_IDirectoryContents__GetDirectoryContents_0__1__String(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h, SG_HNDL_NULLABLE subpath) {
    if (!_g_Microsoft_Extensions_FileProviders_Physical._fp_Microsoft_Extensions_FileProviders_PhysicalFileProvider_IDirectoryContents__GetDirectoryContents_0__1__String) {
        my_init();
    }
    SG_HNDL_NULLABLE ret = _g_Microsoft_Extensions_FileProviders_Physical._fp_Microsoft_Extensions_FileProviders_PhysicalFileProvider_IDirectoryContents__GetDirectoryContents_0__1__String(__thrown, __self_h, subpath);
    return ret;
}

SG_HNDL_NULLABLE Microsoft_Extensions_FileProviders_PhysicalFileProvider_IFileInfo__GetFileInfo_0__1__String(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h, SG_HNDL_NULLABLE subpath) {
    if (!_g_Microsoft_Extensions_FileProviders_Physical._fp_Microsoft_Extensions_FileProviders_PhysicalFileProvider_IFileInfo__GetFileInfo_0__1__String) {
        my_init();
    }
    SG_HNDL_NULLABLE ret = _g_Microsoft_Extensions_FileProviders_Physical._fp_Microsoft_Extensions_FileProviders_PhysicalFileProvider_IFileInfo__GetFileInfo_0__1__String(__thrown, __self_h, subpath);
    return ret;
}

SG_HNDL_NULLABLE Microsoft_Extensions_FileProviders_PhysicalFileProvider_IChangeToken__Watch_0__1__String(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h, SG_HNDL_NULLABLE filter) {
    if (!_g_Microsoft_Extensions_FileProviders_Physical._fp_Microsoft_Extensions_FileProviders_PhysicalFileProvider_IChangeToken__Watch_0__1__String) {
        my_init();
    }
    SG_HNDL_NULLABLE ret = _g_Microsoft_Extensions_FileProviders_Physical._fp_Microsoft_Extensions_FileProviders_PhysicalFileProvider_IChangeToken__Watch_0__1__String(__thrown, __self_h, filter);
    return ret;
}

SG_HNDL_NULLABLE Microsoft_Extensions_FileProviders_PhysicalFileProvider_String__get_Root_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h) {
    if (!_g_Microsoft_Extensions_FileProviders_Physical._fp_Microsoft_Extensions_FileProviders_PhysicalFileProvider_String__get_Root_0__0) {
        my_init();
    }
    SG_HNDL_NULLABLE ret = _g_Microsoft_Extensions_FileProviders_Physical._fp_Microsoft_Extensions_FileProviders_PhysicalFileProvider_String__get_Root_0__0(__thrown, __self_h);
    return ret;
}

int32_t Microsoft_Extensions_FileProviders_PhysicalFileProvider_bool__get_UseActivePolling_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h) {
    if (!_g_Microsoft_Extensions_FileProviders_Physical._fp_Microsoft_Extensions_FileProviders_PhysicalFileProvider_bool__get_UseActivePolling_0__0) {
        my_init();
    }
    int32_t ret = _g_Microsoft_Extensions_FileProviders_Physical._fp_Microsoft_Extensions_FileProviders_PhysicalFileProvider_bool__get_UseActivePolling_0__0(__thrown, __self_h);
    return ret;
}

void Microsoft_Extensions_FileProviders_PhysicalFileProvider_void__set_UseActivePolling_0__1__bool(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h, int32_t value) {
    if (!_g_Microsoft_Extensions_FileProviders_Physical._fp_Microsoft_Extensions_FileProviders_PhysicalFileProvider_void__set_UseActivePolling_0__1__bool) {
        my_init();
    }
    _g_Microsoft_Extensions_FileProviders_Physical._fp_Microsoft_Extensions_FileProviders_PhysicalFileProvider_void__set_UseActivePolling_0__1__bool(__thrown, __self_h, value);
}

int32_t Microsoft_Extensions_FileProviders_PhysicalFileProvider_bool__get_UsePollingFileWatcher_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h) {
    if (!_g_Microsoft_Extensions_FileProviders_Physical._fp_Microsoft_Extensions_FileProviders_PhysicalFileProvider_bool__get_UsePollingFileWatcher_0__0) {
        my_init();
    }
    int32_t ret = _g_Microsoft_Extensions_FileProviders_Physical._fp_Microsoft_Extensions_FileProviders_PhysicalFileProvider_bool__get_UsePollingFileWatcher_0__0(__thrown, __self_h);
    return ret;
}

void Microsoft_Extensions_FileProviders_PhysicalFileProvider_void__set_UsePollingFileWatcher_0__1__bool(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h, int32_t value) {
    if (!_g_Microsoft_Extensions_FileProviders_Physical._fp_Microsoft_Extensions_FileProviders_PhysicalFileProvider_void__set_UsePollingFileWatcher_0__1__bool) {
        my_init();
    }
    _g_Microsoft_Extensions_FileProviders_Physical._fp_Microsoft_Extensions_FileProviders_PhysicalFileProvider_void__set_UsePollingFileWatcher_0__1__bool(__thrown, __self_h, value);
}

SG_HNDL_NONNULL Microsoft_Extensions_FileProviders_PhysicalFileProvider_cast(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __h) {
    if (!_g_Microsoft_Extensions_FileProviders_Physical._fp_Microsoft_Extensions_FileProviders_PhysicalFileProvider_cast) {
        my_init();
    }
    SG_HNDL_NONNULL ret = _g_Microsoft_Extensions_FileProviders_Physical._fp_Microsoft_Extensions_FileProviders_PhysicalFileProvider_cast(__thrown, __h);
    return ret;
}

TYP Microsoft_Extensions_FileProviders_Internal_PhysicalDirectoryContents_get_type_handle(void) {
    if (!_g_Microsoft_Extensions_FileProviders_Physical._fp_Microsoft_Extensions_FileProviders_Internal_PhysicalDirectoryContents_get_type_handle) {
        my_init();
    }
    TYP ret = _g_Microsoft_Extensions_FileProviders_Physical._fp_Microsoft_Extensions_FileProviders_Internal_PhysicalDirectoryContents_get_type_handle();
    return ret;
}

SG_HNDL_NONNULL Microsoft_Extensions_FileProviders_Internal_PhysicalDirectoryContents_ctor_0__1__String(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NULLABLE directory) {
    if (!_g_Microsoft_Extensions_FileProviders_Physical._fp_Microsoft_Extensions_FileProviders_Internal_PhysicalDirectoryContents_ctor_0__1__String) {
        my_init();
    }
    SG_HNDL_NONNULL ret = _g_Microsoft_Extensions_FileProviders_Physical._fp_Microsoft_Extensions_FileProviders_Internal_PhysicalDirectoryContents_ctor_0__1__String(__thrown, directory);
    return ret;
}

SG_HNDL_NONNULL Microsoft_Extensions_FileProviders_Internal_PhysicalDirectoryContents_ctor_0__2__String_ExclusionFilters(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NULLABLE directory, int32_t filters) {
    if (!_g_Microsoft_Extensions_FileProviders_Physical._fp_Microsoft_Extensions_FileProviders_Internal_PhysicalDirectoryContents_ctor_0__2__String_ExclusionFilters) {
        my_init();
    }
    SG_HNDL_NONNULL ret = _g_Microsoft_Extensions_FileProviders_Physical._fp_Microsoft_Extensions_FileProviders_Internal_PhysicalDirectoryContents_ctor_0__2__String_ExclusionFilters(__thrown, directory, filters);
    return ret;
}

SG_HNDL_NULLABLE Microsoft_Extensions_FileProviders_Internal_PhysicalDirectoryContents_System_Collections_Generic_IEnumerator_Microsoft_Extensions_FileProviders_IFileInfo___GetEnumerator_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h) {
    if (!_g_Microsoft_Extensions_FileProviders_Physical._fp_Microsoft_Extensions_FileProviders_Internal_PhysicalDirectoryContents_System_Collections_Generic_IEnumerator_Microsoft_Extensions_FileProviders_IFileInfo___GetEnumerator_0__0) {
        my_init();
    }
    SG_HNDL_NULLABLE ret = _g_Microsoft_Extensions_FileProviders_Physical._fp_Microsoft_Extensions_FileProviders_Internal_PhysicalDirectoryContents_System_Collections_Generic_IEnumerator_Microsoft_Extensions_FileProviders_IFileInfo___GetEnumerator_0__0(__thrown, __self_h);
    return ret;
}

int32_t Microsoft_Extensions_FileProviders_Internal_PhysicalDirectoryContents_bool__get_Exists_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h) {
    if (!_g_Microsoft_Extensions_FileProviders_Physical._fp_Microsoft_Extensions_FileProviders_Internal_PhysicalDirectoryContents_bool__get_Exists_0__0) {
        my_init();
    }
    int32_t ret = _g_Microsoft_Extensions_FileProviders_Physical._fp_Microsoft_Extensions_FileProviders_Internal_PhysicalDirectoryContents_bool__get_Exists_0__0(__thrown, __self_h);
    return ret;
}

SG_HNDL_NONNULL Microsoft_Extensions_FileProviders_Internal_PhysicalDirectoryContents_cast(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __h) {
    if (!_g_Microsoft_Extensions_FileProviders_Physical._fp_Microsoft_Extensions_FileProviders_Internal_PhysicalDirectoryContents_cast) {
        my_init();
    }
    SG_HNDL_NONNULL ret = _g_Microsoft_Extensions_FileProviders_Physical._fp_Microsoft_Extensions_FileProviders_Internal_PhysicalDirectoryContents_cast(__thrown, __h);
    return ret;
}

TYP Microsoft_Extensions_FileProviders_Physical_ExclusionFilters_get_type_handle(void) {
    if (!_g_Microsoft_Extensions_FileProviders_Physical._fp_Microsoft_Extensions_FileProviders_Physical_ExclusionFilters_get_type_handle) {
        my_init();
    }
    TYP ret = _g_Microsoft_Extensions_FileProviders_Physical._fp_Microsoft_Extensions_FileProviders_Physical_ExclusionFilters_get_type_handle();
    return ret;
}

int32_t Microsoft_Extensions_FileProviders_Physical_ExclusionFilters_get_None(void) {
    if (!_g_Microsoft_Extensions_FileProviders_Physical._fp_Microsoft_Extensions_FileProviders_Physical_ExclusionFilters_get_None) {
        my_init();
    }
    int32_t ret = _g_Microsoft_Extensions_FileProviders_Physical._fp_Microsoft_Extensions_FileProviders_Physical_ExclusionFilters_get_None();
    return ret;
}

int32_t Microsoft_Extensions_FileProviders_Physical_ExclusionFilters_get_DotPrefixed(void) {
    if (!_g_Microsoft_Extensions_FileProviders_Physical._fp_Microsoft_Extensions_FileProviders_Physical_ExclusionFilters_get_DotPrefixed) {
        my_init();
    }
    int32_t ret = _g_Microsoft_Extensions_FileProviders_Physical._fp_Microsoft_Extensions_FileProviders_Physical_ExclusionFilters_get_DotPrefixed();
    return ret;
}

int32_t Microsoft_Extensions_FileProviders_Physical_ExclusionFilters_get_Hidden(void) {
    if (!_g_Microsoft_Extensions_FileProviders_Physical._fp_Microsoft_Extensions_FileProviders_Physical_ExclusionFilters_get_Hidden) {
        my_init();
    }
    int32_t ret = _g_Microsoft_Extensions_FileProviders_Physical._fp_Microsoft_Extensions_FileProviders_Physical_ExclusionFilters_get_Hidden();
    return ret;
}

int32_t Microsoft_Extensions_FileProviders_Physical_ExclusionFilters_get_System(void) {
    if (!_g_Microsoft_Extensions_FileProviders_Physical._fp_Microsoft_Extensions_FileProviders_Physical_ExclusionFilters_get_System) {
        my_init();
    }
    int32_t ret = _g_Microsoft_Extensions_FileProviders_Physical._fp_Microsoft_Extensions_FileProviders_Physical_ExclusionFilters_get_System();
    return ret;
}

int32_t Microsoft_Extensions_FileProviders_Physical_ExclusionFilters_get_Sensitive(void) {
    if (!_g_Microsoft_Extensions_FileProviders_Physical._fp_Microsoft_Extensions_FileProviders_Physical_ExclusionFilters_get_Sensitive) {
        my_init();
    }
    int32_t ret = _g_Microsoft_Extensions_FileProviders_Physical._fp_Microsoft_Extensions_FileProviders_Physical_ExclusionFilters_get_Sensitive();
    return ret;
}

TYP Microsoft_Extensions_FileProviders_Physical_PhysicalDirectoryInfo_get_type_handle(void) {
    if (!_g_Microsoft_Extensions_FileProviders_Physical._fp_Microsoft_Extensions_FileProviders_Physical_PhysicalDirectoryInfo_get_type_handle) {
        my_init();
    }
    TYP ret = _g_Microsoft_Extensions_FileProviders_Physical._fp_Microsoft_Extensions_FileProviders_Physical_PhysicalDirectoryInfo_get_type_handle();
    return ret;
}

SG_HNDL_NONNULL Microsoft_Extensions_FileProviders_Physical_PhysicalDirectoryInfo_ctor_0__1__DirectoryInfo(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NULLABLE info) {
    if (!_g_Microsoft_Extensions_FileProviders_Physical._fp_Microsoft_Extensions_FileProviders_Physical_PhysicalDirectoryInfo_ctor_0__1__DirectoryInfo) {
        my_init();
    }
    SG_HNDL_NONNULL ret = _g_Microsoft_Extensions_FileProviders_Physical._fp_Microsoft_Extensions_FileProviders_Physical_PhysicalDirectoryInfo_ctor_0__1__DirectoryInfo(__thrown, info);
    return ret;
}

SG_HNDL_NULLABLE Microsoft_Extensions_FileProviders_Physical_PhysicalDirectoryInfo_Stream__CreateReadStream_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h) {
    if (!_g_Microsoft_Extensions_FileProviders_Physical._fp_Microsoft_Extensions_FileProviders_Physical_PhysicalDirectoryInfo_Stream__CreateReadStream_0__0) {
        my_init();
    }
    SG_HNDL_NULLABLE ret = _g_Microsoft_Extensions_FileProviders_Physical._fp_Microsoft_Extensions_FileProviders_Physical_PhysicalDirectoryInfo_Stream__CreateReadStream_0__0(__thrown, __self_h);
    return ret;
}

int32_t Microsoft_Extensions_FileProviders_Physical_PhysicalDirectoryInfo_bool__get_Exists_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h) {
    if (!_g_Microsoft_Extensions_FileProviders_Physical._fp_Microsoft_Extensions_FileProviders_Physical_PhysicalDirectoryInfo_bool__get_Exists_0__0) {
        my_init();
    }
    int32_t ret = _g_Microsoft_Extensions_FileProviders_Physical._fp_Microsoft_Extensions_FileProviders_Physical_PhysicalDirectoryInfo_bool__get_Exists_0__0(__thrown, __self_h);
    return ret;
}

int32_t Microsoft_Extensions_FileProviders_Physical_PhysicalDirectoryInfo_bool__get_IsDirectory_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h) {
    if (!_g_Microsoft_Extensions_FileProviders_Physical._fp_Microsoft_Extensions_FileProviders_Physical_PhysicalDirectoryInfo_bool__get_IsDirectory_0__0) {
        my_init();
    }
    int32_t ret = _g_Microsoft_Extensions_FileProviders_Physical._fp_Microsoft_Extensions_FileProviders_Physical_PhysicalDirectoryInfo_bool__get_IsDirectory_0__0(__thrown, __self_h);
    return ret;
}

SG_HNDL_NONNULL Microsoft_Extensions_FileProviders_Physical_PhysicalDirectoryInfo_DateTimeOffset__get_LastModified_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h) {
    if (!_g_Microsoft_Extensions_FileProviders_Physical._fp_Microsoft_Extensions_FileProviders_Physical_PhysicalDirectoryInfo_DateTimeOffset__get_LastModified_0__0) {
        my_init();
    }
    SG_HNDL_NONNULL ret = _g_Microsoft_Extensions_FileProviders_Physical._fp_Microsoft_Extensions_FileProviders_Physical_PhysicalDirectoryInfo_DateTimeOffset__get_LastModified_0__0(__thrown, __self_h);
    return ret;
}

int64_t Microsoft_Extensions_FileProviders_Physical_PhysicalDirectoryInfo_i64__get_Length_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h) {
    if (!_g_Microsoft_Extensions_FileProviders_Physical._fp_Microsoft_Extensions_FileProviders_Physical_PhysicalDirectoryInfo_i64__get_Length_0__0) {
        my_init();
    }
    int64_t ret = _g_Microsoft_Extensions_FileProviders_Physical._fp_Microsoft_Extensions_FileProviders_Physical_PhysicalDirectoryInfo_i64__get_Length_0__0(__thrown, __self_h);
    return ret;
}

SG_HNDL_NULLABLE Microsoft_Extensions_FileProviders_Physical_PhysicalDirectoryInfo_String__get_Name_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h) {
    if (!_g_Microsoft_Extensions_FileProviders_Physical._fp_Microsoft_Extensions_FileProviders_Physical_PhysicalDirectoryInfo_String__get_Name_0__0) {
        my_init();
    }
    SG_HNDL_NULLABLE ret = _g_Microsoft_Extensions_FileProviders_Physical._fp_Microsoft_Extensions_FileProviders_Physical_PhysicalDirectoryInfo_String__get_Name_0__0(__thrown, __self_h);
    return ret;
}

SG_HNDL_NULLABLE Microsoft_Extensions_FileProviders_Physical_PhysicalDirectoryInfo_String__get_PhysicalPath_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h) {
    if (!_g_Microsoft_Extensions_FileProviders_Physical._fp_Microsoft_Extensions_FileProviders_Physical_PhysicalDirectoryInfo_String__get_PhysicalPath_0__0) {
        my_init();
    }
    SG_HNDL_NULLABLE ret = _g_Microsoft_Extensions_FileProviders_Physical._fp_Microsoft_Extensions_FileProviders_Physical_PhysicalDirectoryInfo_String__get_PhysicalPath_0__0(__thrown, __self_h);
    return ret;
}

SG_HNDL_NONNULL Microsoft_Extensions_FileProviders_Physical_PhysicalDirectoryInfo_cast(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __h) {
    if (!_g_Microsoft_Extensions_FileProviders_Physical._fp_Microsoft_Extensions_FileProviders_Physical_PhysicalDirectoryInfo_cast) {
        my_init();
    }
    SG_HNDL_NONNULL ret = _g_Microsoft_Extensions_FileProviders_Physical._fp_Microsoft_Extensions_FileProviders_Physical_PhysicalDirectoryInfo_cast(__thrown, __h);
    return ret;
}

TYP Microsoft_Extensions_FileProviders_Physical_PhysicalFileInfo_get_type_handle(void) {
    if (!_g_Microsoft_Extensions_FileProviders_Physical._fp_Microsoft_Extensions_FileProviders_Physical_PhysicalFileInfo_get_type_handle) {
        my_init();
    }
    TYP ret = _g_Microsoft_Extensions_FileProviders_Physical._fp_Microsoft_Extensions_FileProviders_Physical_PhysicalFileInfo_get_type_handle();
    return ret;
}

SG_HNDL_NONNULL Microsoft_Extensions_FileProviders_Physical_PhysicalFileInfo_ctor_0__1__FileInfo(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NULLABLE info) {
    if (!_g_Microsoft_Extensions_FileProviders_Physical._fp_Microsoft_Extensions_FileProviders_Physical_PhysicalFileInfo_ctor_0__1__FileInfo) {
        my_init();
    }
    SG_HNDL_NONNULL ret = _g_Microsoft_Extensions_FileProviders_Physical._fp_Microsoft_Extensions_FileProviders_Physical_PhysicalFileInfo_ctor_0__1__FileInfo(__thrown, info);
    return ret;
}

SG_HNDL_NULLABLE Microsoft_Extensions_FileProviders_Physical_PhysicalFileInfo_Stream__CreateReadStream_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h) {
    if (!_g_Microsoft_Extensions_FileProviders_Physical._fp_Microsoft_Extensions_FileProviders_Physical_PhysicalFileInfo_Stream__CreateReadStream_0__0) {
        my_init();
    }
    SG_HNDL_NULLABLE ret = _g_Microsoft_Extensions_FileProviders_Physical._fp_Microsoft_Extensions_FileProviders_Physical_PhysicalFileInfo_Stream__CreateReadStream_0__0(__thrown, __self_h);
    return ret;
}

int32_t Microsoft_Extensions_FileProviders_Physical_PhysicalFileInfo_bool__get_Exists_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h) {
    if (!_g_Microsoft_Extensions_FileProviders_Physical._fp_Microsoft_Extensions_FileProviders_Physical_PhysicalFileInfo_bool__get_Exists_0__0) {
        my_init();
    }
    int32_t ret = _g_Microsoft_Extensions_FileProviders_Physical._fp_Microsoft_Extensions_FileProviders_Physical_PhysicalFileInfo_bool__get_Exists_0__0(__thrown, __self_h);
    return ret;
}

int32_t Microsoft_Extensions_FileProviders_Physical_PhysicalFileInfo_bool__get_IsDirectory_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h) {
    if (!_g_Microsoft_Extensions_FileProviders_Physical._fp_Microsoft_Extensions_FileProviders_Physical_PhysicalFileInfo_bool__get_IsDirectory_0__0) {
        my_init();
    }
    int32_t ret = _g_Microsoft_Extensions_FileProviders_Physical._fp_Microsoft_Extensions_FileProviders_Physical_PhysicalFileInfo_bool__get_IsDirectory_0__0(__thrown, __self_h);
    return ret;
}

SG_HNDL_NONNULL Microsoft_Extensions_FileProviders_Physical_PhysicalFileInfo_DateTimeOffset__get_LastModified_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h) {
    if (!_g_Microsoft_Extensions_FileProviders_Physical._fp_Microsoft_Extensions_FileProviders_Physical_PhysicalFileInfo_DateTimeOffset__get_LastModified_0__0) {
        my_init();
    }
    SG_HNDL_NONNULL ret = _g_Microsoft_Extensions_FileProviders_Physical._fp_Microsoft_Extensions_FileProviders_Physical_PhysicalFileInfo_DateTimeOffset__get_LastModified_0__0(__thrown, __self_h);
    return ret;
}

int64_t Microsoft_Extensions_FileProviders_Physical_PhysicalFileInfo_i64__get_Length_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h) {
    if (!_g_Microsoft_Extensions_FileProviders_Physical._fp_Microsoft_Extensions_FileProviders_Physical_PhysicalFileInfo_i64__get_Length_0__0) {
        my_init();
    }
    int64_t ret = _g_Microsoft_Extensions_FileProviders_Physical._fp_Microsoft_Extensions_FileProviders_Physical_PhysicalFileInfo_i64__get_Length_0__0(__thrown, __self_h);
    return ret;
}

SG_HNDL_NULLABLE Microsoft_Extensions_FileProviders_Physical_PhysicalFileInfo_String__get_Name_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h) {
    if (!_g_Microsoft_Extensions_FileProviders_Physical._fp_Microsoft_Extensions_FileProviders_Physical_PhysicalFileInfo_String__get_Name_0__0) {
        my_init();
    }
    SG_HNDL_NULLABLE ret = _g_Microsoft_Extensions_FileProviders_Physical._fp_Microsoft_Extensions_FileProviders_Physical_PhysicalFileInfo_String__get_Name_0__0(__thrown, __self_h);
    return ret;
}

SG_HNDL_NULLABLE Microsoft_Extensions_FileProviders_Physical_PhysicalFileInfo_String__get_PhysicalPath_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h) {
    if (!_g_Microsoft_Extensions_FileProviders_Physical._fp_Microsoft_Extensions_FileProviders_Physical_PhysicalFileInfo_String__get_PhysicalPath_0__0) {
        my_init();
    }
    SG_HNDL_NULLABLE ret = _g_Microsoft_Extensions_FileProviders_Physical._fp_Microsoft_Extensions_FileProviders_Physical_PhysicalFileInfo_String__get_PhysicalPath_0__0(__thrown, __self_h);
    return ret;
}

SG_HNDL_NONNULL Microsoft_Extensions_FileProviders_Physical_PhysicalFileInfo_cast(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __h) {
    if (!_g_Microsoft_Extensions_FileProviders_Physical._fp_Microsoft_Extensions_FileProviders_Physical_PhysicalFileInfo_cast) {
        my_init();
    }
    SG_HNDL_NONNULL ret = _g_Microsoft_Extensions_FileProviders_Physical._fp_Microsoft_Extensions_FileProviders_Physical_PhysicalFileInfo_cast(__thrown, __h);
    return ret;
}

TYP Microsoft_Extensions_FileProviders_Physical_PhysicalFilesWatcher_get_type_handle(void) {
    if (!_g_Microsoft_Extensions_FileProviders_Physical._fp_Microsoft_Extensions_FileProviders_Physical_PhysicalFilesWatcher_get_type_handle) {
        my_init();
    }
    TYP ret = _g_Microsoft_Extensions_FileProviders_Physical._fp_Microsoft_Extensions_FileProviders_Physical_PhysicalFilesWatcher_get_type_handle();
    return ret;
}

SG_HNDL_NONNULL Microsoft_Extensions_FileProviders_Physical_PhysicalFilesWatcher_ctor_0__3__String_FileSystemWatcher_bool(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NULLABLE root, SG_HNDL_NULLABLE fileSystemWatcher, int32_t pollForChanges) {
    if (!_g_Microsoft_Extensions_FileProviders_Physical._fp_Microsoft_Extensions_FileProviders_Physical_PhysicalFilesWatcher_ctor_0__3__String_FileSystemWatcher_bool) {
        my_init();
    }
    SG_HNDL_NONNULL ret = _g_Microsoft_Extensions_FileProviders_Physical._fp_Microsoft_Extensions_FileProviders_Physical_PhysicalFilesWatcher_ctor_0__3__String_FileSystemWatcher_bool(__thrown, root, fileSystemWatcher, pollForChanges);
    return ret;
}

SG_HNDL_NONNULL Microsoft_Extensions_FileProviders_Physical_PhysicalFilesWatcher_ctor_0__4__String_FileSystemWatcher_bool_ExclusionFilters(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NULLABLE root, SG_HNDL_NULLABLE fileSystemWatcher, int32_t pollForChanges, int32_t filters) {
    if (!_g_Microsoft_Extensions_FileProviders_Physical._fp_Microsoft_Extensions_FileProviders_Physical_PhysicalFilesWatcher_ctor_0__4__String_FileSystemWatcher_bool_ExclusionFilters) {
        my_init();
    }
    SG_HNDL_NONNULL ret = _g_Microsoft_Extensions_FileProviders_Physical._fp_Microsoft_Extensions_FileProviders_Physical_PhysicalFilesWatcher_ctor_0__4__String_FileSystemWatcher_bool_ExclusionFilters(__thrown, root, fileSystemWatcher, pollForChanges, filters);
    return ret;
}

SG_HNDL_NULLABLE Microsoft_Extensions_FileProviders_Physical_PhysicalFilesWatcher_IChangeToken__CreateFileChangeToken_0__1__String(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h, SG_HNDL_NULLABLE filter) {
    if (!_g_Microsoft_Extensions_FileProviders_Physical._fp_Microsoft_Extensions_FileProviders_Physical_PhysicalFilesWatcher_IChangeToken__CreateFileChangeToken_0__1__String) {
        my_init();
    }
    SG_HNDL_NULLABLE ret = _g_Microsoft_Extensions_FileProviders_Physical._fp_Microsoft_Extensions_FileProviders_Physical_PhysicalFilesWatcher_IChangeToken__CreateFileChangeToken_0__1__String(__thrown, __self_h, filter);
    return ret;
}

void Microsoft_Extensions_FileProviders_Physical_PhysicalFilesWatcher_void__Dispose_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h) {
    if (!_g_Microsoft_Extensions_FileProviders_Physical._fp_Microsoft_Extensions_FileProviders_Physical_PhysicalFilesWatcher_void__Dispose_0__0) {
        my_init();
    }
    _g_Microsoft_Extensions_FileProviders_Physical._fp_Microsoft_Extensions_FileProviders_Physical_PhysicalFilesWatcher_void__Dispose_0__0(__thrown, __self_h);
}

SG_HNDL_NONNULL Microsoft_Extensions_FileProviders_Physical_PhysicalFilesWatcher_cast(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __h) {
    if (!_g_Microsoft_Extensions_FileProviders_Physical._fp_Microsoft_Extensions_FileProviders_Physical_PhysicalFilesWatcher_cast) {
        my_init();
    }
    SG_HNDL_NONNULL ret = _g_Microsoft_Extensions_FileProviders_Physical._fp_Microsoft_Extensions_FileProviders_Physical_PhysicalFilesWatcher_cast(__thrown, __h);
    return ret;
}

TYP Microsoft_Extensions_FileProviders_Physical_PollingFileChangeToken_get_type_handle(void) {
    if (!_g_Microsoft_Extensions_FileProviders_Physical._fp_Microsoft_Extensions_FileProviders_Physical_PollingFileChangeToken_get_type_handle) {
        my_init();
    }
    TYP ret = _g_Microsoft_Extensions_FileProviders_Physical._fp_Microsoft_Extensions_FileProviders_Physical_PollingFileChangeToken_get_type_handle();
    return ret;
}

SG_HNDL_NONNULL Microsoft_Extensions_FileProviders_Physical_PollingFileChangeToken_ctor_0__1__FileInfo(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NULLABLE fileInfo) {
    if (!_g_Microsoft_Extensions_FileProviders_Physical._fp_Microsoft_Extensions_FileProviders_Physical_PollingFileChangeToken_ctor_0__1__FileInfo) {
        my_init();
    }
    SG_HNDL_NONNULL ret = _g_Microsoft_Extensions_FileProviders_Physical._fp_Microsoft_Extensions_FileProviders_Physical_PollingFileChangeToken_ctor_0__1__FileInfo(__thrown, fileInfo);
    return ret;
}

SG_HNDL_NULLABLE Microsoft_Extensions_FileProviders_Physical_PollingFileChangeToken_IDisposable__RegisterChangeCallback_0__2__System_Action_object__Object(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h, SG_HNDL_NULLABLE callback, SG_HNDL_NULLABLE state) {
    if (!_g_Microsoft_Extensions_FileProviders_Physical._fp_Microsoft_Extensions_FileProviders_Physical_PollingFileChangeToken_IDisposable__RegisterChangeCallback_0__2__System_Action_object__Object) {
        my_init();
    }
    SG_HNDL_NULLABLE ret = _g_Microsoft_Extensions_FileProviders_Physical._fp_Microsoft_Extensions_FileProviders_Physical_PollingFileChangeToken_IDisposable__RegisterChangeCallback_0__2__System_Action_object__Object(__thrown, __self_h, callback, state);
    return ret;
}

int32_t Microsoft_Extensions_FileProviders_Physical_PollingFileChangeToken_bool__get_ActiveChangeCallbacks_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h) {
    if (!_g_Microsoft_Extensions_FileProviders_Physical._fp_Microsoft_Extensions_FileProviders_Physical_PollingFileChangeToken_bool__get_ActiveChangeCallbacks_0__0) {
        my_init();
    }
    int32_t ret = _g_Microsoft_Extensions_FileProviders_Physical._fp_Microsoft_Extensions_FileProviders_Physical_PollingFileChangeToken_bool__get_ActiveChangeCallbacks_0__0(__thrown, __self_h);
    return ret;
}

int32_t Microsoft_Extensions_FileProviders_Physical_PollingFileChangeToken_bool__get_HasChanged_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h) {
    if (!_g_Microsoft_Extensions_FileProviders_Physical._fp_Microsoft_Extensions_FileProviders_Physical_PollingFileChangeToken_bool__get_HasChanged_0__0) {
        my_init();
    }
    int32_t ret = _g_Microsoft_Extensions_FileProviders_Physical._fp_Microsoft_Extensions_FileProviders_Physical_PollingFileChangeToken_bool__get_HasChanged_0__0(__thrown, __self_h);
    return ret;
}

SG_HNDL_NONNULL Microsoft_Extensions_FileProviders_Physical_PollingFileChangeToken_cast(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __h) {
    if (!_g_Microsoft_Extensions_FileProviders_Physical._fp_Microsoft_Extensions_FileProviders_Physical_PollingFileChangeToken_cast) {
        my_init();
    }
    SG_HNDL_NONNULL ret = _g_Microsoft_Extensions_FileProviders_Physical._fp_Microsoft_Extensions_FileProviders_Physical_PollingFileChangeToken_cast(__thrown, __h);
    return ret;
}

TYP Microsoft_Extensions_FileProviders_Physical_PollingWildCardChangeToken_get_type_handle(void) {
    if (!_g_Microsoft_Extensions_FileProviders_Physical._fp_Microsoft_Extensions_FileProviders_Physical_PollingWildCardChangeToken_get_type_handle) {
        my_init();
    }
    TYP ret = _g_Microsoft_Extensions_FileProviders_Physical._fp_Microsoft_Extensions_FileProviders_Physical_PollingWildCardChangeToken_get_type_handle();
    return ret;
}

SG_HNDL_NONNULL Microsoft_Extensions_FileProviders_Physical_PollingWildCardChangeToken_ctor_0__2__String_String(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NULLABLE root, SG_HNDL_NULLABLE pattern) {
    if (!_g_Microsoft_Extensions_FileProviders_Physical._fp_Microsoft_Extensions_FileProviders_Physical_PollingWildCardChangeToken_ctor_0__2__String_String) {
        my_init();
    }
    SG_HNDL_NONNULL ret = _g_Microsoft_Extensions_FileProviders_Physical._fp_Microsoft_Extensions_FileProviders_Physical_PollingWildCardChangeToken_ctor_0__2__String_String(__thrown, root, pattern);
    return ret;
}

int32_t Microsoft_Extensions_FileProviders_Physical_PollingWildCardChangeToken_bool__get_ActiveChangeCallbacks_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h) {
    if (!_g_Microsoft_Extensions_FileProviders_Physical._fp_Microsoft_Extensions_FileProviders_Physical_PollingWildCardChangeToken_bool__get_ActiveChangeCallbacks_0__0) {
        my_init();
    }
    int32_t ret = _g_Microsoft_Extensions_FileProviders_Physical._fp_Microsoft_Extensions_FileProviders_Physical_PollingWildCardChangeToken_bool__get_ActiveChangeCallbacks_0__0(__thrown, __self_h);
    return ret;
}

int32_t Microsoft_Extensions_FileProviders_Physical_PollingWildCardChangeToken_bool__get_HasChanged_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h) {
    if (!_g_Microsoft_Extensions_FileProviders_Physical._fp_Microsoft_Extensions_FileProviders_Physical_PollingWildCardChangeToken_bool__get_HasChanged_0__0) {
        my_init();
    }
    int32_t ret = _g_Microsoft_Extensions_FileProviders_Physical._fp_Microsoft_Extensions_FileProviders_Physical_PollingWildCardChangeToken_bool__get_HasChanged_0__0(__thrown, __self_h);
    return ret;
}

SG_HNDL_NONNULL Microsoft_Extensions_FileProviders_Physical_PollingWildCardChangeToken_cast(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __h) {
    if (!_g_Microsoft_Extensions_FileProviders_Physical._fp_Microsoft_Extensions_FileProviders_Physical_PollingWildCardChangeToken_cast) {
        my_init();
    }
    SG_HNDL_NONNULL ret = _g_Microsoft_Extensions_FileProviders_Physical._fp_Microsoft_Extensions_FileProviders_Physical_PollingWildCardChangeToken_cast(__thrown, __h);
    return ret;
}

