// this file is automatically generated with SourceGear Bridge

#include <stdint.h>

#include "Microsoft_Extensions_Configuration_Xml.h"

extern void (*_sg_resolve_jumptable)(const char*, int, void*);

struct {
    SG_HNDL_NULLABLE (* _Nonnull  _fp_Microsoft_Extensions_Configuration_XmlConfigurationExtensions_IConfigurationBuilder__AddXmlFile_0__5__IConfigurationBuilder_IFileProvider_String_bool_bool)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NULLABLE builder, SG_HNDL_NULLABLE provider, SG_HNDL_NULLABLE path, int32_t optional, int32_t reloadOnChange);
    SG_HNDL_NULLABLE (* _Nonnull  _fp_Microsoft_Extensions_Configuration_XmlConfigurationExtensions_IConfigurationBuilder__AddXmlFile_0__2__IConfigurationBuilder_System_Action_Microsoft_Extensions_Configuration_Xml_XmlConfigurationSource_)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NULLABLE builder, SG_HNDL_NULLABLE configureSource);
    SG_HNDL_NULLABLE (* _Nonnull  _fp_Microsoft_Extensions_Configuration_XmlConfigurationExtensions_IConfigurationBuilder__AddXmlFile_0__2__IConfigurationBuilder_String)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NULLABLE builder, SG_HNDL_NULLABLE path);
    SG_HNDL_NULLABLE (* _Nonnull  _fp_Microsoft_Extensions_Configuration_XmlConfigurationExtensions_IConfigurationBuilder__AddXmlFile_0__3__IConfigurationBuilder_String_bool)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NULLABLE builder, SG_HNDL_NULLABLE path, int32_t optional);
    SG_HNDL_NULLABLE (* _Nonnull  _fp_Microsoft_Extensions_Configuration_XmlConfigurationExtensions_IConfigurationBuilder__AddXmlFile_0__4__IConfigurationBuilder_String_bool_bool)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NULLABLE builder, SG_HNDL_NULLABLE path, int32_t optional, int32_t reloadOnChange);
    SG_HNDL_NULLABLE (* _Nonnull  _fp_Microsoft_Extensions_Configuration_XmlConfigurationExtensions_IConfigurationBuilder__AddXmlStream_0__2__IConfigurationBuilder_Stream)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NULLABLE builder, SG_HNDL_NULLABLE stream);
    TYP (* _Nonnull  _fp_Microsoft_Extensions_Configuration_Xml_XmlConfigurationProvider_get_type_handle)(void);
    SG_HNDL_NONNULL (* _Nonnull  _fp_Microsoft_Extensions_Configuration_Xml_XmlConfigurationProvider_ctor_0__1__XmlConfigurationSource)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NULLABLE source);
    void (* _Nonnull  _fp_Microsoft_Extensions_Configuration_Xml_XmlConfigurationProvider_void__Load_0__1__Stream)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h, SG_HNDL_NULLABLE stream);
    SG_HNDL_NONNULL (* _Nonnull  _fp_Microsoft_Extensions_Configuration_Xml_XmlConfigurationProvider_cast)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __h);
    TYP (* _Nonnull  _fp_Microsoft_Extensions_Configuration_Xml_XmlConfigurationSource_get_type_handle)(void);
    SG_HNDL_NONNULL (* _Nonnull  _fp_Microsoft_Extensions_Configuration_Xml_XmlConfigurationSource_ctor_0__0)(SG_HNDL_NULLABLE * _Nonnull __thrown);
    SG_HNDL_NULLABLE (* _Nonnull  _fp_Microsoft_Extensions_Configuration_Xml_XmlConfigurationSource_IConfigurationProvider__Build_0__1__IConfigurationBuilder)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h, SG_HNDL_NULLABLE builder);
    SG_HNDL_NONNULL (* _Nonnull  _fp_Microsoft_Extensions_Configuration_Xml_XmlConfigurationSource_cast)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __h);
    TYP (* _Nonnull  _fp_Microsoft_Extensions_Configuration_Xml_XmlDocumentDecryptor_get_type_handle)(void);
    SG_HNDL_NULLABLE (* _Nonnull  _fp_Microsoft_Extensions_Configuration_Xml_XmlDocumentDecryptor_get_Instance)(void);
    void (* _Nonnull  _fp_Microsoft_Extensions_Configuration_Xml_XmlDocumentDecryptor_set_Instance)(SG_HNDL_NULLABLE __v);
    SG_HNDL_NULLABLE (* _Nonnull  _fp_Microsoft_Extensions_Configuration_Xml_XmlDocumentDecryptor_XmlReader__CreateDecryptingXmlReader_0__2__Stream_XmlReaderSettings)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h, SG_HNDL_NULLABLE input, SG_HNDL_NULLABLE settings);
    SG_HNDL_NONNULL (* _Nonnull  _fp_Microsoft_Extensions_Configuration_Xml_XmlDocumentDecryptor_cast)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __h);
    TYP (* _Nonnull  _fp_Microsoft_Extensions_Configuration_Xml_XmlStreamConfigurationProvider_get_type_handle)(void);
    SG_HNDL_NONNULL (* _Nonnull  _fp_Microsoft_Extensions_Configuration_Xml_XmlStreamConfigurationProvider_ctor_0__1__XmlStreamConfigurationSource)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NULLABLE source);
    void (* _Nonnull  _fp_Microsoft_Extensions_Configuration_Xml_XmlStreamConfigurationProvider_void__Load_0__1__Stream)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h, SG_HNDL_NULLABLE stream);
    SG_HNDL_NULLABLE (* _Nonnull  _fp_Microsoft_Extensions_Configuration_Xml_XmlStreamConfigurationProvider_System_Collections_Generic_IDictionary_string_string___Read_0__2__Stream_XmlDocumentDecryptor)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NULLABLE stream, SG_HNDL_NULLABLE decryptor);
    SG_HNDL_NONNULL (* _Nonnull  _fp_Microsoft_Extensions_Configuration_Xml_XmlStreamConfigurationProvider_cast)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __h);
    TYP (* _Nonnull  _fp_Microsoft_Extensions_Configuration_Xml_XmlStreamConfigurationSource_get_type_handle)(void);
    SG_HNDL_NONNULL (* _Nonnull  _fp_Microsoft_Extensions_Configuration_Xml_XmlStreamConfigurationSource_ctor_0__0)(SG_HNDL_NULLABLE * _Nonnull __thrown);
    SG_HNDL_NULLABLE (* _Nonnull  _fp_Microsoft_Extensions_Configuration_Xml_XmlStreamConfigurationSource_IConfigurationProvider__Build_0__1__IConfigurationBuilder)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h, SG_HNDL_NULLABLE builder);
    SG_HNDL_NONNULL (* _Nonnull  _fp_Microsoft_Extensions_Configuration_Xml_XmlStreamConfigurationSource_cast)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __h);
} _g_Microsoft_Extensions_Configuration_Xml;

static void my_init() {
    _sg_resolve_jumptable("Microsoft_Extensions_Configuration_Xml", 38, &_g_Microsoft_Extensions_Configuration_Xml);
}

SG_HNDL_NULLABLE Microsoft_Extensions_Configuration_XmlConfigurationExtensions_IConfigurationBuilder__AddXmlFile_0__5__IConfigurationBuilder_IFileProvider_String_bool_bool(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NULLABLE builder, SG_HNDL_NULLABLE provider, SG_HNDL_NULLABLE path, int32_t optional, int32_t reloadOnChange) {
    if (!_g_Microsoft_Extensions_Configuration_Xml._fp_Microsoft_Extensions_Configuration_XmlConfigurationExtensions_IConfigurationBuilder__AddXmlFile_0__5__IConfigurationBuilder_IFileProvider_String_bool_bool) {
        my_init();
    }
    SG_HNDL_NULLABLE ret = _g_Microsoft_Extensions_Configuration_Xml._fp_Microsoft_Extensions_Configuration_XmlConfigurationExtensions_IConfigurationBuilder__AddXmlFile_0__5__IConfigurationBuilder_IFileProvider_String_bool_bool(__thrown, builder, provider, path, optional, reloadOnChange);
    return ret;
}

SG_HNDL_NULLABLE Microsoft_Extensions_Configuration_XmlConfigurationExtensions_IConfigurationBuilder__AddXmlFile_0__2__IConfigurationBuilder_System_Action_Microsoft_Extensions_Configuration_Xml_XmlConfigurationSource_(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NULLABLE builder, SG_HNDL_NULLABLE configureSource) {
    if (!_g_Microsoft_Extensions_Configuration_Xml._fp_Microsoft_Extensions_Configuration_XmlConfigurationExtensions_IConfigurationBuilder__AddXmlFile_0__2__IConfigurationBuilder_System_Action_Microsoft_Extensions_Configuration_Xml_XmlConfigurationSource_) {
        my_init();
    }
    SG_HNDL_NULLABLE ret = _g_Microsoft_Extensions_Configuration_Xml._fp_Microsoft_Extensions_Configuration_XmlConfigurationExtensions_IConfigurationBuilder__AddXmlFile_0__2__IConfigurationBuilder_System_Action_Microsoft_Extensions_Configuration_Xml_XmlConfigurationSource_(__thrown, builder, configureSource);
    return ret;
}

SG_HNDL_NULLABLE Microsoft_Extensions_Configuration_XmlConfigurationExtensions_IConfigurationBuilder__AddXmlFile_0__2__IConfigurationBuilder_String(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NULLABLE builder, SG_HNDL_NULLABLE path) {
    if (!_g_Microsoft_Extensions_Configuration_Xml._fp_Microsoft_Extensions_Configuration_XmlConfigurationExtensions_IConfigurationBuilder__AddXmlFile_0__2__IConfigurationBuilder_String) {
        my_init();
    }
    SG_HNDL_NULLABLE ret = _g_Microsoft_Extensions_Configuration_Xml._fp_Microsoft_Extensions_Configuration_XmlConfigurationExtensions_IConfigurationBuilder__AddXmlFile_0__2__IConfigurationBuilder_String(__thrown, builder, path);
    return ret;
}

SG_HNDL_NULLABLE Microsoft_Extensions_Configuration_XmlConfigurationExtensions_IConfigurationBuilder__AddXmlFile_0__3__IConfigurationBuilder_String_bool(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NULLABLE builder, SG_HNDL_NULLABLE path, int32_t optional) {
    if (!_g_Microsoft_Extensions_Configuration_Xml._fp_Microsoft_Extensions_Configuration_XmlConfigurationExtensions_IConfigurationBuilder__AddXmlFile_0__3__IConfigurationBuilder_String_bool) {
        my_init();
    }
    SG_HNDL_NULLABLE ret = _g_Microsoft_Extensions_Configuration_Xml._fp_Microsoft_Extensions_Configuration_XmlConfigurationExtensions_IConfigurationBuilder__AddXmlFile_0__3__IConfigurationBuilder_String_bool(__thrown, builder, path, optional);
    return ret;
}

SG_HNDL_NULLABLE Microsoft_Extensions_Configuration_XmlConfigurationExtensions_IConfigurationBuilder__AddXmlFile_0__4__IConfigurationBuilder_String_bool_bool(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NULLABLE builder, SG_HNDL_NULLABLE path, int32_t optional, int32_t reloadOnChange) {
    if (!_g_Microsoft_Extensions_Configuration_Xml._fp_Microsoft_Extensions_Configuration_XmlConfigurationExtensions_IConfigurationBuilder__AddXmlFile_0__4__IConfigurationBuilder_String_bool_bool) {
        my_init();
    }
    SG_HNDL_NULLABLE ret = _g_Microsoft_Extensions_Configuration_Xml._fp_Microsoft_Extensions_Configuration_XmlConfigurationExtensions_IConfigurationBuilder__AddXmlFile_0__4__IConfigurationBuilder_String_bool_bool(__thrown, builder, path, optional, reloadOnChange);
    return ret;
}

SG_HNDL_NULLABLE Microsoft_Extensions_Configuration_XmlConfigurationExtensions_IConfigurationBuilder__AddXmlStream_0__2__IConfigurationBuilder_Stream(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NULLABLE builder, SG_HNDL_NULLABLE stream) {
    if (!_g_Microsoft_Extensions_Configuration_Xml._fp_Microsoft_Extensions_Configuration_XmlConfigurationExtensions_IConfigurationBuilder__AddXmlStream_0__2__IConfigurationBuilder_Stream) {
        my_init();
    }
    SG_HNDL_NULLABLE ret = _g_Microsoft_Extensions_Configuration_Xml._fp_Microsoft_Extensions_Configuration_XmlConfigurationExtensions_IConfigurationBuilder__AddXmlStream_0__2__IConfigurationBuilder_Stream(__thrown, builder, stream);
    return ret;
}

TYP Microsoft_Extensions_Configuration_Xml_XmlConfigurationProvider_get_type_handle(void) {
    if (!_g_Microsoft_Extensions_Configuration_Xml._fp_Microsoft_Extensions_Configuration_Xml_XmlConfigurationProvider_get_type_handle) {
        my_init();
    }
    TYP ret = _g_Microsoft_Extensions_Configuration_Xml._fp_Microsoft_Extensions_Configuration_Xml_XmlConfigurationProvider_get_type_handle();
    return ret;
}

SG_HNDL_NONNULL Microsoft_Extensions_Configuration_Xml_XmlConfigurationProvider_ctor_0__1__XmlConfigurationSource(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NULLABLE source) {
    if (!_g_Microsoft_Extensions_Configuration_Xml._fp_Microsoft_Extensions_Configuration_Xml_XmlConfigurationProvider_ctor_0__1__XmlConfigurationSource) {
        my_init();
    }
    SG_HNDL_NONNULL ret = _g_Microsoft_Extensions_Configuration_Xml._fp_Microsoft_Extensions_Configuration_Xml_XmlConfigurationProvider_ctor_0__1__XmlConfigurationSource(__thrown, source);
    return ret;
}

void Microsoft_Extensions_Configuration_Xml_XmlConfigurationProvider_void__Load_0__1__Stream(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h, SG_HNDL_NULLABLE stream) {
    if (!_g_Microsoft_Extensions_Configuration_Xml._fp_Microsoft_Extensions_Configuration_Xml_XmlConfigurationProvider_void__Load_0__1__Stream) {
        my_init();
    }
    _g_Microsoft_Extensions_Configuration_Xml._fp_Microsoft_Extensions_Configuration_Xml_XmlConfigurationProvider_void__Load_0__1__Stream(__thrown, __self_h, stream);
}

SG_HNDL_NONNULL Microsoft_Extensions_Configuration_Xml_XmlConfigurationProvider_cast(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __h) {
    if (!_g_Microsoft_Extensions_Configuration_Xml._fp_Microsoft_Extensions_Configuration_Xml_XmlConfigurationProvider_cast) {
        my_init();
    }
    SG_HNDL_NONNULL ret = _g_Microsoft_Extensions_Configuration_Xml._fp_Microsoft_Extensions_Configuration_Xml_XmlConfigurationProvider_cast(__thrown, __h);
    return ret;
}

TYP Microsoft_Extensions_Configuration_Xml_XmlConfigurationSource_get_type_handle(void) {
    if (!_g_Microsoft_Extensions_Configuration_Xml._fp_Microsoft_Extensions_Configuration_Xml_XmlConfigurationSource_get_type_handle) {
        my_init();
    }
    TYP ret = _g_Microsoft_Extensions_Configuration_Xml._fp_Microsoft_Extensions_Configuration_Xml_XmlConfigurationSource_get_type_handle();
    return ret;
}

SG_HNDL_NONNULL Microsoft_Extensions_Configuration_Xml_XmlConfigurationSource_ctor_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown) {
    if (!_g_Microsoft_Extensions_Configuration_Xml._fp_Microsoft_Extensions_Configuration_Xml_XmlConfigurationSource_ctor_0__0) {
        my_init();
    }
    SG_HNDL_NONNULL ret = _g_Microsoft_Extensions_Configuration_Xml._fp_Microsoft_Extensions_Configuration_Xml_XmlConfigurationSource_ctor_0__0(__thrown);
    return ret;
}

SG_HNDL_NULLABLE Microsoft_Extensions_Configuration_Xml_XmlConfigurationSource_IConfigurationProvider__Build_0__1__IConfigurationBuilder(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h, SG_HNDL_NULLABLE builder) {
    if (!_g_Microsoft_Extensions_Configuration_Xml._fp_Microsoft_Extensions_Configuration_Xml_XmlConfigurationSource_IConfigurationProvider__Build_0__1__IConfigurationBuilder) {
        my_init();
    }
    SG_HNDL_NULLABLE ret = _g_Microsoft_Extensions_Configuration_Xml._fp_Microsoft_Extensions_Configuration_Xml_XmlConfigurationSource_IConfigurationProvider__Build_0__1__IConfigurationBuilder(__thrown, __self_h, builder);
    return ret;
}

SG_HNDL_NONNULL Microsoft_Extensions_Configuration_Xml_XmlConfigurationSource_cast(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __h) {
    if (!_g_Microsoft_Extensions_Configuration_Xml._fp_Microsoft_Extensions_Configuration_Xml_XmlConfigurationSource_cast) {
        my_init();
    }
    SG_HNDL_NONNULL ret = _g_Microsoft_Extensions_Configuration_Xml._fp_Microsoft_Extensions_Configuration_Xml_XmlConfigurationSource_cast(__thrown, __h);
    return ret;
}

TYP Microsoft_Extensions_Configuration_Xml_XmlDocumentDecryptor_get_type_handle(void) {
    if (!_g_Microsoft_Extensions_Configuration_Xml._fp_Microsoft_Extensions_Configuration_Xml_XmlDocumentDecryptor_get_type_handle) {
        my_init();
    }
    TYP ret = _g_Microsoft_Extensions_Configuration_Xml._fp_Microsoft_Extensions_Configuration_Xml_XmlDocumentDecryptor_get_type_handle();
    return ret;
}

SG_HNDL_NULLABLE Microsoft_Extensions_Configuration_Xml_XmlDocumentDecryptor_get_Instance(void) {
    if (!_g_Microsoft_Extensions_Configuration_Xml._fp_Microsoft_Extensions_Configuration_Xml_XmlDocumentDecryptor_get_Instance) {
        my_init();
    }
    SG_HNDL_NULLABLE ret = _g_Microsoft_Extensions_Configuration_Xml._fp_Microsoft_Extensions_Configuration_Xml_XmlDocumentDecryptor_get_Instance();
    return ret;
}

void Microsoft_Extensions_Configuration_Xml_XmlDocumentDecryptor_set_Instance(SG_HNDL_NULLABLE __v) {
    if (!_g_Microsoft_Extensions_Configuration_Xml._fp_Microsoft_Extensions_Configuration_Xml_XmlDocumentDecryptor_set_Instance) {
        my_init();
    }
    _g_Microsoft_Extensions_Configuration_Xml._fp_Microsoft_Extensions_Configuration_Xml_XmlDocumentDecryptor_set_Instance(__v);
}

SG_HNDL_NULLABLE Microsoft_Extensions_Configuration_Xml_XmlDocumentDecryptor_XmlReader__CreateDecryptingXmlReader_0__2__Stream_XmlReaderSettings(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h, SG_HNDL_NULLABLE input, SG_HNDL_NULLABLE settings) {
    if (!_g_Microsoft_Extensions_Configuration_Xml._fp_Microsoft_Extensions_Configuration_Xml_XmlDocumentDecryptor_XmlReader__CreateDecryptingXmlReader_0__2__Stream_XmlReaderSettings) {
        my_init();
    }
    SG_HNDL_NULLABLE ret = _g_Microsoft_Extensions_Configuration_Xml._fp_Microsoft_Extensions_Configuration_Xml_XmlDocumentDecryptor_XmlReader__CreateDecryptingXmlReader_0__2__Stream_XmlReaderSettings(__thrown, __self_h, input, settings);
    return ret;
}

SG_HNDL_NONNULL Microsoft_Extensions_Configuration_Xml_XmlDocumentDecryptor_cast(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __h) {
    if (!_g_Microsoft_Extensions_Configuration_Xml._fp_Microsoft_Extensions_Configuration_Xml_XmlDocumentDecryptor_cast) {
        my_init();
    }
    SG_HNDL_NONNULL ret = _g_Microsoft_Extensions_Configuration_Xml._fp_Microsoft_Extensions_Configuration_Xml_XmlDocumentDecryptor_cast(__thrown, __h);
    return ret;
}

TYP Microsoft_Extensions_Configuration_Xml_XmlStreamConfigurationProvider_get_type_handle(void) {
    if (!_g_Microsoft_Extensions_Configuration_Xml._fp_Microsoft_Extensions_Configuration_Xml_XmlStreamConfigurationProvider_get_type_handle) {
        my_init();
    }
    TYP ret = _g_Microsoft_Extensions_Configuration_Xml._fp_Microsoft_Extensions_Configuration_Xml_XmlStreamConfigurationProvider_get_type_handle();
    return ret;
}

SG_HNDL_NONNULL Microsoft_Extensions_Configuration_Xml_XmlStreamConfigurationProvider_ctor_0__1__XmlStreamConfigurationSource(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NULLABLE source) {
    if (!_g_Microsoft_Extensions_Configuration_Xml._fp_Microsoft_Extensions_Configuration_Xml_XmlStreamConfigurationProvider_ctor_0__1__XmlStreamConfigurationSource) {
        my_init();
    }
    SG_HNDL_NONNULL ret = _g_Microsoft_Extensions_Configuration_Xml._fp_Microsoft_Extensions_Configuration_Xml_XmlStreamConfigurationProvider_ctor_0__1__XmlStreamConfigurationSource(__thrown, source);
    return ret;
}

void Microsoft_Extensions_Configuration_Xml_XmlStreamConfigurationProvider_void__Load_0__1__Stream(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h, SG_HNDL_NULLABLE stream) {
    if (!_g_Microsoft_Extensions_Configuration_Xml._fp_Microsoft_Extensions_Configuration_Xml_XmlStreamConfigurationProvider_void__Load_0__1__Stream) {
        my_init();
    }
    _g_Microsoft_Extensions_Configuration_Xml._fp_Microsoft_Extensions_Configuration_Xml_XmlStreamConfigurationProvider_void__Load_0__1__Stream(__thrown, __self_h, stream);
}

SG_HNDL_NULLABLE Microsoft_Extensions_Configuration_Xml_XmlStreamConfigurationProvider_System_Collections_Generic_IDictionary_string_string___Read_0__2__Stream_XmlDocumentDecryptor(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NULLABLE stream, SG_HNDL_NULLABLE decryptor) {
    if (!_g_Microsoft_Extensions_Configuration_Xml._fp_Microsoft_Extensions_Configuration_Xml_XmlStreamConfigurationProvider_System_Collections_Generic_IDictionary_string_string___Read_0__2__Stream_XmlDocumentDecryptor) {
        my_init();
    }
    SG_HNDL_NULLABLE ret = _g_Microsoft_Extensions_Configuration_Xml._fp_Microsoft_Extensions_Configuration_Xml_XmlStreamConfigurationProvider_System_Collections_Generic_IDictionary_string_string___Read_0__2__Stream_XmlDocumentDecryptor(__thrown, stream, decryptor);
    return ret;
}

SG_HNDL_NONNULL Microsoft_Extensions_Configuration_Xml_XmlStreamConfigurationProvider_cast(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __h) {
    if (!_g_Microsoft_Extensions_Configuration_Xml._fp_Microsoft_Extensions_Configuration_Xml_XmlStreamConfigurationProvider_cast) {
        my_init();
    }
    SG_HNDL_NONNULL ret = _g_Microsoft_Extensions_Configuration_Xml._fp_Microsoft_Extensions_Configuration_Xml_XmlStreamConfigurationProvider_cast(__thrown, __h);
    return ret;
}

TYP Microsoft_Extensions_Configuration_Xml_XmlStreamConfigurationSource_get_type_handle(void) {
    if (!_g_Microsoft_Extensions_Configuration_Xml._fp_Microsoft_Extensions_Configuration_Xml_XmlStreamConfigurationSource_get_type_handle) {
        my_init();
    }
    TYP ret = _g_Microsoft_Extensions_Configuration_Xml._fp_Microsoft_Extensions_Configuration_Xml_XmlStreamConfigurationSource_get_type_handle();
    return ret;
}

SG_HNDL_NONNULL Microsoft_Extensions_Configuration_Xml_XmlStreamConfigurationSource_ctor_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown) {
    if (!_g_Microsoft_Extensions_Configuration_Xml._fp_Microsoft_Extensions_Configuration_Xml_XmlStreamConfigurationSource_ctor_0__0) {
        my_init();
    }
    SG_HNDL_NONNULL ret = _g_Microsoft_Extensions_Configuration_Xml._fp_Microsoft_Extensions_Configuration_Xml_XmlStreamConfigurationSource_ctor_0__0(__thrown);
    return ret;
}

SG_HNDL_NULLABLE Microsoft_Extensions_Configuration_Xml_XmlStreamConfigurationSource_IConfigurationProvider__Build_0__1__IConfigurationBuilder(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h, SG_HNDL_NULLABLE builder) {
    if (!_g_Microsoft_Extensions_Configuration_Xml._fp_Microsoft_Extensions_Configuration_Xml_XmlStreamConfigurationSource_IConfigurationProvider__Build_0__1__IConfigurationBuilder) {
        my_init();
    }
    SG_HNDL_NULLABLE ret = _g_Microsoft_Extensions_Configuration_Xml._fp_Microsoft_Extensions_Configuration_Xml_XmlStreamConfigurationSource_IConfigurationProvider__Build_0__1__IConfigurationBuilder(__thrown, __self_h, builder);
    return ret;
}

SG_HNDL_NONNULL Microsoft_Extensions_Configuration_Xml_XmlStreamConfigurationSource_cast(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __h) {
    if (!_g_Microsoft_Extensions_Configuration_Xml._fp_Microsoft_Extensions_Configuration_Xml_XmlStreamConfigurationSource_cast) {
        my_init();
    }
    SG_HNDL_NONNULL ret = _g_Microsoft_Extensions_Configuration_Xml._fp_Microsoft_Extensions_Configuration_Xml_XmlStreamConfigurationSource_cast(__thrown, __h);
    return ret;
}

