// this file is automatically generated with SourceGear Bridge

#include <stdint.h>

#include "Microsoft_AspNetCore_HttpLogging.h"

extern void (*_sg_resolve_jumptable)(const char*, int, void*);

struct {
    SG_HNDL_NONNULL (* _Nonnull  _fp_Microsoft_AspNetCore_Builder_HttpLoggingBuilderExtensions_IApplicationBuilder__UseHttpLogging_0__1__IApplicationBuilder)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL app);
    SG_HNDL_NONNULL (* _Nonnull  _fp_Microsoft_AspNetCore_Builder_HttpLoggingBuilderExtensions_IApplicationBuilder__UseW3CLogging_0__1__IApplicationBuilder)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL app);
    TYP (* _Nonnull  _fp_Microsoft_AspNetCore_HttpLogging_HttpLoggingFields_get_type_handle)(void);
    int64_t (* _Nonnull  _fp_Microsoft_AspNetCore_HttpLogging_HttpLoggingFields_get_None)(void);
    int64_t (* _Nonnull  _fp_Microsoft_AspNetCore_HttpLogging_HttpLoggingFields_get_RequestPath)(void);
    int64_t (* _Nonnull  _fp_Microsoft_AspNetCore_HttpLogging_HttpLoggingFields_get_RequestQuery)(void);
    int64_t (* _Nonnull  _fp_Microsoft_AspNetCore_HttpLogging_HttpLoggingFields_get_RequestProtocol)(void);
    int64_t (* _Nonnull  _fp_Microsoft_AspNetCore_HttpLogging_HttpLoggingFields_get_RequestMethod)(void);
    int64_t (* _Nonnull  _fp_Microsoft_AspNetCore_HttpLogging_HttpLoggingFields_get_RequestScheme)(void);
    int64_t (* _Nonnull  _fp_Microsoft_AspNetCore_HttpLogging_HttpLoggingFields_get_ResponseStatusCode)(void);
    int64_t (* _Nonnull  _fp_Microsoft_AspNetCore_HttpLogging_HttpLoggingFields_get_RequestHeaders)(void);
    int64_t (* _Nonnull  _fp_Microsoft_AspNetCore_HttpLogging_HttpLoggingFields_get_ResponseHeaders)(void);
    int64_t (* _Nonnull  _fp_Microsoft_AspNetCore_HttpLogging_HttpLoggingFields_get_RequestTrailers)(void);
    int64_t (* _Nonnull  _fp_Microsoft_AspNetCore_HttpLogging_HttpLoggingFields_get_ResponseTrailers)(void);
    int64_t (* _Nonnull  _fp_Microsoft_AspNetCore_HttpLogging_HttpLoggingFields_get_RequestBody)(void);
    int64_t (* _Nonnull  _fp_Microsoft_AspNetCore_HttpLogging_HttpLoggingFields_get_ResponseBody)(void);
    int64_t (* _Nonnull  _fp_Microsoft_AspNetCore_HttpLogging_HttpLoggingFields_get_RequestProperties)(void);
    int64_t (* _Nonnull  _fp_Microsoft_AspNetCore_HttpLogging_HttpLoggingFields_get_RequestPropertiesAndHeaders)(void);
    int64_t (* _Nonnull  _fp_Microsoft_AspNetCore_HttpLogging_HttpLoggingFields_get_ResponsePropertiesAndHeaders)(void);
    int64_t (* _Nonnull  _fp_Microsoft_AspNetCore_HttpLogging_HttpLoggingFields_get_Request)(void);
    int64_t (* _Nonnull  _fp_Microsoft_AspNetCore_HttpLogging_HttpLoggingFields_get_Response)(void);
    int64_t (* _Nonnull  _fp_Microsoft_AspNetCore_HttpLogging_HttpLoggingFields_get_All)(void);
    TYP (* _Nonnull  _fp_Microsoft_AspNetCore_HttpLogging_HttpLoggingOptions_get_type_handle)(void);
    SG_HNDL_NONNULL (* _Nonnull  _fp_Microsoft_AspNetCore_HttpLogging_HttpLoggingOptions_ctor_0__0)(SG_HNDL_NULLABLE * _Nonnull __thrown);
    int64_t (* _Nonnull  _fp_Microsoft_AspNetCore_HttpLogging_HttpLoggingOptions_HttpLoggingFields__get_LoggingFields_0__0)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h);
    void (* _Nonnull  _fp_Microsoft_AspNetCore_HttpLogging_HttpLoggingOptions_void__set_LoggingFields_0__1__HttpLoggingFields)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h, int64_t value);
    SG_HNDL_NONNULL (* _Nonnull  _fp_Microsoft_AspNetCore_HttpLogging_HttpLoggingOptions_System_Collections_Generic_ISet_string___get_RequestHeaders_0__0)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h);
    SG_HNDL_NONNULL (* _Nonnull  _fp_Microsoft_AspNetCore_HttpLogging_HttpLoggingOptions_System_Collections_Generic_ISet_string___get_ResponseHeaders_0__0)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h);
    SG_HNDL_NONNULL (* _Nonnull  _fp_Microsoft_AspNetCore_HttpLogging_HttpLoggingOptions_MediaTypeOptions__get_MediaTypeOptions_0__0)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h);
    int32_t (* _Nonnull  _fp_Microsoft_AspNetCore_HttpLogging_HttpLoggingOptions_i32__get_RequestBodyLogLimit_0__0)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h);
    void (* _Nonnull  _fp_Microsoft_AspNetCore_HttpLogging_HttpLoggingOptions_void__set_RequestBodyLogLimit_0__1__i32)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h, int32_t value);
    int32_t (* _Nonnull  _fp_Microsoft_AspNetCore_HttpLogging_HttpLoggingOptions_i32__get_ResponseBodyLogLimit_0__0)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h);
    void (* _Nonnull  _fp_Microsoft_AspNetCore_HttpLogging_HttpLoggingOptions_void__set_ResponseBodyLogLimit_0__1__i32)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h, int32_t value);
    SG_HNDL_NONNULL (* _Nonnull  _fp_Microsoft_AspNetCore_HttpLogging_HttpLoggingOptions_cast)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __h);
    TYP (* _Nonnull  _fp_Microsoft_AspNetCore_HttpLogging_MediaTypeOptions_get_type_handle)(void);
    void (* _Nonnull  _fp_Microsoft_AspNetCore_HttpLogging_MediaTypeOptions_void__AddText_0__1__String)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h, SG_HNDL_NONNULL contentType);
    void (* _Nonnull  _fp_Microsoft_AspNetCore_HttpLogging_MediaTypeOptions_void__AddText_0__2__String_Encoding)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h, SG_HNDL_NONNULL contentType, SG_HNDL_NONNULL encoding);
    void (* _Nonnull  _fp_Microsoft_AspNetCore_HttpLogging_MediaTypeOptions_void__AddBinary_0__1__MediaTypeHeaderValue)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h, SG_HNDL_NONNULL mediaType);
    void (* _Nonnull  _fp_Microsoft_AspNetCore_HttpLogging_MediaTypeOptions_void__AddBinary_0__1__String)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h, SG_HNDL_NONNULL contentType);
    void (* _Nonnull  _fp_Microsoft_AspNetCore_HttpLogging_MediaTypeOptions_void__Clear_0__0)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h);
    SG_HNDL_NONNULL (* _Nonnull  _fp_Microsoft_AspNetCore_HttpLogging_MediaTypeOptions_cast)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __h);
    TYP (* _Nonnull  _fp_Microsoft_AspNetCore_HttpLogging_W3CLoggerOptions_get_type_handle)(void);
    SG_HNDL_NONNULL (* _Nonnull  _fp_Microsoft_AspNetCore_HttpLogging_W3CLoggerOptions_ctor_0__0)(SG_HNDL_NULLABLE * _Nonnull __thrown);
    SG_HNDL_NULLABLE (* _Nonnull  _fp_Microsoft_AspNetCore_HttpLogging_W3CLoggerOptions_System_Nullable_i32___get_FileSizeLimit_0__0)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h);
    void (* _Nonnull  _fp_Microsoft_AspNetCore_HttpLogging_W3CLoggerOptions_void__set_FileSizeLimit_0__1__System_Nullable_i32_)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h, SG_HNDL_NULLABLE value);
    SG_HNDL_NULLABLE (* _Nonnull  _fp_Microsoft_AspNetCore_HttpLogging_W3CLoggerOptions_System_Nullable_i32___get_RetainedFileCountLimit_0__0)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h);
    void (* _Nonnull  _fp_Microsoft_AspNetCore_HttpLogging_W3CLoggerOptions_void__set_RetainedFileCountLimit_0__1__System_Nullable_i32_)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h, SG_HNDL_NULLABLE value);
    SG_HNDL_NONNULL (* _Nonnull  _fp_Microsoft_AspNetCore_HttpLogging_W3CLoggerOptions_String__get_FileName_0__0)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h);
    void (* _Nonnull  _fp_Microsoft_AspNetCore_HttpLogging_W3CLoggerOptions_void__set_FileName_0__1__String)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h, SG_HNDL_NONNULL value);
    SG_HNDL_NONNULL (* _Nonnull  _fp_Microsoft_AspNetCore_HttpLogging_W3CLoggerOptions_String__get_LogDirectory_0__0)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h);
    void (* _Nonnull  _fp_Microsoft_AspNetCore_HttpLogging_W3CLoggerOptions_void__set_LogDirectory_0__1__String)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h, SG_HNDL_NONNULL value);
    SG_HNDL_NONNULL (* _Nonnull  _fp_Microsoft_AspNetCore_HttpLogging_W3CLoggerOptions_TimeSpan__get_FlushInterval_0__0)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h);
    void (* _Nonnull  _fp_Microsoft_AspNetCore_HttpLogging_W3CLoggerOptions_void__set_FlushInterval_0__1__TimeSpan)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h, SG_HNDL_NONNULL value);
    int64_t (* _Nonnull  _fp_Microsoft_AspNetCore_HttpLogging_W3CLoggerOptions_W3CLoggingFields__get_LoggingFields_0__0)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h);
    void (* _Nonnull  _fp_Microsoft_AspNetCore_HttpLogging_W3CLoggerOptions_void__set_LoggingFields_0__1__W3CLoggingFields)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h, int64_t value);
    SG_HNDL_NONNULL (* _Nonnull  _fp_Microsoft_AspNetCore_HttpLogging_W3CLoggerOptions_cast)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __h);
    TYP (* _Nonnull  _fp_Microsoft_AspNetCore_HttpLogging_W3CLoggingFields_get_type_handle)(void);
    int64_t (* _Nonnull  _fp_Microsoft_AspNetCore_HttpLogging_W3CLoggingFields_get_None)(void);
    int64_t (* _Nonnull  _fp_Microsoft_AspNetCore_HttpLogging_W3CLoggingFields_get_Date)(void);
    int64_t (* _Nonnull  _fp_Microsoft_AspNetCore_HttpLogging_W3CLoggingFields_get_Time)(void);
    int64_t (* _Nonnull  _fp_Microsoft_AspNetCore_HttpLogging_W3CLoggingFields_get_ClientIpAddress)(void);
    int64_t (* _Nonnull  _fp_Microsoft_AspNetCore_HttpLogging_W3CLoggingFields_get_UserName)(void);
    int64_t (* _Nonnull  _fp_Microsoft_AspNetCore_HttpLogging_W3CLoggingFields_get_ServerName)(void);
    int64_t (* _Nonnull  _fp_Microsoft_AspNetCore_HttpLogging_W3CLoggingFields_get_ServerIpAddress)(void);
    int64_t (* _Nonnull  _fp_Microsoft_AspNetCore_HttpLogging_W3CLoggingFields_get_ServerPort)(void);
    int64_t (* _Nonnull  _fp_Microsoft_AspNetCore_HttpLogging_W3CLoggingFields_get_Method)(void);
    int64_t (* _Nonnull  _fp_Microsoft_AspNetCore_HttpLogging_W3CLoggingFields_get_UriStem)(void);
    int64_t (* _Nonnull  _fp_Microsoft_AspNetCore_HttpLogging_W3CLoggingFields_get_UriQuery)(void);
    int64_t (* _Nonnull  _fp_Microsoft_AspNetCore_HttpLogging_W3CLoggingFields_get_ProtocolStatus)(void);
    int64_t (* _Nonnull  _fp_Microsoft_AspNetCore_HttpLogging_W3CLoggingFields_get_TimeTaken)(void);
    int64_t (* _Nonnull  _fp_Microsoft_AspNetCore_HttpLogging_W3CLoggingFields_get_ProtocolVersion)(void);
    int64_t (* _Nonnull  _fp_Microsoft_AspNetCore_HttpLogging_W3CLoggingFields_get_Host)(void);
    int64_t (* _Nonnull  _fp_Microsoft_AspNetCore_HttpLogging_W3CLoggingFields_get_UserAgent)(void);
    int64_t (* _Nonnull  _fp_Microsoft_AspNetCore_HttpLogging_W3CLoggingFields_get_Cookie)(void);
    int64_t (* _Nonnull  _fp_Microsoft_AspNetCore_HttpLogging_W3CLoggingFields_get_Referer)(void);
    int64_t (* _Nonnull  _fp_Microsoft_AspNetCore_HttpLogging_W3CLoggingFields_get_ConnectionInfoFields)(void);
    int64_t (* _Nonnull  _fp_Microsoft_AspNetCore_HttpLogging_W3CLoggingFields_get_RequestHeaders)(void);
    int64_t (* _Nonnull  _fp_Microsoft_AspNetCore_HttpLogging_W3CLoggingFields_get_Request)(void);
    int64_t (* _Nonnull  _fp_Microsoft_AspNetCore_HttpLogging_W3CLoggingFields_get_All)(void);
    SG_HNDL_NONNULL (* _Nonnull  _fp_Microsoft_Extensions_DependencyInjection_HttpLoggingServicesExtensions_IServiceCollection__AddHttpLogging_0__2__IServiceCollection_System_Action_Microsoft_AspNetCore_HttpLogging_HttpLoggingOptions_)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL services, SG_HNDL_NONNULL configureOptions);
    SG_HNDL_NONNULL (* _Nonnull  _fp_Microsoft_Extensions_DependencyInjection_HttpLoggingServicesExtensions_IServiceCollection__AddW3CLogging_0__2__IServiceCollection_System_Action_Microsoft_AspNetCore_HttpLogging_W3CLoggerOptions_)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL services, SG_HNDL_NONNULL configureOptions);
} _g_Microsoft_AspNetCore_HttpLogging;

static void my_init() {
    _sg_resolve_jumptable("Microsoft_AspNetCore_HttpLogging", 32, &_g_Microsoft_AspNetCore_HttpLogging);
}

SG_HNDL_NONNULL Microsoft_AspNetCore_Builder_HttpLoggingBuilderExtensions_IApplicationBuilder__UseHttpLogging_0__1__IApplicationBuilder(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL app) {
    if (!_g_Microsoft_AspNetCore_HttpLogging._fp_Microsoft_AspNetCore_Builder_HttpLoggingBuilderExtensions_IApplicationBuilder__UseHttpLogging_0__1__IApplicationBuilder) {
        my_init();
    }
    SG_HNDL_NONNULL ret = _g_Microsoft_AspNetCore_HttpLogging._fp_Microsoft_AspNetCore_Builder_HttpLoggingBuilderExtensions_IApplicationBuilder__UseHttpLogging_0__1__IApplicationBuilder(__thrown, app);
    return ret;
}

SG_HNDL_NONNULL Microsoft_AspNetCore_Builder_HttpLoggingBuilderExtensions_IApplicationBuilder__UseW3CLogging_0__1__IApplicationBuilder(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL app) {
    if (!_g_Microsoft_AspNetCore_HttpLogging._fp_Microsoft_AspNetCore_Builder_HttpLoggingBuilderExtensions_IApplicationBuilder__UseW3CLogging_0__1__IApplicationBuilder) {
        my_init();
    }
    SG_HNDL_NONNULL ret = _g_Microsoft_AspNetCore_HttpLogging._fp_Microsoft_AspNetCore_Builder_HttpLoggingBuilderExtensions_IApplicationBuilder__UseW3CLogging_0__1__IApplicationBuilder(__thrown, app);
    return ret;
}

TYP Microsoft_AspNetCore_HttpLogging_HttpLoggingFields_get_type_handle(void) {
    if (!_g_Microsoft_AspNetCore_HttpLogging._fp_Microsoft_AspNetCore_HttpLogging_HttpLoggingFields_get_type_handle) {
        my_init();
    }
    TYP ret = _g_Microsoft_AspNetCore_HttpLogging._fp_Microsoft_AspNetCore_HttpLogging_HttpLoggingFields_get_type_handle();
    return ret;
}

int64_t Microsoft_AspNetCore_HttpLogging_HttpLoggingFields_get_None(void) {
    if (!_g_Microsoft_AspNetCore_HttpLogging._fp_Microsoft_AspNetCore_HttpLogging_HttpLoggingFields_get_None) {
        my_init();
    }
    int64_t ret = _g_Microsoft_AspNetCore_HttpLogging._fp_Microsoft_AspNetCore_HttpLogging_HttpLoggingFields_get_None();
    return ret;
}

int64_t Microsoft_AspNetCore_HttpLogging_HttpLoggingFields_get_RequestPath(void) {
    if (!_g_Microsoft_AspNetCore_HttpLogging._fp_Microsoft_AspNetCore_HttpLogging_HttpLoggingFields_get_RequestPath) {
        my_init();
    }
    int64_t ret = _g_Microsoft_AspNetCore_HttpLogging._fp_Microsoft_AspNetCore_HttpLogging_HttpLoggingFields_get_RequestPath();
    return ret;
}

int64_t Microsoft_AspNetCore_HttpLogging_HttpLoggingFields_get_RequestQuery(void) {
    if (!_g_Microsoft_AspNetCore_HttpLogging._fp_Microsoft_AspNetCore_HttpLogging_HttpLoggingFields_get_RequestQuery) {
        my_init();
    }
    int64_t ret = _g_Microsoft_AspNetCore_HttpLogging._fp_Microsoft_AspNetCore_HttpLogging_HttpLoggingFields_get_RequestQuery();
    return ret;
}

int64_t Microsoft_AspNetCore_HttpLogging_HttpLoggingFields_get_RequestProtocol(void) {
    if (!_g_Microsoft_AspNetCore_HttpLogging._fp_Microsoft_AspNetCore_HttpLogging_HttpLoggingFields_get_RequestProtocol) {
        my_init();
    }
    int64_t ret = _g_Microsoft_AspNetCore_HttpLogging._fp_Microsoft_AspNetCore_HttpLogging_HttpLoggingFields_get_RequestProtocol();
    return ret;
}

int64_t Microsoft_AspNetCore_HttpLogging_HttpLoggingFields_get_RequestMethod(void) {
    if (!_g_Microsoft_AspNetCore_HttpLogging._fp_Microsoft_AspNetCore_HttpLogging_HttpLoggingFields_get_RequestMethod) {
        my_init();
    }
    int64_t ret = _g_Microsoft_AspNetCore_HttpLogging._fp_Microsoft_AspNetCore_HttpLogging_HttpLoggingFields_get_RequestMethod();
    return ret;
}

int64_t Microsoft_AspNetCore_HttpLogging_HttpLoggingFields_get_RequestScheme(void) {
    if (!_g_Microsoft_AspNetCore_HttpLogging._fp_Microsoft_AspNetCore_HttpLogging_HttpLoggingFields_get_RequestScheme) {
        my_init();
    }
    int64_t ret = _g_Microsoft_AspNetCore_HttpLogging._fp_Microsoft_AspNetCore_HttpLogging_HttpLoggingFields_get_RequestScheme();
    return ret;
}

int64_t Microsoft_AspNetCore_HttpLogging_HttpLoggingFields_get_ResponseStatusCode(void) {
    if (!_g_Microsoft_AspNetCore_HttpLogging._fp_Microsoft_AspNetCore_HttpLogging_HttpLoggingFields_get_ResponseStatusCode) {
        my_init();
    }
    int64_t ret = _g_Microsoft_AspNetCore_HttpLogging._fp_Microsoft_AspNetCore_HttpLogging_HttpLoggingFields_get_ResponseStatusCode();
    return ret;
}

int64_t Microsoft_AspNetCore_HttpLogging_HttpLoggingFields_get_RequestHeaders(void) {
    if (!_g_Microsoft_AspNetCore_HttpLogging._fp_Microsoft_AspNetCore_HttpLogging_HttpLoggingFields_get_RequestHeaders) {
        my_init();
    }
    int64_t ret = _g_Microsoft_AspNetCore_HttpLogging._fp_Microsoft_AspNetCore_HttpLogging_HttpLoggingFields_get_RequestHeaders();
    return ret;
}

int64_t Microsoft_AspNetCore_HttpLogging_HttpLoggingFields_get_ResponseHeaders(void) {
    if (!_g_Microsoft_AspNetCore_HttpLogging._fp_Microsoft_AspNetCore_HttpLogging_HttpLoggingFields_get_ResponseHeaders) {
        my_init();
    }
    int64_t ret = _g_Microsoft_AspNetCore_HttpLogging._fp_Microsoft_AspNetCore_HttpLogging_HttpLoggingFields_get_ResponseHeaders();
    return ret;
}

int64_t Microsoft_AspNetCore_HttpLogging_HttpLoggingFields_get_RequestTrailers(void) {
    if (!_g_Microsoft_AspNetCore_HttpLogging._fp_Microsoft_AspNetCore_HttpLogging_HttpLoggingFields_get_RequestTrailers) {
        my_init();
    }
    int64_t ret = _g_Microsoft_AspNetCore_HttpLogging._fp_Microsoft_AspNetCore_HttpLogging_HttpLoggingFields_get_RequestTrailers();
    return ret;
}

int64_t Microsoft_AspNetCore_HttpLogging_HttpLoggingFields_get_ResponseTrailers(void) {
    if (!_g_Microsoft_AspNetCore_HttpLogging._fp_Microsoft_AspNetCore_HttpLogging_HttpLoggingFields_get_ResponseTrailers) {
        my_init();
    }
    int64_t ret = _g_Microsoft_AspNetCore_HttpLogging._fp_Microsoft_AspNetCore_HttpLogging_HttpLoggingFields_get_ResponseTrailers();
    return ret;
}

int64_t Microsoft_AspNetCore_HttpLogging_HttpLoggingFields_get_RequestBody(void) {
    if (!_g_Microsoft_AspNetCore_HttpLogging._fp_Microsoft_AspNetCore_HttpLogging_HttpLoggingFields_get_RequestBody) {
        my_init();
    }
    int64_t ret = _g_Microsoft_AspNetCore_HttpLogging._fp_Microsoft_AspNetCore_HttpLogging_HttpLoggingFields_get_RequestBody();
    return ret;
}

int64_t Microsoft_AspNetCore_HttpLogging_HttpLoggingFields_get_ResponseBody(void) {
    if (!_g_Microsoft_AspNetCore_HttpLogging._fp_Microsoft_AspNetCore_HttpLogging_HttpLoggingFields_get_ResponseBody) {
        my_init();
    }
    int64_t ret = _g_Microsoft_AspNetCore_HttpLogging._fp_Microsoft_AspNetCore_HttpLogging_HttpLoggingFields_get_ResponseBody();
    return ret;
}

int64_t Microsoft_AspNetCore_HttpLogging_HttpLoggingFields_get_RequestProperties(void) {
    if (!_g_Microsoft_AspNetCore_HttpLogging._fp_Microsoft_AspNetCore_HttpLogging_HttpLoggingFields_get_RequestProperties) {
        my_init();
    }
    int64_t ret = _g_Microsoft_AspNetCore_HttpLogging._fp_Microsoft_AspNetCore_HttpLogging_HttpLoggingFields_get_RequestProperties();
    return ret;
}

int64_t Microsoft_AspNetCore_HttpLogging_HttpLoggingFields_get_RequestPropertiesAndHeaders(void) {
    if (!_g_Microsoft_AspNetCore_HttpLogging._fp_Microsoft_AspNetCore_HttpLogging_HttpLoggingFields_get_RequestPropertiesAndHeaders) {
        my_init();
    }
    int64_t ret = _g_Microsoft_AspNetCore_HttpLogging._fp_Microsoft_AspNetCore_HttpLogging_HttpLoggingFields_get_RequestPropertiesAndHeaders();
    return ret;
}

int64_t Microsoft_AspNetCore_HttpLogging_HttpLoggingFields_get_ResponsePropertiesAndHeaders(void) {
    if (!_g_Microsoft_AspNetCore_HttpLogging._fp_Microsoft_AspNetCore_HttpLogging_HttpLoggingFields_get_ResponsePropertiesAndHeaders) {
        my_init();
    }
    int64_t ret = _g_Microsoft_AspNetCore_HttpLogging._fp_Microsoft_AspNetCore_HttpLogging_HttpLoggingFields_get_ResponsePropertiesAndHeaders();
    return ret;
}

int64_t Microsoft_AspNetCore_HttpLogging_HttpLoggingFields_get_Request(void) {
    if (!_g_Microsoft_AspNetCore_HttpLogging._fp_Microsoft_AspNetCore_HttpLogging_HttpLoggingFields_get_Request) {
        my_init();
    }
    int64_t ret = _g_Microsoft_AspNetCore_HttpLogging._fp_Microsoft_AspNetCore_HttpLogging_HttpLoggingFields_get_Request();
    return ret;
}

int64_t Microsoft_AspNetCore_HttpLogging_HttpLoggingFields_get_Response(void) {
    if (!_g_Microsoft_AspNetCore_HttpLogging._fp_Microsoft_AspNetCore_HttpLogging_HttpLoggingFields_get_Response) {
        my_init();
    }
    int64_t ret = _g_Microsoft_AspNetCore_HttpLogging._fp_Microsoft_AspNetCore_HttpLogging_HttpLoggingFields_get_Response();
    return ret;
}

int64_t Microsoft_AspNetCore_HttpLogging_HttpLoggingFields_get_All(void) {
    if (!_g_Microsoft_AspNetCore_HttpLogging._fp_Microsoft_AspNetCore_HttpLogging_HttpLoggingFields_get_All) {
        my_init();
    }
    int64_t ret = _g_Microsoft_AspNetCore_HttpLogging._fp_Microsoft_AspNetCore_HttpLogging_HttpLoggingFields_get_All();
    return ret;
}

TYP Microsoft_AspNetCore_HttpLogging_HttpLoggingOptions_get_type_handle(void) {
    if (!_g_Microsoft_AspNetCore_HttpLogging._fp_Microsoft_AspNetCore_HttpLogging_HttpLoggingOptions_get_type_handle) {
        my_init();
    }
    TYP ret = _g_Microsoft_AspNetCore_HttpLogging._fp_Microsoft_AspNetCore_HttpLogging_HttpLoggingOptions_get_type_handle();
    return ret;
}

SG_HNDL_NONNULL Microsoft_AspNetCore_HttpLogging_HttpLoggingOptions_ctor_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown) {
    if (!_g_Microsoft_AspNetCore_HttpLogging._fp_Microsoft_AspNetCore_HttpLogging_HttpLoggingOptions_ctor_0__0) {
        my_init();
    }
    SG_HNDL_NONNULL ret = _g_Microsoft_AspNetCore_HttpLogging._fp_Microsoft_AspNetCore_HttpLogging_HttpLoggingOptions_ctor_0__0(__thrown);
    return ret;
}

int64_t Microsoft_AspNetCore_HttpLogging_HttpLoggingOptions_HttpLoggingFields__get_LoggingFields_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h) {
    if (!_g_Microsoft_AspNetCore_HttpLogging._fp_Microsoft_AspNetCore_HttpLogging_HttpLoggingOptions_HttpLoggingFields__get_LoggingFields_0__0) {
        my_init();
    }
    int64_t ret = _g_Microsoft_AspNetCore_HttpLogging._fp_Microsoft_AspNetCore_HttpLogging_HttpLoggingOptions_HttpLoggingFields__get_LoggingFields_0__0(__thrown, __self_h);
    return ret;
}

void Microsoft_AspNetCore_HttpLogging_HttpLoggingOptions_void__set_LoggingFields_0__1__HttpLoggingFields(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h, int64_t value) {
    if (!_g_Microsoft_AspNetCore_HttpLogging._fp_Microsoft_AspNetCore_HttpLogging_HttpLoggingOptions_void__set_LoggingFields_0__1__HttpLoggingFields) {
        my_init();
    }
    _g_Microsoft_AspNetCore_HttpLogging._fp_Microsoft_AspNetCore_HttpLogging_HttpLoggingOptions_void__set_LoggingFields_0__1__HttpLoggingFields(__thrown, __self_h, value);
}

SG_HNDL_NONNULL Microsoft_AspNetCore_HttpLogging_HttpLoggingOptions_System_Collections_Generic_ISet_string___get_RequestHeaders_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h) {
    if (!_g_Microsoft_AspNetCore_HttpLogging._fp_Microsoft_AspNetCore_HttpLogging_HttpLoggingOptions_System_Collections_Generic_ISet_string___get_RequestHeaders_0__0) {
        my_init();
    }
    SG_HNDL_NONNULL ret = _g_Microsoft_AspNetCore_HttpLogging._fp_Microsoft_AspNetCore_HttpLogging_HttpLoggingOptions_System_Collections_Generic_ISet_string___get_RequestHeaders_0__0(__thrown, __self_h);
    return ret;
}

SG_HNDL_NONNULL Microsoft_AspNetCore_HttpLogging_HttpLoggingOptions_System_Collections_Generic_ISet_string___get_ResponseHeaders_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h) {
    if (!_g_Microsoft_AspNetCore_HttpLogging._fp_Microsoft_AspNetCore_HttpLogging_HttpLoggingOptions_System_Collections_Generic_ISet_string___get_ResponseHeaders_0__0) {
        my_init();
    }
    SG_HNDL_NONNULL ret = _g_Microsoft_AspNetCore_HttpLogging._fp_Microsoft_AspNetCore_HttpLogging_HttpLoggingOptions_System_Collections_Generic_ISet_string___get_ResponseHeaders_0__0(__thrown, __self_h);
    return ret;
}

SG_HNDL_NONNULL Microsoft_AspNetCore_HttpLogging_HttpLoggingOptions_MediaTypeOptions__get_MediaTypeOptions_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h) {
    if (!_g_Microsoft_AspNetCore_HttpLogging._fp_Microsoft_AspNetCore_HttpLogging_HttpLoggingOptions_MediaTypeOptions__get_MediaTypeOptions_0__0) {
        my_init();
    }
    SG_HNDL_NONNULL ret = _g_Microsoft_AspNetCore_HttpLogging._fp_Microsoft_AspNetCore_HttpLogging_HttpLoggingOptions_MediaTypeOptions__get_MediaTypeOptions_0__0(__thrown, __self_h);
    return ret;
}

int32_t Microsoft_AspNetCore_HttpLogging_HttpLoggingOptions_i32__get_RequestBodyLogLimit_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h) {
    if (!_g_Microsoft_AspNetCore_HttpLogging._fp_Microsoft_AspNetCore_HttpLogging_HttpLoggingOptions_i32__get_RequestBodyLogLimit_0__0) {
        my_init();
    }
    int32_t ret = _g_Microsoft_AspNetCore_HttpLogging._fp_Microsoft_AspNetCore_HttpLogging_HttpLoggingOptions_i32__get_RequestBodyLogLimit_0__0(__thrown, __self_h);
    return ret;
}

void Microsoft_AspNetCore_HttpLogging_HttpLoggingOptions_void__set_RequestBodyLogLimit_0__1__i32(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h, int32_t value) {
    if (!_g_Microsoft_AspNetCore_HttpLogging._fp_Microsoft_AspNetCore_HttpLogging_HttpLoggingOptions_void__set_RequestBodyLogLimit_0__1__i32) {
        my_init();
    }
    _g_Microsoft_AspNetCore_HttpLogging._fp_Microsoft_AspNetCore_HttpLogging_HttpLoggingOptions_void__set_RequestBodyLogLimit_0__1__i32(__thrown, __self_h, value);
}

int32_t Microsoft_AspNetCore_HttpLogging_HttpLoggingOptions_i32__get_ResponseBodyLogLimit_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h) {
    if (!_g_Microsoft_AspNetCore_HttpLogging._fp_Microsoft_AspNetCore_HttpLogging_HttpLoggingOptions_i32__get_ResponseBodyLogLimit_0__0) {
        my_init();
    }
    int32_t ret = _g_Microsoft_AspNetCore_HttpLogging._fp_Microsoft_AspNetCore_HttpLogging_HttpLoggingOptions_i32__get_ResponseBodyLogLimit_0__0(__thrown, __self_h);
    return ret;
}

void Microsoft_AspNetCore_HttpLogging_HttpLoggingOptions_void__set_ResponseBodyLogLimit_0__1__i32(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h, int32_t value) {
    if (!_g_Microsoft_AspNetCore_HttpLogging._fp_Microsoft_AspNetCore_HttpLogging_HttpLoggingOptions_void__set_ResponseBodyLogLimit_0__1__i32) {
        my_init();
    }
    _g_Microsoft_AspNetCore_HttpLogging._fp_Microsoft_AspNetCore_HttpLogging_HttpLoggingOptions_void__set_ResponseBodyLogLimit_0__1__i32(__thrown, __self_h, value);
}

SG_HNDL_NONNULL Microsoft_AspNetCore_HttpLogging_HttpLoggingOptions_cast(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __h) {
    if (!_g_Microsoft_AspNetCore_HttpLogging._fp_Microsoft_AspNetCore_HttpLogging_HttpLoggingOptions_cast) {
        my_init();
    }
    SG_HNDL_NONNULL ret = _g_Microsoft_AspNetCore_HttpLogging._fp_Microsoft_AspNetCore_HttpLogging_HttpLoggingOptions_cast(__thrown, __h);
    return ret;
}

TYP Microsoft_AspNetCore_HttpLogging_MediaTypeOptions_get_type_handle(void) {
    if (!_g_Microsoft_AspNetCore_HttpLogging._fp_Microsoft_AspNetCore_HttpLogging_MediaTypeOptions_get_type_handle) {
        my_init();
    }
    TYP ret = _g_Microsoft_AspNetCore_HttpLogging._fp_Microsoft_AspNetCore_HttpLogging_MediaTypeOptions_get_type_handle();
    return ret;
}

void Microsoft_AspNetCore_HttpLogging_MediaTypeOptions_void__AddText_0__1__String(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h, SG_HNDL_NONNULL contentType) {
    if (!_g_Microsoft_AspNetCore_HttpLogging._fp_Microsoft_AspNetCore_HttpLogging_MediaTypeOptions_void__AddText_0__1__String) {
        my_init();
    }
    _g_Microsoft_AspNetCore_HttpLogging._fp_Microsoft_AspNetCore_HttpLogging_MediaTypeOptions_void__AddText_0__1__String(__thrown, __self_h, contentType);
}

void Microsoft_AspNetCore_HttpLogging_MediaTypeOptions_void__AddText_0__2__String_Encoding(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h, SG_HNDL_NONNULL contentType, SG_HNDL_NONNULL encoding) {
    if (!_g_Microsoft_AspNetCore_HttpLogging._fp_Microsoft_AspNetCore_HttpLogging_MediaTypeOptions_void__AddText_0__2__String_Encoding) {
        my_init();
    }
    _g_Microsoft_AspNetCore_HttpLogging._fp_Microsoft_AspNetCore_HttpLogging_MediaTypeOptions_void__AddText_0__2__String_Encoding(__thrown, __self_h, contentType, encoding);
}

void Microsoft_AspNetCore_HttpLogging_MediaTypeOptions_void__AddBinary_0__1__MediaTypeHeaderValue(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h, SG_HNDL_NONNULL mediaType) {
    if (!_g_Microsoft_AspNetCore_HttpLogging._fp_Microsoft_AspNetCore_HttpLogging_MediaTypeOptions_void__AddBinary_0__1__MediaTypeHeaderValue) {
        my_init();
    }
    _g_Microsoft_AspNetCore_HttpLogging._fp_Microsoft_AspNetCore_HttpLogging_MediaTypeOptions_void__AddBinary_0__1__MediaTypeHeaderValue(__thrown, __self_h, mediaType);
}

void Microsoft_AspNetCore_HttpLogging_MediaTypeOptions_void__AddBinary_0__1__String(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h, SG_HNDL_NONNULL contentType) {
    if (!_g_Microsoft_AspNetCore_HttpLogging._fp_Microsoft_AspNetCore_HttpLogging_MediaTypeOptions_void__AddBinary_0__1__String) {
        my_init();
    }
    _g_Microsoft_AspNetCore_HttpLogging._fp_Microsoft_AspNetCore_HttpLogging_MediaTypeOptions_void__AddBinary_0__1__String(__thrown, __self_h, contentType);
}

void Microsoft_AspNetCore_HttpLogging_MediaTypeOptions_void__Clear_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h) {
    if (!_g_Microsoft_AspNetCore_HttpLogging._fp_Microsoft_AspNetCore_HttpLogging_MediaTypeOptions_void__Clear_0__0) {
        my_init();
    }
    _g_Microsoft_AspNetCore_HttpLogging._fp_Microsoft_AspNetCore_HttpLogging_MediaTypeOptions_void__Clear_0__0(__thrown, __self_h);
}

SG_HNDL_NONNULL Microsoft_AspNetCore_HttpLogging_MediaTypeOptions_cast(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __h) {
    if (!_g_Microsoft_AspNetCore_HttpLogging._fp_Microsoft_AspNetCore_HttpLogging_MediaTypeOptions_cast) {
        my_init();
    }
    SG_HNDL_NONNULL ret = _g_Microsoft_AspNetCore_HttpLogging._fp_Microsoft_AspNetCore_HttpLogging_MediaTypeOptions_cast(__thrown, __h);
    return ret;
}

TYP Microsoft_AspNetCore_HttpLogging_W3CLoggerOptions_get_type_handle(void) {
    if (!_g_Microsoft_AspNetCore_HttpLogging._fp_Microsoft_AspNetCore_HttpLogging_W3CLoggerOptions_get_type_handle) {
        my_init();
    }
    TYP ret = _g_Microsoft_AspNetCore_HttpLogging._fp_Microsoft_AspNetCore_HttpLogging_W3CLoggerOptions_get_type_handle();
    return ret;
}

SG_HNDL_NONNULL Microsoft_AspNetCore_HttpLogging_W3CLoggerOptions_ctor_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown) {
    if (!_g_Microsoft_AspNetCore_HttpLogging._fp_Microsoft_AspNetCore_HttpLogging_W3CLoggerOptions_ctor_0__0) {
        my_init();
    }
    SG_HNDL_NONNULL ret = _g_Microsoft_AspNetCore_HttpLogging._fp_Microsoft_AspNetCore_HttpLogging_W3CLoggerOptions_ctor_0__0(__thrown);
    return ret;
}

SG_HNDL_NULLABLE Microsoft_AspNetCore_HttpLogging_W3CLoggerOptions_System_Nullable_i32___get_FileSizeLimit_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h) {
    if (!_g_Microsoft_AspNetCore_HttpLogging._fp_Microsoft_AspNetCore_HttpLogging_W3CLoggerOptions_System_Nullable_i32___get_FileSizeLimit_0__0) {
        my_init();
    }
    SG_HNDL_NULLABLE ret = _g_Microsoft_AspNetCore_HttpLogging._fp_Microsoft_AspNetCore_HttpLogging_W3CLoggerOptions_System_Nullable_i32___get_FileSizeLimit_0__0(__thrown, __self_h);
    return ret;
}

void Microsoft_AspNetCore_HttpLogging_W3CLoggerOptions_void__set_FileSizeLimit_0__1__System_Nullable_i32_(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h, SG_HNDL_NULLABLE value) {
    if (!_g_Microsoft_AspNetCore_HttpLogging._fp_Microsoft_AspNetCore_HttpLogging_W3CLoggerOptions_void__set_FileSizeLimit_0__1__System_Nullable_i32_) {
        my_init();
    }
    _g_Microsoft_AspNetCore_HttpLogging._fp_Microsoft_AspNetCore_HttpLogging_W3CLoggerOptions_void__set_FileSizeLimit_0__1__System_Nullable_i32_(__thrown, __self_h, value);
}

SG_HNDL_NULLABLE Microsoft_AspNetCore_HttpLogging_W3CLoggerOptions_System_Nullable_i32___get_RetainedFileCountLimit_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h) {
    if (!_g_Microsoft_AspNetCore_HttpLogging._fp_Microsoft_AspNetCore_HttpLogging_W3CLoggerOptions_System_Nullable_i32___get_RetainedFileCountLimit_0__0) {
        my_init();
    }
    SG_HNDL_NULLABLE ret = _g_Microsoft_AspNetCore_HttpLogging._fp_Microsoft_AspNetCore_HttpLogging_W3CLoggerOptions_System_Nullable_i32___get_RetainedFileCountLimit_0__0(__thrown, __self_h);
    return ret;
}

void Microsoft_AspNetCore_HttpLogging_W3CLoggerOptions_void__set_RetainedFileCountLimit_0__1__System_Nullable_i32_(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h, SG_HNDL_NULLABLE value) {
    if (!_g_Microsoft_AspNetCore_HttpLogging._fp_Microsoft_AspNetCore_HttpLogging_W3CLoggerOptions_void__set_RetainedFileCountLimit_0__1__System_Nullable_i32_) {
        my_init();
    }
    _g_Microsoft_AspNetCore_HttpLogging._fp_Microsoft_AspNetCore_HttpLogging_W3CLoggerOptions_void__set_RetainedFileCountLimit_0__1__System_Nullable_i32_(__thrown, __self_h, value);
}

SG_HNDL_NONNULL Microsoft_AspNetCore_HttpLogging_W3CLoggerOptions_String__get_FileName_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h) {
    if (!_g_Microsoft_AspNetCore_HttpLogging._fp_Microsoft_AspNetCore_HttpLogging_W3CLoggerOptions_String__get_FileName_0__0) {
        my_init();
    }
    SG_HNDL_NONNULL ret = _g_Microsoft_AspNetCore_HttpLogging._fp_Microsoft_AspNetCore_HttpLogging_W3CLoggerOptions_String__get_FileName_0__0(__thrown, __self_h);
    return ret;
}

void Microsoft_AspNetCore_HttpLogging_W3CLoggerOptions_void__set_FileName_0__1__String(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h, SG_HNDL_NONNULL value) {
    if (!_g_Microsoft_AspNetCore_HttpLogging._fp_Microsoft_AspNetCore_HttpLogging_W3CLoggerOptions_void__set_FileName_0__1__String) {
        my_init();
    }
    _g_Microsoft_AspNetCore_HttpLogging._fp_Microsoft_AspNetCore_HttpLogging_W3CLoggerOptions_void__set_FileName_0__1__String(__thrown, __self_h, value);
}

SG_HNDL_NONNULL Microsoft_AspNetCore_HttpLogging_W3CLoggerOptions_String__get_LogDirectory_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h) {
    if (!_g_Microsoft_AspNetCore_HttpLogging._fp_Microsoft_AspNetCore_HttpLogging_W3CLoggerOptions_String__get_LogDirectory_0__0) {
        my_init();
    }
    SG_HNDL_NONNULL ret = _g_Microsoft_AspNetCore_HttpLogging._fp_Microsoft_AspNetCore_HttpLogging_W3CLoggerOptions_String__get_LogDirectory_0__0(__thrown, __self_h);
    return ret;
}

void Microsoft_AspNetCore_HttpLogging_W3CLoggerOptions_void__set_LogDirectory_0__1__String(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h, SG_HNDL_NONNULL value) {
    if (!_g_Microsoft_AspNetCore_HttpLogging._fp_Microsoft_AspNetCore_HttpLogging_W3CLoggerOptions_void__set_LogDirectory_0__1__String) {
        my_init();
    }
    _g_Microsoft_AspNetCore_HttpLogging._fp_Microsoft_AspNetCore_HttpLogging_W3CLoggerOptions_void__set_LogDirectory_0__1__String(__thrown, __self_h, value);
}

SG_HNDL_NONNULL Microsoft_AspNetCore_HttpLogging_W3CLoggerOptions_TimeSpan__get_FlushInterval_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h) {
    if (!_g_Microsoft_AspNetCore_HttpLogging._fp_Microsoft_AspNetCore_HttpLogging_W3CLoggerOptions_TimeSpan__get_FlushInterval_0__0) {
        my_init();
    }
    SG_HNDL_NONNULL ret = _g_Microsoft_AspNetCore_HttpLogging._fp_Microsoft_AspNetCore_HttpLogging_W3CLoggerOptions_TimeSpan__get_FlushInterval_0__0(__thrown, __self_h);
    return ret;
}

void Microsoft_AspNetCore_HttpLogging_W3CLoggerOptions_void__set_FlushInterval_0__1__TimeSpan(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h, SG_HNDL_NONNULL value) {
    if (!_g_Microsoft_AspNetCore_HttpLogging._fp_Microsoft_AspNetCore_HttpLogging_W3CLoggerOptions_void__set_FlushInterval_0__1__TimeSpan) {
        my_init();
    }
    _g_Microsoft_AspNetCore_HttpLogging._fp_Microsoft_AspNetCore_HttpLogging_W3CLoggerOptions_void__set_FlushInterval_0__1__TimeSpan(__thrown, __self_h, value);
}

int64_t Microsoft_AspNetCore_HttpLogging_W3CLoggerOptions_W3CLoggingFields__get_LoggingFields_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h) {
    if (!_g_Microsoft_AspNetCore_HttpLogging._fp_Microsoft_AspNetCore_HttpLogging_W3CLoggerOptions_W3CLoggingFields__get_LoggingFields_0__0) {
        my_init();
    }
    int64_t ret = _g_Microsoft_AspNetCore_HttpLogging._fp_Microsoft_AspNetCore_HttpLogging_W3CLoggerOptions_W3CLoggingFields__get_LoggingFields_0__0(__thrown, __self_h);
    return ret;
}

void Microsoft_AspNetCore_HttpLogging_W3CLoggerOptions_void__set_LoggingFields_0__1__W3CLoggingFields(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h, int64_t value) {
    if (!_g_Microsoft_AspNetCore_HttpLogging._fp_Microsoft_AspNetCore_HttpLogging_W3CLoggerOptions_void__set_LoggingFields_0__1__W3CLoggingFields) {
        my_init();
    }
    _g_Microsoft_AspNetCore_HttpLogging._fp_Microsoft_AspNetCore_HttpLogging_W3CLoggerOptions_void__set_LoggingFields_0__1__W3CLoggingFields(__thrown, __self_h, value);
}

SG_HNDL_NONNULL Microsoft_AspNetCore_HttpLogging_W3CLoggerOptions_cast(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __h) {
    if (!_g_Microsoft_AspNetCore_HttpLogging._fp_Microsoft_AspNetCore_HttpLogging_W3CLoggerOptions_cast) {
        my_init();
    }
    SG_HNDL_NONNULL ret = _g_Microsoft_AspNetCore_HttpLogging._fp_Microsoft_AspNetCore_HttpLogging_W3CLoggerOptions_cast(__thrown, __h);
    return ret;
}

TYP Microsoft_AspNetCore_HttpLogging_W3CLoggingFields_get_type_handle(void) {
    if (!_g_Microsoft_AspNetCore_HttpLogging._fp_Microsoft_AspNetCore_HttpLogging_W3CLoggingFields_get_type_handle) {
        my_init();
    }
    TYP ret = _g_Microsoft_AspNetCore_HttpLogging._fp_Microsoft_AspNetCore_HttpLogging_W3CLoggingFields_get_type_handle();
    return ret;
}

int64_t Microsoft_AspNetCore_HttpLogging_W3CLoggingFields_get_None(void) {
    if (!_g_Microsoft_AspNetCore_HttpLogging._fp_Microsoft_AspNetCore_HttpLogging_W3CLoggingFields_get_None) {
        my_init();
    }
    int64_t ret = _g_Microsoft_AspNetCore_HttpLogging._fp_Microsoft_AspNetCore_HttpLogging_W3CLoggingFields_get_None();
    return ret;
}

int64_t Microsoft_AspNetCore_HttpLogging_W3CLoggingFields_get_Date(void) {
    if (!_g_Microsoft_AspNetCore_HttpLogging._fp_Microsoft_AspNetCore_HttpLogging_W3CLoggingFields_get_Date) {
        my_init();
    }
    int64_t ret = _g_Microsoft_AspNetCore_HttpLogging._fp_Microsoft_AspNetCore_HttpLogging_W3CLoggingFields_get_Date();
    return ret;
}

int64_t Microsoft_AspNetCore_HttpLogging_W3CLoggingFields_get_Time(void) {
    if (!_g_Microsoft_AspNetCore_HttpLogging._fp_Microsoft_AspNetCore_HttpLogging_W3CLoggingFields_get_Time) {
        my_init();
    }
    int64_t ret = _g_Microsoft_AspNetCore_HttpLogging._fp_Microsoft_AspNetCore_HttpLogging_W3CLoggingFields_get_Time();
    return ret;
}

int64_t Microsoft_AspNetCore_HttpLogging_W3CLoggingFields_get_ClientIpAddress(void) {
    if (!_g_Microsoft_AspNetCore_HttpLogging._fp_Microsoft_AspNetCore_HttpLogging_W3CLoggingFields_get_ClientIpAddress) {
        my_init();
    }
    int64_t ret = _g_Microsoft_AspNetCore_HttpLogging._fp_Microsoft_AspNetCore_HttpLogging_W3CLoggingFields_get_ClientIpAddress();
    return ret;
}

int64_t Microsoft_AspNetCore_HttpLogging_W3CLoggingFields_get_UserName(void) {
    if (!_g_Microsoft_AspNetCore_HttpLogging._fp_Microsoft_AspNetCore_HttpLogging_W3CLoggingFields_get_UserName) {
        my_init();
    }
    int64_t ret = _g_Microsoft_AspNetCore_HttpLogging._fp_Microsoft_AspNetCore_HttpLogging_W3CLoggingFields_get_UserName();
    return ret;
}

int64_t Microsoft_AspNetCore_HttpLogging_W3CLoggingFields_get_ServerName(void) {
    if (!_g_Microsoft_AspNetCore_HttpLogging._fp_Microsoft_AspNetCore_HttpLogging_W3CLoggingFields_get_ServerName) {
        my_init();
    }
    int64_t ret = _g_Microsoft_AspNetCore_HttpLogging._fp_Microsoft_AspNetCore_HttpLogging_W3CLoggingFields_get_ServerName();
    return ret;
}

int64_t Microsoft_AspNetCore_HttpLogging_W3CLoggingFields_get_ServerIpAddress(void) {
    if (!_g_Microsoft_AspNetCore_HttpLogging._fp_Microsoft_AspNetCore_HttpLogging_W3CLoggingFields_get_ServerIpAddress) {
        my_init();
    }
    int64_t ret = _g_Microsoft_AspNetCore_HttpLogging._fp_Microsoft_AspNetCore_HttpLogging_W3CLoggingFields_get_ServerIpAddress();
    return ret;
}

int64_t Microsoft_AspNetCore_HttpLogging_W3CLoggingFields_get_ServerPort(void) {
    if (!_g_Microsoft_AspNetCore_HttpLogging._fp_Microsoft_AspNetCore_HttpLogging_W3CLoggingFields_get_ServerPort) {
        my_init();
    }
    int64_t ret = _g_Microsoft_AspNetCore_HttpLogging._fp_Microsoft_AspNetCore_HttpLogging_W3CLoggingFields_get_ServerPort();
    return ret;
}

int64_t Microsoft_AspNetCore_HttpLogging_W3CLoggingFields_get_Method(void) {
    if (!_g_Microsoft_AspNetCore_HttpLogging._fp_Microsoft_AspNetCore_HttpLogging_W3CLoggingFields_get_Method) {
        my_init();
    }
    int64_t ret = _g_Microsoft_AspNetCore_HttpLogging._fp_Microsoft_AspNetCore_HttpLogging_W3CLoggingFields_get_Method();
    return ret;
}

int64_t Microsoft_AspNetCore_HttpLogging_W3CLoggingFields_get_UriStem(void) {
    if (!_g_Microsoft_AspNetCore_HttpLogging._fp_Microsoft_AspNetCore_HttpLogging_W3CLoggingFields_get_UriStem) {
        my_init();
    }
    int64_t ret = _g_Microsoft_AspNetCore_HttpLogging._fp_Microsoft_AspNetCore_HttpLogging_W3CLoggingFields_get_UriStem();
    return ret;
}

int64_t Microsoft_AspNetCore_HttpLogging_W3CLoggingFields_get_UriQuery(void) {
    if (!_g_Microsoft_AspNetCore_HttpLogging._fp_Microsoft_AspNetCore_HttpLogging_W3CLoggingFields_get_UriQuery) {
        my_init();
    }
    int64_t ret = _g_Microsoft_AspNetCore_HttpLogging._fp_Microsoft_AspNetCore_HttpLogging_W3CLoggingFields_get_UriQuery();
    return ret;
}

int64_t Microsoft_AspNetCore_HttpLogging_W3CLoggingFields_get_ProtocolStatus(void) {
    if (!_g_Microsoft_AspNetCore_HttpLogging._fp_Microsoft_AspNetCore_HttpLogging_W3CLoggingFields_get_ProtocolStatus) {
        my_init();
    }
    int64_t ret = _g_Microsoft_AspNetCore_HttpLogging._fp_Microsoft_AspNetCore_HttpLogging_W3CLoggingFields_get_ProtocolStatus();
    return ret;
}

int64_t Microsoft_AspNetCore_HttpLogging_W3CLoggingFields_get_TimeTaken(void) {
    if (!_g_Microsoft_AspNetCore_HttpLogging._fp_Microsoft_AspNetCore_HttpLogging_W3CLoggingFields_get_TimeTaken) {
        my_init();
    }
    int64_t ret = _g_Microsoft_AspNetCore_HttpLogging._fp_Microsoft_AspNetCore_HttpLogging_W3CLoggingFields_get_TimeTaken();
    return ret;
}

int64_t Microsoft_AspNetCore_HttpLogging_W3CLoggingFields_get_ProtocolVersion(void) {
    if (!_g_Microsoft_AspNetCore_HttpLogging._fp_Microsoft_AspNetCore_HttpLogging_W3CLoggingFields_get_ProtocolVersion) {
        my_init();
    }
    int64_t ret = _g_Microsoft_AspNetCore_HttpLogging._fp_Microsoft_AspNetCore_HttpLogging_W3CLoggingFields_get_ProtocolVersion();
    return ret;
}

int64_t Microsoft_AspNetCore_HttpLogging_W3CLoggingFields_get_Host(void) {
    if (!_g_Microsoft_AspNetCore_HttpLogging._fp_Microsoft_AspNetCore_HttpLogging_W3CLoggingFields_get_Host) {
        my_init();
    }
    int64_t ret = _g_Microsoft_AspNetCore_HttpLogging._fp_Microsoft_AspNetCore_HttpLogging_W3CLoggingFields_get_Host();
    return ret;
}

int64_t Microsoft_AspNetCore_HttpLogging_W3CLoggingFields_get_UserAgent(void) {
    if (!_g_Microsoft_AspNetCore_HttpLogging._fp_Microsoft_AspNetCore_HttpLogging_W3CLoggingFields_get_UserAgent) {
        my_init();
    }
    int64_t ret = _g_Microsoft_AspNetCore_HttpLogging._fp_Microsoft_AspNetCore_HttpLogging_W3CLoggingFields_get_UserAgent();
    return ret;
}

int64_t Microsoft_AspNetCore_HttpLogging_W3CLoggingFields_get_Cookie(void) {
    if (!_g_Microsoft_AspNetCore_HttpLogging._fp_Microsoft_AspNetCore_HttpLogging_W3CLoggingFields_get_Cookie) {
        my_init();
    }
    int64_t ret = _g_Microsoft_AspNetCore_HttpLogging._fp_Microsoft_AspNetCore_HttpLogging_W3CLoggingFields_get_Cookie();
    return ret;
}

int64_t Microsoft_AspNetCore_HttpLogging_W3CLoggingFields_get_Referer(void) {
    if (!_g_Microsoft_AspNetCore_HttpLogging._fp_Microsoft_AspNetCore_HttpLogging_W3CLoggingFields_get_Referer) {
        my_init();
    }
    int64_t ret = _g_Microsoft_AspNetCore_HttpLogging._fp_Microsoft_AspNetCore_HttpLogging_W3CLoggingFields_get_Referer();
    return ret;
}

int64_t Microsoft_AspNetCore_HttpLogging_W3CLoggingFields_get_ConnectionInfoFields(void) {
    if (!_g_Microsoft_AspNetCore_HttpLogging._fp_Microsoft_AspNetCore_HttpLogging_W3CLoggingFields_get_ConnectionInfoFields) {
        my_init();
    }
    int64_t ret = _g_Microsoft_AspNetCore_HttpLogging._fp_Microsoft_AspNetCore_HttpLogging_W3CLoggingFields_get_ConnectionInfoFields();
    return ret;
}

int64_t Microsoft_AspNetCore_HttpLogging_W3CLoggingFields_get_RequestHeaders(void) {
    if (!_g_Microsoft_AspNetCore_HttpLogging._fp_Microsoft_AspNetCore_HttpLogging_W3CLoggingFields_get_RequestHeaders) {
        my_init();
    }
    int64_t ret = _g_Microsoft_AspNetCore_HttpLogging._fp_Microsoft_AspNetCore_HttpLogging_W3CLoggingFields_get_RequestHeaders();
    return ret;
}

int64_t Microsoft_AspNetCore_HttpLogging_W3CLoggingFields_get_Request(void) {
    if (!_g_Microsoft_AspNetCore_HttpLogging._fp_Microsoft_AspNetCore_HttpLogging_W3CLoggingFields_get_Request) {
        my_init();
    }
    int64_t ret = _g_Microsoft_AspNetCore_HttpLogging._fp_Microsoft_AspNetCore_HttpLogging_W3CLoggingFields_get_Request();
    return ret;
}

int64_t Microsoft_AspNetCore_HttpLogging_W3CLoggingFields_get_All(void) {
    if (!_g_Microsoft_AspNetCore_HttpLogging._fp_Microsoft_AspNetCore_HttpLogging_W3CLoggingFields_get_All) {
        my_init();
    }
    int64_t ret = _g_Microsoft_AspNetCore_HttpLogging._fp_Microsoft_AspNetCore_HttpLogging_W3CLoggingFields_get_All();
    return ret;
}

SG_HNDL_NONNULL Microsoft_Extensions_DependencyInjection_HttpLoggingServicesExtensions_IServiceCollection__AddHttpLogging_0__2__IServiceCollection_System_Action_Microsoft_AspNetCore_HttpLogging_HttpLoggingOptions_(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL services, SG_HNDL_NONNULL configureOptions) {
    if (!_g_Microsoft_AspNetCore_HttpLogging._fp_Microsoft_Extensions_DependencyInjection_HttpLoggingServicesExtensions_IServiceCollection__AddHttpLogging_0__2__IServiceCollection_System_Action_Microsoft_AspNetCore_HttpLogging_HttpLoggingOptions_) {
        my_init();
    }
    SG_HNDL_NONNULL ret = _g_Microsoft_AspNetCore_HttpLogging._fp_Microsoft_Extensions_DependencyInjection_HttpLoggingServicesExtensions_IServiceCollection__AddHttpLogging_0__2__IServiceCollection_System_Action_Microsoft_AspNetCore_HttpLogging_HttpLoggingOptions_(__thrown, services, configureOptions);
    return ret;
}

SG_HNDL_NONNULL Microsoft_Extensions_DependencyInjection_HttpLoggingServicesExtensions_IServiceCollection__AddW3CLogging_0__2__IServiceCollection_System_Action_Microsoft_AspNetCore_HttpLogging_W3CLoggerOptions_(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL services, SG_HNDL_NONNULL configureOptions) {
    if (!_g_Microsoft_AspNetCore_HttpLogging._fp_Microsoft_Extensions_DependencyInjection_HttpLoggingServicesExtensions_IServiceCollection__AddW3CLogging_0__2__IServiceCollection_System_Action_Microsoft_AspNetCore_HttpLogging_W3CLoggerOptions_) {
        my_init();
    }
    SG_HNDL_NONNULL ret = _g_Microsoft_AspNetCore_HttpLogging._fp_Microsoft_Extensions_DependencyInjection_HttpLoggingServicesExtensions_IServiceCollection__AddW3CLogging_0__2__IServiceCollection_System_Action_Microsoft_AspNetCore_HttpLogging_W3CLoggerOptions_(__thrown, services, configureOptions);
    return ret;
}

