// this file is automatically generated with SourceGear Bridge

#include <stdint.h>

#include "Microsoft_AspNetCore_Diagnostics_Abstractions.h"

extern void (*_sg_resolve_jumptable)(const char*, int, void*);

struct {
    TYP (* _Nonnull  _fp_Microsoft_AspNetCore_Diagnostics_CompilationFailure_get_type_handle)(void);
    SG_HNDL_NONNULL (* _Nonnull  _fp_Microsoft_AspNetCore_Diagnostics_CompilationFailure_ctor_0__4__String_String_String_System_Collections_Generic_IEnumerable_Microsoft_AspNetCore_Diagnostics_DiagnosticMessage_)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NULLABLE sourceFilePath, SG_HNDL_NULLABLE sourceFileContent, SG_HNDL_NULLABLE compiledContent, SG_HNDL_NULLABLE messages);
    SG_HNDL_NONNULL (* _Nonnull  _fp_Microsoft_AspNetCore_Diagnostics_CompilationFailure_ctor_0__5__String_String_String_System_Collections_Generic_IEnumerable_Microsoft_AspNetCore_Diagnostics_DiagnosticMessage__String)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NULLABLE sourceFilePath, SG_HNDL_NULLABLE sourceFileContent, SG_HNDL_NULLABLE compiledContent, SG_HNDL_NULLABLE messages, SG_HNDL_NULLABLE failureSummary);
    SG_HNDL_NULLABLE (* _Nonnull  _fp_Microsoft_AspNetCore_Diagnostics_CompilationFailure_String__get_SourceFilePath_0__0)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h);
    SG_HNDL_NULLABLE (* _Nonnull  _fp_Microsoft_AspNetCore_Diagnostics_CompilationFailure_String__get_SourceFileContent_0__0)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h);
    SG_HNDL_NULLABLE (* _Nonnull  _fp_Microsoft_AspNetCore_Diagnostics_CompilationFailure_String__get_CompiledContent_0__0)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h);
    SG_HNDL_NULLABLE (* _Nonnull  _fp_Microsoft_AspNetCore_Diagnostics_CompilationFailure_System_Collections_Generic_IEnumerable_Microsoft_AspNetCore_Diagnostics_DiagnosticMessage___get_Messages_0__0)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h);
    SG_HNDL_NULLABLE (* _Nonnull  _fp_Microsoft_AspNetCore_Diagnostics_CompilationFailure_String__get_FailureSummary_0__0)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h);
    SG_HNDL_NONNULL (* _Nonnull  _fp_Microsoft_AspNetCore_Diagnostics_CompilationFailure_cast)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __h);
    TYP (* _Nonnull  _fp_Microsoft_AspNetCore_Diagnostics_DiagnosticMessage_get_type_handle)(void);
    SG_HNDL_NONNULL (* _Nonnull  _fp_Microsoft_AspNetCore_Diagnostics_DiagnosticMessage_ctor_0__7__String_String_String_i32_i32_i32_i32)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NULLABLE message, SG_HNDL_NULLABLE formattedMessage, SG_HNDL_NULLABLE filePath, int32_t startLine, int32_t startColumn, int32_t endLine, int32_t endColumn);
    SG_HNDL_NULLABLE (* _Nonnull  _fp_Microsoft_AspNetCore_Diagnostics_DiagnosticMessage_String__get_SourceFilePath_0__0)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h);
    SG_HNDL_NULLABLE (* _Nonnull  _fp_Microsoft_AspNetCore_Diagnostics_DiagnosticMessage_String__get_Message_0__0)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h);
    int32_t (* _Nonnull  _fp_Microsoft_AspNetCore_Diagnostics_DiagnosticMessage_i32__get_StartLine_0__0)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h);
    int32_t (* _Nonnull  _fp_Microsoft_AspNetCore_Diagnostics_DiagnosticMessage_i32__get_StartColumn_0__0)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h);
    int32_t (* _Nonnull  _fp_Microsoft_AspNetCore_Diagnostics_DiagnosticMessage_i32__get_EndLine_0__0)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h);
    int32_t (* _Nonnull  _fp_Microsoft_AspNetCore_Diagnostics_DiagnosticMessage_i32__get_EndColumn_0__0)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h);
    SG_HNDL_NULLABLE (* _Nonnull  _fp_Microsoft_AspNetCore_Diagnostics_DiagnosticMessage_String__get_FormattedMessage_0__0)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h);
    SG_HNDL_NONNULL (* _Nonnull  _fp_Microsoft_AspNetCore_Diagnostics_DiagnosticMessage_cast)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __h);
    TYP (* _Nonnull  _fp_Microsoft_AspNetCore_Diagnostics_ErrorContext_get_type_handle)(void);
    SG_HNDL_NONNULL (* _Nonnull  _fp_Microsoft_AspNetCore_Diagnostics_ErrorContext_ctor_0__2__HttpContext_Exception)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL httpContext, SG_HNDL_NONNULL exception);
    SG_HNDL_NONNULL (* _Nonnull  _fp_Microsoft_AspNetCore_Diagnostics_ErrorContext_HttpContext__get_HttpContext_0__0)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h);
    SG_HNDL_NONNULL (* _Nonnull  _fp_Microsoft_AspNetCore_Diagnostics_ErrorContext_Exception__get_Exception_0__0)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h);
    SG_HNDL_NONNULL (* _Nonnull  _fp_Microsoft_AspNetCore_Diagnostics_ErrorContext_cast)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __h);
    TYP (* _Nonnull  _fp_Microsoft_AspNetCore_Diagnostics_ICompilationException_get_type_handle)(void);
    SG_HNDL_NULLABLE (* _Nonnull  _fp_Microsoft_AspNetCore_Diagnostics_ICompilationException_System_Collections_Generic_IEnumerable_Microsoft_AspNetCore_Diagnostics_CompilationFailure___get_CompilationFailures_0__0)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h);
    SG_HNDL_NONNULL (* _Nonnull  _fp_Microsoft_AspNetCore_Diagnostics_ICompilationException_cast)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __h);
    SG_HNDL_NONNULL (* _Nonnull  _fp_Microsoft_AspNetCore_Diagnostics_ICompilationException_create)(SG_HNDL_NULLABLE * _Nonnull __thrown, void (* _Nullable __deinit)(const void* _Nonnull __pdata));
    TYP (* _Nonnull  _fp_Microsoft_AspNetCore_Diagnostics_IDeveloperPageExceptionFilter_get_type_handle)(void);
    SG_HNDL_NONNULL (* _Nonnull  _fp_Microsoft_AspNetCore_Diagnostics_IDeveloperPageExceptionFilter_Task__HandleExceptionAsync_0__2__ErrorContext_System_Func_Microsoft_AspNetCore_Diagnostics_ErrorContext_Task_)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h, SG_HNDL_NONNULL errorContext, SG_HNDL_NONNULL next);
    SG_HNDL_NONNULL (* _Nonnull  _fp_Microsoft_AspNetCore_Diagnostics_IDeveloperPageExceptionFilter_cast)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __h);
    SG_HNDL_NONNULL (* _Nonnull  _fp_Microsoft_AspNetCore_Diagnostics_IDeveloperPageExceptionFilter_create)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL (* _Nonnull  __cb_Microsoft_AspNetCore_Diagnostics_IDeveloperPageExceptionFilter_Task__HandleExceptionAsync_0__2__ErrorContext_System_Func_Microsoft_AspNetCore_Diagnostics_ErrorContext_Task_)(const void* _Nonnull __pdata, SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL errorContext, SG_HNDL_NONNULL next), const void* _Nonnull __pdata_Microsoft_AspNetCore_Diagnostics_IDeveloperPageExceptionFilter_Task__HandleExceptionAsync_0__2__ErrorContext_System_Func_Microsoft_AspNetCore_Diagnostics_ErrorContext_Task_, void (* _Nullable __deinit)(const void* _Nonnull __pdata));
    TYP (* _Nonnull  _fp_Microsoft_AspNetCore_Diagnostics_IExceptionHandlerFeature_get_type_handle)(void);
    SG_HNDL_NONNULL (* _Nonnull  _fp_Microsoft_AspNetCore_Diagnostics_IExceptionHandlerFeature_Exception__get_Error_0__0)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h);
    SG_HNDL_NONNULL (* _Nonnull  _fp_Microsoft_AspNetCore_Diagnostics_IExceptionHandlerFeature_String__get_Path_0__0)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h);
    SG_HNDL_NULLABLE (* _Nonnull  _fp_Microsoft_AspNetCore_Diagnostics_IExceptionHandlerFeature_Endpoint__get_Endpoint_0__0)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h);
    SG_HNDL_NULLABLE (* _Nonnull  _fp_Microsoft_AspNetCore_Diagnostics_IExceptionHandlerFeature_RouteValueDictionary__get_RouteValues_0__0)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h);
    SG_HNDL_NONNULL (* _Nonnull  _fp_Microsoft_AspNetCore_Diagnostics_IExceptionHandlerFeature_cast)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __h);
    SG_HNDL_NONNULL (* _Nonnull  _fp_Microsoft_AspNetCore_Diagnostics_IExceptionHandlerFeature_create)(SG_HNDL_NULLABLE * _Nonnull __thrown, void (* _Nullable __deinit)(const void* _Nonnull __pdata));
    TYP (* _Nonnull  _fp_Microsoft_AspNetCore_Diagnostics_IExceptionHandlerPathFeature_get_type_handle)(void);
    SG_HNDL_NONNULL (* _Nonnull  _fp_Microsoft_AspNetCore_Diagnostics_IExceptionHandlerPathFeature_String__get_Path_0__0)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h);
    SG_HNDL_NONNULL (* _Nonnull  _fp_Microsoft_AspNetCore_Diagnostics_IExceptionHandlerPathFeature_cast)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __h);
    SG_HNDL_NONNULL (* _Nonnull  _fp_Microsoft_AspNetCore_Diagnostics_IExceptionHandlerPathFeature_create)(SG_HNDL_NULLABLE * _Nonnull __thrown, void (* _Nullable __deinit)(const void* _Nonnull __pdata));
    TYP (* _Nonnull  _fp_Microsoft_AspNetCore_Diagnostics_IStatusCodePagesFeature_get_type_handle)(void);
    int32_t (* _Nonnull  _fp_Microsoft_AspNetCore_Diagnostics_IStatusCodePagesFeature_bool__get_Enabled_0__0)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h);
    void (* _Nonnull  _fp_Microsoft_AspNetCore_Diagnostics_IStatusCodePagesFeature_void__set_Enabled_0__1__bool)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h, int32_t value);
    SG_HNDL_NONNULL (* _Nonnull  _fp_Microsoft_AspNetCore_Diagnostics_IStatusCodePagesFeature_cast)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __h);
    SG_HNDL_NONNULL (* _Nonnull  _fp_Microsoft_AspNetCore_Diagnostics_IStatusCodePagesFeature_create)(SG_HNDL_NULLABLE * _Nonnull __thrown, void (* _Nullable __deinit)(const void* _Nonnull __pdata));
    TYP (* _Nonnull  _fp_Microsoft_AspNetCore_Diagnostics_IStatusCodeReExecuteFeature_get_type_handle)(void);
    SG_HNDL_NONNULL (* _Nonnull  _fp_Microsoft_AspNetCore_Diagnostics_IStatusCodeReExecuteFeature_String__get_OriginalPathBase_0__0)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h);
    void (* _Nonnull  _fp_Microsoft_AspNetCore_Diagnostics_IStatusCodeReExecuteFeature_void__set_OriginalPathBase_0__1__String)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h, SG_HNDL_NONNULL value);
    SG_HNDL_NONNULL (* _Nonnull  _fp_Microsoft_AspNetCore_Diagnostics_IStatusCodeReExecuteFeature_String__get_OriginalPath_0__0)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h);
    void (* _Nonnull  _fp_Microsoft_AspNetCore_Diagnostics_IStatusCodeReExecuteFeature_void__set_OriginalPath_0__1__String)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h, SG_HNDL_NONNULL value);
    SG_HNDL_NULLABLE (* _Nonnull  _fp_Microsoft_AspNetCore_Diagnostics_IStatusCodeReExecuteFeature_String__get_OriginalQueryString_0__0)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h);
    void (* _Nonnull  _fp_Microsoft_AspNetCore_Diagnostics_IStatusCodeReExecuteFeature_void__set_OriginalQueryString_0__1__String)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h, SG_HNDL_NULLABLE value);
    SG_HNDL_NONNULL (* _Nonnull  _fp_Microsoft_AspNetCore_Diagnostics_IStatusCodeReExecuteFeature_cast)(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __h);
    SG_HNDL_NONNULL (* _Nonnull  _fp_Microsoft_AspNetCore_Diagnostics_IStatusCodeReExecuteFeature_create)(SG_HNDL_NULLABLE * _Nonnull __thrown, void (* _Nullable __deinit)(const void* _Nonnull __pdata));
} _g_Microsoft_AspNetCore_Diagnostics_Abstractions;

static void my_init() {
    _sg_resolve_jumptable("Microsoft_AspNetCore_Diagnostics_Abstractions", 45, &_g_Microsoft_AspNetCore_Diagnostics_Abstractions);
}

TYP Microsoft_AspNetCore_Diagnostics_CompilationFailure_get_type_handle(void) {
    if (!_g_Microsoft_AspNetCore_Diagnostics_Abstractions._fp_Microsoft_AspNetCore_Diagnostics_CompilationFailure_get_type_handle) {
        my_init();
    }
    TYP ret = _g_Microsoft_AspNetCore_Diagnostics_Abstractions._fp_Microsoft_AspNetCore_Diagnostics_CompilationFailure_get_type_handle();
    return ret;
}

SG_HNDL_NONNULL Microsoft_AspNetCore_Diagnostics_CompilationFailure_ctor_0__4__String_String_String_System_Collections_Generic_IEnumerable_Microsoft_AspNetCore_Diagnostics_DiagnosticMessage_(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NULLABLE sourceFilePath, SG_HNDL_NULLABLE sourceFileContent, SG_HNDL_NULLABLE compiledContent, SG_HNDL_NULLABLE messages) {
    if (!_g_Microsoft_AspNetCore_Diagnostics_Abstractions._fp_Microsoft_AspNetCore_Diagnostics_CompilationFailure_ctor_0__4__String_String_String_System_Collections_Generic_IEnumerable_Microsoft_AspNetCore_Diagnostics_DiagnosticMessage_) {
        my_init();
    }
    SG_HNDL_NONNULL ret = _g_Microsoft_AspNetCore_Diagnostics_Abstractions._fp_Microsoft_AspNetCore_Diagnostics_CompilationFailure_ctor_0__4__String_String_String_System_Collections_Generic_IEnumerable_Microsoft_AspNetCore_Diagnostics_DiagnosticMessage_(__thrown, sourceFilePath, sourceFileContent, compiledContent, messages);
    return ret;
}

SG_HNDL_NONNULL Microsoft_AspNetCore_Diagnostics_CompilationFailure_ctor_0__5__String_String_String_System_Collections_Generic_IEnumerable_Microsoft_AspNetCore_Diagnostics_DiagnosticMessage__String(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NULLABLE sourceFilePath, SG_HNDL_NULLABLE sourceFileContent, SG_HNDL_NULLABLE compiledContent, SG_HNDL_NULLABLE messages, SG_HNDL_NULLABLE failureSummary) {
    if (!_g_Microsoft_AspNetCore_Diagnostics_Abstractions._fp_Microsoft_AspNetCore_Diagnostics_CompilationFailure_ctor_0__5__String_String_String_System_Collections_Generic_IEnumerable_Microsoft_AspNetCore_Diagnostics_DiagnosticMessage__String) {
        my_init();
    }
    SG_HNDL_NONNULL ret = _g_Microsoft_AspNetCore_Diagnostics_Abstractions._fp_Microsoft_AspNetCore_Diagnostics_CompilationFailure_ctor_0__5__String_String_String_System_Collections_Generic_IEnumerable_Microsoft_AspNetCore_Diagnostics_DiagnosticMessage__String(__thrown, sourceFilePath, sourceFileContent, compiledContent, messages, failureSummary);
    return ret;
}

SG_HNDL_NULLABLE Microsoft_AspNetCore_Diagnostics_CompilationFailure_String__get_SourceFilePath_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h) {
    if (!_g_Microsoft_AspNetCore_Diagnostics_Abstractions._fp_Microsoft_AspNetCore_Diagnostics_CompilationFailure_String__get_SourceFilePath_0__0) {
        my_init();
    }
    SG_HNDL_NULLABLE ret = _g_Microsoft_AspNetCore_Diagnostics_Abstractions._fp_Microsoft_AspNetCore_Diagnostics_CompilationFailure_String__get_SourceFilePath_0__0(__thrown, __self_h);
    return ret;
}

SG_HNDL_NULLABLE Microsoft_AspNetCore_Diagnostics_CompilationFailure_String__get_SourceFileContent_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h) {
    if (!_g_Microsoft_AspNetCore_Diagnostics_Abstractions._fp_Microsoft_AspNetCore_Diagnostics_CompilationFailure_String__get_SourceFileContent_0__0) {
        my_init();
    }
    SG_HNDL_NULLABLE ret = _g_Microsoft_AspNetCore_Diagnostics_Abstractions._fp_Microsoft_AspNetCore_Diagnostics_CompilationFailure_String__get_SourceFileContent_0__0(__thrown, __self_h);
    return ret;
}

SG_HNDL_NULLABLE Microsoft_AspNetCore_Diagnostics_CompilationFailure_String__get_CompiledContent_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h) {
    if (!_g_Microsoft_AspNetCore_Diagnostics_Abstractions._fp_Microsoft_AspNetCore_Diagnostics_CompilationFailure_String__get_CompiledContent_0__0) {
        my_init();
    }
    SG_HNDL_NULLABLE ret = _g_Microsoft_AspNetCore_Diagnostics_Abstractions._fp_Microsoft_AspNetCore_Diagnostics_CompilationFailure_String__get_CompiledContent_0__0(__thrown, __self_h);
    return ret;
}

SG_HNDL_NULLABLE Microsoft_AspNetCore_Diagnostics_CompilationFailure_System_Collections_Generic_IEnumerable_Microsoft_AspNetCore_Diagnostics_DiagnosticMessage___get_Messages_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h) {
    if (!_g_Microsoft_AspNetCore_Diagnostics_Abstractions._fp_Microsoft_AspNetCore_Diagnostics_CompilationFailure_System_Collections_Generic_IEnumerable_Microsoft_AspNetCore_Diagnostics_DiagnosticMessage___get_Messages_0__0) {
        my_init();
    }
    SG_HNDL_NULLABLE ret = _g_Microsoft_AspNetCore_Diagnostics_Abstractions._fp_Microsoft_AspNetCore_Diagnostics_CompilationFailure_System_Collections_Generic_IEnumerable_Microsoft_AspNetCore_Diagnostics_DiagnosticMessage___get_Messages_0__0(__thrown, __self_h);
    return ret;
}

SG_HNDL_NULLABLE Microsoft_AspNetCore_Diagnostics_CompilationFailure_String__get_FailureSummary_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h) {
    if (!_g_Microsoft_AspNetCore_Diagnostics_Abstractions._fp_Microsoft_AspNetCore_Diagnostics_CompilationFailure_String__get_FailureSummary_0__0) {
        my_init();
    }
    SG_HNDL_NULLABLE ret = _g_Microsoft_AspNetCore_Diagnostics_Abstractions._fp_Microsoft_AspNetCore_Diagnostics_CompilationFailure_String__get_FailureSummary_0__0(__thrown, __self_h);
    return ret;
}

SG_HNDL_NONNULL Microsoft_AspNetCore_Diagnostics_CompilationFailure_cast(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __h) {
    if (!_g_Microsoft_AspNetCore_Diagnostics_Abstractions._fp_Microsoft_AspNetCore_Diagnostics_CompilationFailure_cast) {
        my_init();
    }
    SG_HNDL_NONNULL ret = _g_Microsoft_AspNetCore_Diagnostics_Abstractions._fp_Microsoft_AspNetCore_Diagnostics_CompilationFailure_cast(__thrown, __h);
    return ret;
}

TYP Microsoft_AspNetCore_Diagnostics_DiagnosticMessage_get_type_handle(void) {
    if (!_g_Microsoft_AspNetCore_Diagnostics_Abstractions._fp_Microsoft_AspNetCore_Diagnostics_DiagnosticMessage_get_type_handle) {
        my_init();
    }
    TYP ret = _g_Microsoft_AspNetCore_Diagnostics_Abstractions._fp_Microsoft_AspNetCore_Diagnostics_DiagnosticMessage_get_type_handle();
    return ret;
}

SG_HNDL_NONNULL Microsoft_AspNetCore_Diagnostics_DiagnosticMessage_ctor_0__7__String_String_String_i32_i32_i32_i32(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NULLABLE message, SG_HNDL_NULLABLE formattedMessage, SG_HNDL_NULLABLE filePath, int32_t startLine, int32_t startColumn, int32_t endLine, int32_t endColumn) {
    if (!_g_Microsoft_AspNetCore_Diagnostics_Abstractions._fp_Microsoft_AspNetCore_Diagnostics_DiagnosticMessage_ctor_0__7__String_String_String_i32_i32_i32_i32) {
        my_init();
    }
    SG_HNDL_NONNULL ret = _g_Microsoft_AspNetCore_Diagnostics_Abstractions._fp_Microsoft_AspNetCore_Diagnostics_DiagnosticMessage_ctor_0__7__String_String_String_i32_i32_i32_i32(__thrown, message, formattedMessage, filePath, startLine, startColumn, endLine, endColumn);
    return ret;
}

SG_HNDL_NULLABLE Microsoft_AspNetCore_Diagnostics_DiagnosticMessage_String__get_SourceFilePath_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h) {
    if (!_g_Microsoft_AspNetCore_Diagnostics_Abstractions._fp_Microsoft_AspNetCore_Diagnostics_DiagnosticMessage_String__get_SourceFilePath_0__0) {
        my_init();
    }
    SG_HNDL_NULLABLE ret = _g_Microsoft_AspNetCore_Diagnostics_Abstractions._fp_Microsoft_AspNetCore_Diagnostics_DiagnosticMessage_String__get_SourceFilePath_0__0(__thrown, __self_h);
    return ret;
}

SG_HNDL_NULLABLE Microsoft_AspNetCore_Diagnostics_DiagnosticMessage_String__get_Message_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h) {
    if (!_g_Microsoft_AspNetCore_Diagnostics_Abstractions._fp_Microsoft_AspNetCore_Diagnostics_DiagnosticMessage_String__get_Message_0__0) {
        my_init();
    }
    SG_HNDL_NULLABLE ret = _g_Microsoft_AspNetCore_Diagnostics_Abstractions._fp_Microsoft_AspNetCore_Diagnostics_DiagnosticMessage_String__get_Message_0__0(__thrown, __self_h);
    return ret;
}

int32_t Microsoft_AspNetCore_Diagnostics_DiagnosticMessage_i32__get_StartLine_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h) {
    if (!_g_Microsoft_AspNetCore_Diagnostics_Abstractions._fp_Microsoft_AspNetCore_Diagnostics_DiagnosticMessage_i32__get_StartLine_0__0) {
        my_init();
    }
    int32_t ret = _g_Microsoft_AspNetCore_Diagnostics_Abstractions._fp_Microsoft_AspNetCore_Diagnostics_DiagnosticMessage_i32__get_StartLine_0__0(__thrown, __self_h);
    return ret;
}

int32_t Microsoft_AspNetCore_Diagnostics_DiagnosticMessage_i32__get_StartColumn_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h) {
    if (!_g_Microsoft_AspNetCore_Diagnostics_Abstractions._fp_Microsoft_AspNetCore_Diagnostics_DiagnosticMessage_i32__get_StartColumn_0__0) {
        my_init();
    }
    int32_t ret = _g_Microsoft_AspNetCore_Diagnostics_Abstractions._fp_Microsoft_AspNetCore_Diagnostics_DiagnosticMessage_i32__get_StartColumn_0__0(__thrown, __self_h);
    return ret;
}

int32_t Microsoft_AspNetCore_Diagnostics_DiagnosticMessage_i32__get_EndLine_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h) {
    if (!_g_Microsoft_AspNetCore_Diagnostics_Abstractions._fp_Microsoft_AspNetCore_Diagnostics_DiagnosticMessage_i32__get_EndLine_0__0) {
        my_init();
    }
    int32_t ret = _g_Microsoft_AspNetCore_Diagnostics_Abstractions._fp_Microsoft_AspNetCore_Diagnostics_DiagnosticMessage_i32__get_EndLine_0__0(__thrown, __self_h);
    return ret;
}

int32_t Microsoft_AspNetCore_Diagnostics_DiagnosticMessage_i32__get_EndColumn_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h) {
    if (!_g_Microsoft_AspNetCore_Diagnostics_Abstractions._fp_Microsoft_AspNetCore_Diagnostics_DiagnosticMessage_i32__get_EndColumn_0__0) {
        my_init();
    }
    int32_t ret = _g_Microsoft_AspNetCore_Diagnostics_Abstractions._fp_Microsoft_AspNetCore_Diagnostics_DiagnosticMessage_i32__get_EndColumn_0__0(__thrown, __self_h);
    return ret;
}

SG_HNDL_NULLABLE Microsoft_AspNetCore_Diagnostics_DiagnosticMessage_String__get_FormattedMessage_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h) {
    if (!_g_Microsoft_AspNetCore_Diagnostics_Abstractions._fp_Microsoft_AspNetCore_Diagnostics_DiagnosticMessage_String__get_FormattedMessage_0__0) {
        my_init();
    }
    SG_HNDL_NULLABLE ret = _g_Microsoft_AspNetCore_Diagnostics_Abstractions._fp_Microsoft_AspNetCore_Diagnostics_DiagnosticMessage_String__get_FormattedMessage_0__0(__thrown, __self_h);
    return ret;
}

SG_HNDL_NONNULL Microsoft_AspNetCore_Diagnostics_DiagnosticMessage_cast(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __h) {
    if (!_g_Microsoft_AspNetCore_Diagnostics_Abstractions._fp_Microsoft_AspNetCore_Diagnostics_DiagnosticMessage_cast) {
        my_init();
    }
    SG_HNDL_NONNULL ret = _g_Microsoft_AspNetCore_Diagnostics_Abstractions._fp_Microsoft_AspNetCore_Diagnostics_DiagnosticMessage_cast(__thrown, __h);
    return ret;
}

TYP Microsoft_AspNetCore_Diagnostics_ErrorContext_get_type_handle(void) {
    if (!_g_Microsoft_AspNetCore_Diagnostics_Abstractions._fp_Microsoft_AspNetCore_Diagnostics_ErrorContext_get_type_handle) {
        my_init();
    }
    TYP ret = _g_Microsoft_AspNetCore_Diagnostics_Abstractions._fp_Microsoft_AspNetCore_Diagnostics_ErrorContext_get_type_handle();
    return ret;
}

SG_HNDL_NONNULL Microsoft_AspNetCore_Diagnostics_ErrorContext_ctor_0__2__HttpContext_Exception(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL httpContext, SG_HNDL_NONNULL exception) {
    if (!_g_Microsoft_AspNetCore_Diagnostics_Abstractions._fp_Microsoft_AspNetCore_Diagnostics_ErrorContext_ctor_0__2__HttpContext_Exception) {
        my_init();
    }
    SG_HNDL_NONNULL ret = _g_Microsoft_AspNetCore_Diagnostics_Abstractions._fp_Microsoft_AspNetCore_Diagnostics_ErrorContext_ctor_0__2__HttpContext_Exception(__thrown, httpContext, exception);
    return ret;
}

SG_HNDL_NONNULL Microsoft_AspNetCore_Diagnostics_ErrorContext_HttpContext__get_HttpContext_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h) {
    if (!_g_Microsoft_AspNetCore_Diagnostics_Abstractions._fp_Microsoft_AspNetCore_Diagnostics_ErrorContext_HttpContext__get_HttpContext_0__0) {
        my_init();
    }
    SG_HNDL_NONNULL ret = _g_Microsoft_AspNetCore_Diagnostics_Abstractions._fp_Microsoft_AspNetCore_Diagnostics_ErrorContext_HttpContext__get_HttpContext_0__0(__thrown, __self_h);
    return ret;
}

SG_HNDL_NONNULL Microsoft_AspNetCore_Diagnostics_ErrorContext_Exception__get_Exception_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h) {
    if (!_g_Microsoft_AspNetCore_Diagnostics_Abstractions._fp_Microsoft_AspNetCore_Diagnostics_ErrorContext_Exception__get_Exception_0__0) {
        my_init();
    }
    SG_HNDL_NONNULL ret = _g_Microsoft_AspNetCore_Diagnostics_Abstractions._fp_Microsoft_AspNetCore_Diagnostics_ErrorContext_Exception__get_Exception_0__0(__thrown, __self_h);
    return ret;
}

SG_HNDL_NONNULL Microsoft_AspNetCore_Diagnostics_ErrorContext_cast(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __h) {
    if (!_g_Microsoft_AspNetCore_Diagnostics_Abstractions._fp_Microsoft_AspNetCore_Diagnostics_ErrorContext_cast) {
        my_init();
    }
    SG_HNDL_NONNULL ret = _g_Microsoft_AspNetCore_Diagnostics_Abstractions._fp_Microsoft_AspNetCore_Diagnostics_ErrorContext_cast(__thrown, __h);
    return ret;
}

TYP Microsoft_AspNetCore_Diagnostics_ICompilationException_get_type_handle(void) {
    if (!_g_Microsoft_AspNetCore_Diagnostics_Abstractions._fp_Microsoft_AspNetCore_Diagnostics_ICompilationException_get_type_handle) {
        my_init();
    }
    TYP ret = _g_Microsoft_AspNetCore_Diagnostics_Abstractions._fp_Microsoft_AspNetCore_Diagnostics_ICompilationException_get_type_handle();
    return ret;
}

SG_HNDL_NULLABLE Microsoft_AspNetCore_Diagnostics_ICompilationException_System_Collections_Generic_IEnumerable_Microsoft_AspNetCore_Diagnostics_CompilationFailure___get_CompilationFailures_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h) {
    if (!_g_Microsoft_AspNetCore_Diagnostics_Abstractions._fp_Microsoft_AspNetCore_Diagnostics_ICompilationException_System_Collections_Generic_IEnumerable_Microsoft_AspNetCore_Diagnostics_CompilationFailure___get_CompilationFailures_0__0) {
        my_init();
    }
    SG_HNDL_NULLABLE ret = _g_Microsoft_AspNetCore_Diagnostics_Abstractions._fp_Microsoft_AspNetCore_Diagnostics_ICompilationException_System_Collections_Generic_IEnumerable_Microsoft_AspNetCore_Diagnostics_CompilationFailure___get_CompilationFailures_0__0(__thrown, __self_h);
    return ret;
}

SG_HNDL_NONNULL Microsoft_AspNetCore_Diagnostics_ICompilationException_cast(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __h) {
    if (!_g_Microsoft_AspNetCore_Diagnostics_Abstractions._fp_Microsoft_AspNetCore_Diagnostics_ICompilationException_cast) {
        my_init();
    }
    SG_HNDL_NONNULL ret = _g_Microsoft_AspNetCore_Diagnostics_Abstractions._fp_Microsoft_AspNetCore_Diagnostics_ICompilationException_cast(__thrown, __h);
    return ret;
}

SG_HNDL_NONNULL Microsoft_AspNetCore_Diagnostics_ICompilationException_create(SG_HNDL_NULLABLE * _Nonnull __thrown, void (* _Nullable __deinit)(const void* _Nonnull __pdata)) {
    if (!_g_Microsoft_AspNetCore_Diagnostics_Abstractions._fp_Microsoft_AspNetCore_Diagnostics_ICompilationException_create) {
        my_init();
    }
    SG_HNDL_NONNULL ret = _g_Microsoft_AspNetCore_Diagnostics_Abstractions._fp_Microsoft_AspNetCore_Diagnostics_ICompilationException_create(__thrown, __deinit);
    return ret;
}

TYP Microsoft_AspNetCore_Diagnostics_IDeveloperPageExceptionFilter_get_type_handle(void) {
    if (!_g_Microsoft_AspNetCore_Diagnostics_Abstractions._fp_Microsoft_AspNetCore_Diagnostics_IDeveloperPageExceptionFilter_get_type_handle) {
        my_init();
    }
    TYP ret = _g_Microsoft_AspNetCore_Diagnostics_Abstractions._fp_Microsoft_AspNetCore_Diagnostics_IDeveloperPageExceptionFilter_get_type_handle();
    return ret;
}

SG_HNDL_NONNULL Microsoft_AspNetCore_Diagnostics_IDeveloperPageExceptionFilter_Task__HandleExceptionAsync_0__2__ErrorContext_System_Func_Microsoft_AspNetCore_Diagnostics_ErrorContext_Task_(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h, SG_HNDL_NONNULL errorContext, SG_HNDL_NONNULL next) {
    if (!_g_Microsoft_AspNetCore_Diagnostics_Abstractions._fp_Microsoft_AspNetCore_Diagnostics_IDeveloperPageExceptionFilter_Task__HandleExceptionAsync_0__2__ErrorContext_System_Func_Microsoft_AspNetCore_Diagnostics_ErrorContext_Task_) {
        my_init();
    }
    SG_HNDL_NONNULL ret = _g_Microsoft_AspNetCore_Diagnostics_Abstractions._fp_Microsoft_AspNetCore_Diagnostics_IDeveloperPageExceptionFilter_Task__HandleExceptionAsync_0__2__ErrorContext_System_Func_Microsoft_AspNetCore_Diagnostics_ErrorContext_Task_(__thrown, __self_h, errorContext, next);
    return ret;
}

SG_HNDL_NONNULL Microsoft_AspNetCore_Diagnostics_IDeveloperPageExceptionFilter_cast(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __h) {
    if (!_g_Microsoft_AspNetCore_Diagnostics_Abstractions._fp_Microsoft_AspNetCore_Diagnostics_IDeveloperPageExceptionFilter_cast) {
        my_init();
    }
    SG_HNDL_NONNULL ret = _g_Microsoft_AspNetCore_Diagnostics_Abstractions._fp_Microsoft_AspNetCore_Diagnostics_IDeveloperPageExceptionFilter_cast(__thrown, __h);
    return ret;
}

SG_HNDL_NONNULL Microsoft_AspNetCore_Diagnostics_IDeveloperPageExceptionFilter_create(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL (* _Nonnull  __cb_Microsoft_AspNetCore_Diagnostics_IDeveloperPageExceptionFilter_Task__HandleExceptionAsync_0__2__ErrorContext_System_Func_Microsoft_AspNetCore_Diagnostics_ErrorContext_Task_)(const void* _Nonnull __pdata, SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL errorContext, SG_HNDL_NONNULL next), const void* _Nonnull __pdata_Microsoft_AspNetCore_Diagnostics_IDeveloperPageExceptionFilter_Task__HandleExceptionAsync_0__2__ErrorContext_System_Func_Microsoft_AspNetCore_Diagnostics_ErrorContext_Task_, void (* _Nullable __deinit)(const void* _Nonnull __pdata)) {
    if (!_g_Microsoft_AspNetCore_Diagnostics_Abstractions._fp_Microsoft_AspNetCore_Diagnostics_IDeveloperPageExceptionFilter_create) {
        my_init();
    }
    SG_HNDL_NONNULL ret = _g_Microsoft_AspNetCore_Diagnostics_Abstractions._fp_Microsoft_AspNetCore_Diagnostics_IDeveloperPageExceptionFilter_create(__thrown, __cb_Microsoft_AspNetCore_Diagnostics_IDeveloperPageExceptionFilter_Task__HandleExceptionAsync_0__2__ErrorContext_System_Func_Microsoft_AspNetCore_Diagnostics_ErrorContext_Task_, __pdata_Microsoft_AspNetCore_Diagnostics_IDeveloperPageExceptionFilter_Task__HandleExceptionAsync_0__2__ErrorContext_System_Func_Microsoft_AspNetCore_Diagnostics_ErrorContext_Task_, __deinit);
    return ret;
}

TYP Microsoft_AspNetCore_Diagnostics_IExceptionHandlerFeature_get_type_handle(void) {
    if (!_g_Microsoft_AspNetCore_Diagnostics_Abstractions._fp_Microsoft_AspNetCore_Diagnostics_IExceptionHandlerFeature_get_type_handle) {
        my_init();
    }
    TYP ret = _g_Microsoft_AspNetCore_Diagnostics_Abstractions._fp_Microsoft_AspNetCore_Diagnostics_IExceptionHandlerFeature_get_type_handle();
    return ret;
}

SG_HNDL_NONNULL Microsoft_AspNetCore_Diagnostics_IExceptionHandlerFeature_Exception__get_Error_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h) {
    if (!_g_Microsoft_AspNetCore_Diagnostics_Abstractions._fp_Microsoft_AspNetCore_Diagnostics_IExceptionHandlerFeature_Exception__get_Error_0__0) {
        my_init();
    }
    SG_HNDL_NONNULL ret = _g_Microsoft_AspNetCore_Diagnostics_Abstractions._fp_Microsoft_AspNetCore_Diagnostics_IExceptionHandlerFeature_Exception__get_Error_0__0(__thrown, __self_h);
    return ret;
}

SG_HNDL_NONNULL Microsoft_AspNetCore_Diagnostics_IExceptionHandlerFeature_String__get_Path_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h) {
    if (!_g_Microsoft_AspNetCore_Diagnostics_Abstractions._fp_Microsoft_AspNetCore_Diagnostics_IExceptionHandlerFeature_String__get_Path_0__0) {
        my_init();
    }
    SG_HNDL_NONNULL ret = _g_Microsoft_AspNetCore_Diagnostics_Abstractions._fp_Microsoft_AspNetCore_Diagnostics_IExceptionHandlerFeature_String__get_Path_0__0(__thrown, __self_h);
    return ret;
}

SG_HNDL_NULLABLE Microsoft_AspNetCore_Diagnostics_IExceptionHandlerFeature_Endpoint__get_Endpoint_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h) {
    if (!_g_Microsoft_AspNetCore_Diagnostics_Abstractions._fp_Microsoft_AspNetCore_Diagnostics_IExceptionHandlerFeature_Endpoint__get_Endpoint_0__0) {
        my_init();
    }
    SG_HNDL_NULLABLE ret = _g_Microsoft_AspNetCore_Diagnostics_Abstractions._fp_Microsoft_AspNetCore_Diagnostics_IExceptionHandlerFeature_Endpoint__get_Endpoint_0__0(__thrown, __self_h);
    return ret;
}

SG_HNDL_NULLABLE Microsoft_AspNetCore_Diagnostics_IExceptionHandlerFeature_RouteValueDictionary__get_RouteValues_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h) {
    if (!_g_Microsoft_AspNetCore_Diagnostics_Abstractions._fp_Microsoft_AspNetCore_Diagnostics_IExceptionHandlerFeature_RouteValueDictionary__get_RouteValues_0__0) {
        my_init();
    }
    SG_HNDL_NULLABLE ret = _g_Microsoft_AspNetCore_Diagnostics_Abstractions._fp_Microsoft_AspNetCore_Diagnostics_IExceptionHandlerFeature_RouteValueDictionary__get_RouteValues_0__0(__thrown, __self_h);
    return ret;
}

SG_HNDL_NONNULL Microsoft_AspNetCore_Diagnostics_IExceptionHandlerFeature_cast(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __h) {
    if (!_g_Microsoft_AspNetCore_Diagnostics_Abstractions._fp_Microsoft_AspNetCore_Diagnostics_IExceptionHandlerFeature_cast) {
        my_init();
    }
    SG_HNDL_NONNULL ret = _g_Microsoft_AspNetCore_Diagnostics_Abstractions._fp_Microsoft_AspNetCore_Diagnostics_IExceptionHandlerFeature_cast(__thrown, __h);
    return ret;
}

SG_HNDL_NONNULL Microsoft_AspNetCore_Diagnostics_IExceptionHandlerFeature_create(SG_HNDL_NULLABLE * _Nonnull __thrown, void (* _Nullable __deinit)(const void* _Nonnull __pdata)) {
    if (!_g_Microsoft_AspNetCore_Diagnostics_Abstractions._fp_Microsoft_AspNetCore_Diagnostics_IExceptionHandlerFeature_create) {
        my_init();
    }
    SG_HNDL_NONNULL ret = _g_Microsoft_AspNetCore_Diagnostics_Abstractions._fp_Microsoft_AspNetCore_Diagnostics_IExceptionHandlerFeature_create(__thrown, __deinit);
    return ret;
}

TYP Microsoft_AspNetCore_Diagnostics_IExceptionHandlerPathFeature_get_type_handle(void) {
    if (!_g_Microsoft_AspNetCore_Diagnostics_Abstractions._fp_Microsoft_AspNetCore_Diagnostics_IExceptionHandlerPathFeature_get_type_handle) {
        my_init();
    }
    TYP ret = _g_Microsoft_AspNetCore_Diagnostics_Abstractions._fp_Microsoft_AspNetCore_Diagnostics_IExceptionHandlerPathFeature_get_type_handle();
    return ret;
}

SG_HNDL_NONNULL Microsoft_AspNetCore_Diagnostics_IExceptionHandlerPathFeature_String__get_Path_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h) {
    if (!_g_Microsoft_AspNetCore_Diagnostics_Abstractions._fp_Microsoft_AspNetCore_Diagnostics_IExceptionHandlerPathFeature_String__get_Path_0__0) {
        my_init();
    }
    SG_HNDL_NONNULL ret = _g_Microsoft_AspNetCore_Diagnostics_Abstractions._fp_Microsoft_AspNetCore_Diagnostics_IExceptionHandlerPathFeature_String__get_Path_0__0(__thrown, __self_h);
    return ret;
}

SG_HNDL_NONNULL Microsoft_AspNetCore_Diagnostics_IExceptionHandlerPathFeature_cast(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __h) {
    if (!_g_Microsoft_AspNetCore_Diagnostics_Abstractions._fp_Microsoft_AspNetCore_Diagnostics_IExceptionHandlerPathFeature_cast) {
        my_init();
    }
    SG_HNDL_NONNULL ret = _g_Microsoft_AspNetCore_Diagnostics_Abstractions._fp_Microsoft_AspNetCore_Diagnostics_IExceptionHandlerPathFeature_cast(__thrown, __h);
    return ret;
}

SG_HNDL_NONNULL Microsoft_AspNetCore_Diagnostics_IExceptionHandlerPathFeature_create(SG_HNDL_NULLABLE * _Nonnull __thrown, void (* _Nullable __deinit)(const void* _Nonnull __pdata)) {
    if (!_g_Microsoft_AspNetCore_Diagnostics_Abstractions._fp_Microsoft_AspNetCore_Diagnostics_IExceptionHandlerPathFeature_create) {
        my_init();
    }
    SG_HNDL_NONNULL ret = _g_Microsoft_AspNetCore_Diagnostics_Abstractions._fp_Microsoft_AspNetCore_Diagnostics_IExceptionHandlerPathFeature_create(__thrown, __deinit);
    return ret;
}

TYP Microsoft_AspNetCore_Diagnostics_IStatusCodePagesFeature_get_type_handle(void) {
    if (!_g_Microsoft_AspNetCore_Diagnostics_Abstractions._fp_Microsoft_AspNetCore_Diagnostics_IStatusCodePagesFeature_get_type_handle) {
        my_init();
    }
    TYP ret = _g_Microsoft_AspNetCore_Diagnostics_Abstractions._fp_Microsoft_AspNetCore_Diagnostics_IStatusCodePagesFeature_get_type_handle();
    return ret;
}

int32_t Microsoft_AspNetCore_Diagnostics_IStatusCodePagesFeature_bool__get_Enabled_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h) {
    if (!_g_Microsoft_AspNetCore_Diagnostics_Abstractions._fp_Microsoft_AspNetCore_Diagnostics_IStatusCodePagesFeature_bool__get_Enabled_0__0) {
        my_init();
    }
    int32_t ret = _g_Microsoft_AspNetCore_Diagnostics_Abstractions._fp_Microsoft_AspNetCore_Diagnostics_IStatusCodePagesFeature_bool__get_Enabled_0__0(__thrown, __self_h);
    return ret;
}

void Microsoft_AspNetCore_Diagnostics_IStatusCodePagesFeature_void__set_Enabled_0__1__bool(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h, int32_t value) {
    if (!_g_Microsoft_AspNetCore_Diagnostics_Abstractions._fp_Microsoft_AspNetCore_Diagnostics_IStatusCodePagesFeature_void__set_Enabled_0__1__bool) {
        my_init();
    }
    _g_Microsoft_AspNetCore_Diagnostics_Abstractions._fp_Microsoft_AspNetCore_Diagnostics_IStatusCodePagesFeature_void__set_Enabled_0__1__bool(__thrown, __self_h, value);
}

SG_HNDL_NONNULL Microsoft_AspNetCore_Diagnostics_IStatusCodePagesFeature_cast(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __h) {
    if (!_g_Microsoft_AspNetCore_Diagnostics_Abstractions._fp_Microsoft_AspNetCore_Diagnostics_IStatusCodePagesFeature_cast) {
        my_init();
    }
    SG_HNDL_NONNULL ret = _g_Microsoft_AspNetCore_Diagnostics_Abstractions._fp_Microsoft_AspNetCore_Diagnostics_IStatusCodePagesFeature_cast(__thrown, __h);
    return ret;
}

SG_HNDL_NONNULL Microsoft_AspNetCore_Diagnostics_IStatusCodePagesFeature_create(SG_HNDL_NULLABLE * _Nonnull __thrown, void (* _Nullable __deinit)(const void* _Nonnull __pdata)) {
    if (!_g_Microsoft_AspNetCore_Diagnostics_Abstractions._fp_Microsoft_AspNetCore_Diagnostics_IStatusCodePagesFeature_create) {
        my_init();
    }
    SG_HNDL_NONNULL ret = _g_Microsoft_AspNetCore_Diagnostics_Abstractions._fp_Microsoft_AspNetCore_Diagnostics_IStatusCodePagesFeature_create(__thrown, __deinit);
    return ret;
}

TYP Microsoft_AspNetCore_Diagnostics_IStatusCodeReExecuteFeature_get_type_handle(void) {
    if (!_g_Microsoft_AspNetCore_Diagnostics_Abstractions._fp_Microsoft_AspNetCore_Diagnostics_IStatusCodeReExecuteFeature_get_type_handle) {
        my_init();
    }
    TYP ret = _g_Microsoft_AspNetCore_Diagnostics_Abstractions._fp_Microsoft_AspNetCore_Diagnostics_IStatusCodeReExecuteFeature_get_type_handle();
    return ret;
}

SG_HNDL_NONNULL Microsoft_AspNetCore_Diagnostics_IStatusCodeReExecuteFeature_String__get_OriginalPathBase_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h) {
    if (!_g_Microsoft_AspNetCore_Diagnostics_Abstractions._fp_Microsoft_AspNetCore_Diagnostics_IStatusCodeReExecuteFeature_String__get_OriginalPathBase_0__0) {
        my_init();
    }
    SG_HNDL_NONNULL ret = _g_Microsoft_AspNetCore_Diagnostics_Abstractions._fp_Microsoft_AspNetCore_Diagnostics_IStatusCodeReExecuteFeature_String__get_OriginalPathBase_0__0(__thrown, __self_h);
    return ret;
}

void Microsoft_AspNetCore_Diagnostics_IStatusCodeReExecuteFeature_void__set_OriginalPathBase_0__1__String(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h, SG_HNDL_NONNULL value) {
    if (!_g_Microsoft_AspNetCore_Diagnostics_Abstractions._fp_Microsoft_AspNetCore_Diagnostics_IStatusCodeReExecuteFeature_void__set_OriginalPathBase_0__1__String) {
        my_init();
    }
    _g_Microsoft_AspNetCore_Diagnostics_Abstractions._fp_Microsoft_AspNetCore_Diagnostics_IStatusCodeReExecuteFeature_void__set_OriginalPathBase_0__1__String(__thrown, __self_h, value);
}

SG_HNDL_NONNULL Microsoft_AspNetCore_Diagnostics_IStatusCodeReExecuteFeature_String__get_OriginalPath_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h) {
    if (!_g_Microsoft_AspNetCore_Diagnostics_Abstractions._fp_Microsoft_AspNetCore_Diagnostics_IStatusCodeReExecuteFeature_String__get_OriginalPath_0__0) {
        my_init();
    }
    SG_HNDL_NONNULL ret = _g_Microsoft_AspNetCore_Diagnostics_Abstractions._fp_Microsoft_AspNetCore_Diagnostics_IStatusCodeReExecuteFeature_String__get_OriginalPath_0__0(__thrown, __self_h);
    return ret;
}

void Microsoft_AspNetCore_Diagnostics_IStatusCodeReExecuteFeature_void__set_OriginalPath_0__1__String(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h, SG_HNDL_NONNULL value) {
    if (!_g_Microsoft_AspNetCore_Diagnostics_Abstractions._fp_Microsoft_AspNetCore_Diagnostics_IStatusCodeReExecuteFeature_void__set_OriginalPath_0__1__String) {
        my_init();
    }
    _g_Microsoft_AspNetCore_Diagnostics_Abstractions._fp_Microsoft_AspNetCore_Diagnostics_IStatusCodeReExecuteFeature_void__set_OriginalPath_0__1__String(__thrown, __self_h, value);
}

SG_HNDL_NULLABLE Microsoft_AspNetCore_Diagnostics_IStatusCodeReExecuteFeature_String__get_OriginalQueryString_0__0(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h) {
    if (!_g_Microsoft_AspNetCore_Diagnostics_Abstractions._fp_Microsoft_AspNetCore_Diagnostics_IStatusCodeReExecuteFeature_String__get_OriginalQueryString_0__0) {
        my_init();
    }
    SG_HNDL_NULLABLE ret = _g_Microsoft_AspNetCore_Diagnostics_Abstractions._fp_Microsoft_AspNetCore_Diagnostics_IStatusCodeReExecuteFeature_String__get_OriginalQueryString_0__0(__thrown, __self_h);
    return ret;
}

void Microsoft_AspNetCore_Diagnostics_IStatusCodeReExecuteFeature_void__set_OriginalQueryString_0__1__String(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __self_h, SG_HNDL_NULLABLE value) {
    if (!_g_Microsoft_AspNetCore_Diagnostics_Abstractions._fp_Microsoft_AspNetCore_Diagnostics_IStatusCodeReExecuteFeature_void__set_OriginalQueryString_0__1__String) {
        my_init();
    }
    _g_Microsoft_AspNetCore_Diagnostics_Abstractions._fp_Microsoft_AspNetCore_Diagnostics_IStatusCodeReExecuteFeature_void__set_OriginalQueryString_0__1__String(__thrown, __self_h, value);
}

SG_HNDL_NONNULL Microsoft_AspNetCore_Diagnostics_IStatusCodeReExecuteFeature_cast(SG_HNDL_NULLABLE * _Nonnull __thrown, SG_HNDL_NONNULL __h) {
    if (!_g_Microsoft_AspNetCore_Diagnostics_Abstractions._fp_Microsoft_AspNetCore_Diagnostics_IStatusCodeReExecuteFeature_cast) {
        my_init();
    }
    SG_HNDL_NONNULL ret = _g_Microsoft_AspNetCore_Diagnostics_Abstractions._fp_Microsoft_AspNetCore_Diagnostics_IStatusCodeReExecuteFeature_cast(__thrown, __h);
    return ret;
}

SG_HNDL_NONNULL Microsoft_AspNetCore_Diagnostics_IStatusCodeReExecuteFeature_create(SG_HNDL_NULLABLE * _Nonnull __thrown, void (* _Nullable __deinit)(const void* _Nonnull __pdata)) {
    if (!_g_Microsoft_AspNetCore_Diagnostics_Abstractions._fp_Microsoft_AspNetCore_Diagnostics_IStatusCodeReExecuteFeature_create) {
        my_init();
    }
    SG_HNDL_NONNULL ret = _g_Microsoft_AspNetCore_Diagnostics_Abstractions._fp_Microsoft_AspNetCore_Diagnostics_IStatusCodeReExecuteFeature_create(__thrown, __deinit);
    return ret;
}

